//FIXME check small typos äöü, -/-

export interface ElementData {
    name: string,
    kurzsymbol: string,
    protonen: number,
    neutronen: number,
    oberkategorie: string,
    unterkategorie: string,
    hauptgruppe: number,
    periode: number,
    aussehen: string,
    aggregatszustand: string,
    struktur: string,
    haerte: number,
    volumen: number,
    radioaktiv: boolean,
    synthetischHergestellt: boolean,
    prozentsatzAnDerErdhuelle: number,
    atommasse: number,
    ionisierungsenergie: number,
    dichte: number,
    schmelzpunkt: number,
    siedepunkt: number,
    elektronegativität: number,
    flammenfarbe: string,
    wikipedia: string,
    lost: number,
    zweitname: string,
}
export const elements: ElementData[] = [
    {
        name: "Wasserstoff",
        kurzsymbol: "H",
        unterkategorie: "-/-",
        oberkategorie: "Nichtmetall",
        aussehen: "farbloses Gas",
        aggregatszustand: "gasförmig",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Wasserstoff",
        flammenfarbe: "-/-",
        zweitname: "Hydrogenium",
        protonen: 1,
        neutronen: 0,
        lost: 1,
        hauptgruppe: 1,
        periode: 1,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0.88,
        atommasse: 1.00794,
        ionisierungsenergie: 13.5984,
        dichte: 0.0736,
        schmelzpunkt: -259.14,
        siedepunkt: -252.87,
        elektronegativität: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Helium",
        kurzsymbol: "He",
        unterkategorie: "Edelgas",
        oberkategorie: "Nichtmetall",
        aussehen: "Farbloses Gas",
        aggregatszustand: "gasförmig",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Helium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 2,
        neutronen: 2,
        lost: 2,
        hauptgruppe: 18,
        periode: 1,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0.0000004,
        atommasse: 4.002602,
        ionisierungsenergie: 24.5874,
        dichte: 0.176,
        schmelzpunkt: -273,
        siedepunkt: -268.93,
        elektronegativität: 5.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Lithium",
        kurzsymbol: "Li",
        unterkategorie: "Alkalimetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß/grau",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Lithium",
        flammenfarbe: "-/-",
        zweitname: "Litium",
        protonen: 3,
        neutronen: 4,
        lost: 1,
        hauptgruppe: 1,
        periode: 2,
        haerte: 0.6,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0.006,
        atommasse: 6.941,
        ionisierungsenergie: 5.3917,
        dichte: 0.535,
        schmelzpunkt: 180.54,
        siedepunkt: 1347,
        elektronegativität: 0.98,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Beryllium",
        kurzsymbol: "Be",
        unterkategorie: "Erdalkalimetall",
        oberkategorie: "Metall",
        aussehen: "weiß-grau metallisch",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Beryllium",
        flammenfarbe: "-/-",
        zweitname: "Berillium",
        protonen: 4,
        neutronen: 5,
        lost: 2,
        hauptgruppe: 2,
        periode: 2,
        haerte: 5.5,
        volumen: 0.00000485,
        prozentsatzAnDerErdhuelle: 0.0005,
        atommasse: 9.012182,
        ionisierungsenergie: 9.3227,
        dichte: 1.848,
        schmelzpunkt: 1278,
        siedepunkt: 2970,
        elektronegativität: 1.57,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Bor",
        kurzsymbol: "B",
        unterkategorie: "-/-",
        oberkategorie: "Halbmetall",
        aussehen: "schwarz",
        aggregatszustand: "fest",
        struktur: "rhomboedrisch",
        wikipedia: "https://de.wikipedia.org/wiki/Bor",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 5,
        neutronen: 6,
        lost: 3,
        hauptgruppe: 13,
        periode: 2,
        haerte: 9.3,
        volumen: 0.00000439,
        prozentsatzAnDerErdhuelle: 0.001,
        atommasse: 10.811,
        ionisierungsenergie: 8.298,
        dichte: 2.46,
        schmelzpunkt: 2079,
        siedepunkt: 2550,
        elektronegativität: 2.04,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Kohlenstoff",
        kurzsymbol: "C",
        unterkategorie: "-/-",
        oberkategorie: "Nichtmetall",
        aussehen: "Schwarz (Graphit), farblos (Diamant), gelbbraun (Lonsdaleit)",
        aggregatszustand: "fest",
        struktur: "2 verschiedene Modifikationen",
        wikipedia: "https://de.wikipedia.org/wiki/Kohlenstoff",
        flammenfarbe: "-/-",
        zweitname: "Carboneum",
        protonen: 6,
        neutronen: 6,
        lost: 4,
        hauptgruppe: 14,
        periode: 2,
        haerte: 0.5,
        volumen: 0.00000531,
        prozentsatzAnDerErdhuelle: 0.087,
        atommasse: 12.0107,
        ionisierungsenergie: 11.2603,
        dichte: 2.267,
        schmelzpunkt: 3550,
        siedepunkt: 4827,
        elektronegativität: 2.55,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Stickstoff",
        kurzsymbol: "N",
        unterkategorie: "-/-",
        oberkategorie: "Nichtmetall",
        aussehen: "Farbloses Gas",
        aggregatszustand: "gasförmig",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Stickstoff",
        flammenfarbe: "-/-",
        zweitname: "Nitrogenium",
        protonen: 7,
        neutronen: 7,
        lost: 5,
        hauptgruppe: 15,
        periode: 2,
        haerte: 0,
        volumen: 0.00001354,
        prozentsatzAnDerErdhuelle: 0.03,
        atommasse: 14.0067,
        ionisierungsenergie: 14.5341,
        dichte: 1.897,
        schmelzpunkt: -209.86,
        siedepunkt: -195.8,
        elektronegativität: 3.04,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Sauerstoff",
        kurzsymbol: "O",
        unterkategorie: "-/-",
        oberkategorie: "Nichtmetall",
        aussehen: "Farbloses Gas",
        aggregatszustand: "gasförmig",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Sauerstoff",
        flammenfarbe: "-/-",
        zweitname: "Oxygenium",
        protonen: 8,
        neutronen: 8,
        lost: 6,
        hauptgruppe: 16,
        periode: 2,
        haerte: 0,
        volumen: 0.00001736,
        prozentsatzAnDerErdhuelle: 49.4,
        atommasse: 15.9994,
        ionisierungsenergie: 13.6181,
        dichte: 1.426,
        schmelzpunkt: -218.4,
        siedepunkt: -182.96,
        elektronegativität: 3.44,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Fluor",
        kurzsymbol: "F",
        unterkategorie: "Halogen",
        oberkategorie: "Nichtmetall",
        aussehen: "blasses, gelbliches Gas",
        aggregatszustand: "gasförmig",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Fluor",
        flammenfarbe: "-/-",
        zweitname: "Fluorum",
        protonen: 9,
        neutronen: 10,
        lost: 7,
        hauptgruppe: 17,
        periode: 2,
        haerte: 0,
        volumen: 0.0000112,
        prozentsatzAnDerErdhuelle: 0.03,
        atommasse: 18.9984032,
        ionisierungsenergie: 17.4228,
        dichte: 1.5127,
        schmelzpunkt: -219.62,
        siedepunkt: -188.14,
        elektronegativität: 3.98,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Neon",
        kurzsymbol: "Ne",
        unterkategorie: "Edelgas",
        oberkategorie: "Nichtmetall",
        aussehen: "Farbloses Gas",
        aggregatszustand: "gasförmig",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Neon",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 10,
        neutronen: 10,
        lost: 8,
        hauptgruppe: 18,
        periode: 2,
        haerte: 0,
        volumen: 0.00001323,
        prozentsatzAnDerErdhuelle: 0.0000005,
        atommasse: 20.1797,
        ionisierungsenergie: 21.5645,
        dichte: 1.444,
        schmelzpunkt: -248.67,
        siedepunkt: -246.05,
        elektronegativität: 0,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Natrium",
        kurzsymbol: "Na",
        unterkategorie: "Alkalimetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Natrium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 11,
        neutronen: 12,
        lost: 1,
        hauptgruppe: 1,
        periode: 3,
        haerte: 0.5,
        volumen: 0.00002378,
        prozentsatzAnDerErdhuelle: 2.64,
        atommasse: 22.98976928,
        ionisierungsenergie: 5.1391,
        dichte: 0.968,
        schmelzpunkt: 97.81,
        siedepunkt: 882.9,
        elektronegativität: 0.93,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Magnesium",
        kurzsymbol: "Mg",
        unterkategorie: "Erdalkalimetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Magnesium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 12,
        neutronen: 12,
        lost: 2,
        hauptgruppe: 2,
        periode: 3,
        haerte: 2.5,
        volumen: 0.000014,
        prozentsatzAnDerErdhuelle: 1.94,
        atommasse: 24.305,
        ionisierungsenergie: 7.6462,
        dichte: 1.738,
        schmelzpunkt: 648.8,
        siedepunkt: 1090,
        elektronegativität: 1.31,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Aluminium",
        kurzsymbol: "Al",
        unterkategorie: "-/-",
        oberkategorie: "Metall",
        aussehen: "silbrig",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Aluminium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 13,
        neutronen: 14,
        lost: 3,
        hauptgruppe: 13,
        periode: 3,
        haerte: 2.75,
        volumen: 0.00001,
        prozentsatzAnDerErdhuelle: 7.57,
        atommasse: 26.9815386,
        ionisierungsenergie: 5.9858,
        dichte: 2.7,
        schmelzpunkt: 660.37,
        siedepunkt: 2467,
        elektronegativität: 1.61,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Silicium",
        kurzsymbol: "Si",
        unterkategorie: "-/-",
        oberkategorie: "Halbmetall",
        aussehen: "dunkelgrau, bläulicher Farbton",
        aggregatszustand: "fest",
        struktur: "Diamantstruktur",
        wikipedia: "https://de.wikipedia.org/wiki/Silicium",
        flammenfarbe: "-/-",
        zweitname: "Silizium",
        protonen: 14,
        neutronen: 14,
        lost: 4,
        hauptgruppe: 14,
        periode: 3,
        haerte: 6.5,
        volumen: 0.00001206,
        prozentsatzAnDerErdhuelle: 25.8,
        atommasse: 28.0855,
        ionisierungsenergie: 8.1517,
        dichte: 2.33,
        schmelzpunkt: 1410,
        siedepunkt: 2355,
        elektronegativität: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Phosphor",
        kurzsymbol: "P",
        unterkategorie: "-/-",
        oberkategorie: "Nichtmetall",
        aussehen: "weiß-beige, dunkelrot, schwarz, (Durch 3 vers. Modifikationen)",
        aggregatszustand: "fest",
        struktur: "orthorhombisch",
        wikipedia: "https://de.wikipedia.org/wiki/Phosphor",
        flammenfarbe: "-/-",
        zweitname: "Phosfor",
        protonen: 15,
        neutronen: 16,
        lost: 5,
        hauptgruppe: 15,
        periode: 3,
        haerte: 1.5,
        volumen: 0.00001702,
        prozentsatzAnDerErdhuelle: 0.09,
        atommasse: 30.973762,
        ionisierungsenergie: 10.4867,
        dichte: 1.82,
        schmelzpunkt: 44.1,
        siedepunkt: 280,
        elektronegativität: 2.19,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Schwefel",
        kurzsymbol: "S",
        unterkategorie: "-/-",
        oberkategorie: "Nichtmetall",
        aussehen: "gelb",
        aggregatszustand: "fest",
        struktur: "orthorhombisch",
        wikipedia: "https://de.wikipedia.org/wiki/Schwefel",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 16,
        neutronen: 16,
        lost: 6,
        hauptgruppe: 16,
        periode: 3,
        haerte: 2,
        volumen: 0.00001553,
        prozentsatzAnDerErdhuelle: 0.048,
        atommasse: 32.065,
        ionisierungsenergie: 10.36,
        dichte: 2.06,
        schmelzpunkt: 112.8,
        siedepunkt: 444.67,
        elektronegativität: 2.58,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Chlor",
        kurzsymbol: "Cl",
        unterkategorie: "Halogen",
        oberkategorie: "Nichtmetall",
        aussehen: "gelblich-grün",
        aggregatszustand: "fest",
        struktur: "orthorhombisch",
        wikipedia: "https://de.wikipedia.org/wiki/Chlor",
        flammenfarbe: "-/-",
        zweitname: "Chlorum",
        protonen: 17,
        neutronen: 18,
        lost: 7,
        hauptgruppe: 17,
        periode: 3,
        haerte: 0,
        volumen: 0.00001739,
        prozentsatzAnDerErdhuelle: 0.19,
        atommasse: 35.453,
        ionisierungsenergie: 12.9676,
        dichte: 2.03,
        schmelzpunkt: -100.98,
        siedepunkt: -34.6,
        elektronegativität: 3.16,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Argon",
        kurzsymbol: "Ar",
        unterkategorie: "Edelgas",
        oberkategorie: "Nichtmetall",
        aussehen: "farbloses Gas",
        aggregatszustand: "gasförmig",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Argon",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 18,
        neutronen: 22,
        lost: 8,
        hauptgruppe: 18,
        periode: 3,
        haerte: 0,
        volumen: 0.00002256,
        prozentsatzAnDerErdhuelle: 0.0004,
        atommasse: 39.948,
        ionisierungsenergie: 15.7596,
        dichte: 1.656,
        schmelzpunkt: -189.2,
        siedepunkt: -185.7,
        elektronegativität: 0,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Kalium",
        kurzsymbol: "K",
        unterkategorie: "Alkalimetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Kalium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 19,
        neutronen: 20,
        lost: 1,
        hauptgruppe: 1,
        periode: 4,
        haerte: 0.4,
        volumen: 0.00004594,
        prozentsatzAnDerErdhuelle: 2.4,
        atommasse: 39.0983,
        ionisierungsenergie: 4.3407,
        dichte: 0.856,
        schmelzpunkt: 63.65,
        siedepunkt: 774,
        elektronegativität: 0.82,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Calcium",
        kurzsymbol: "Ca",
        unterkategorie: "Erdalkalimetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Calcium",
        flammenfarbe: "-/-",
        zweitname: "Kalkium",
        protonen: 20,
        neutronen: 20,
        lost: 2,
        hauptgruppe: 2,
        periode: 4,
        haerte: 1.75,
        volumen: 0.0000262,
        prozentsatzAnDerErdhuelle: 3.39,
        atommasse: 40.078,
        ionisierungsenergie: 6.1132,
        dichte: 1.55,
        schmelzpunkt: 839,
        siedepunkt: 1484,
        elektronegativität: 1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Scandium",
        kurzsymbol: "Sc",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Scandium",
        flammenfarbe: "-/-",
        zweitname: "Skandium",
        protonen: 21,
        neutronen: 24,
        lost: 2,
        hauptgruppe: 3,
        periode: 4,
        haerte: 2.5,
        volumen: 0.000015,
        prozentsatzAnDerErdhuelle: 0.0005,
        atommasse: 44.955912,
        ionisierungsenergie: 6.5615,
        dichte: 2.985,
        schmelzpunkt: 1541,
        siedepunkt: 2831,
        elektronegativität: 1.36,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Titan",
        kurzsymbol: "Ti",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig metallisch",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Titan_%28Element%29",
        flammenfarbe: "-/-",
        zweitname: "Titanium",
        protonen: 22,
        neutronen: 26,
        lost: 2,
        hauptgruppe: 4,
        periode: 4,
        haerte: 6,
        volumen: 0.00001064,
        prozentsatzAnDerErdhuelle: 0.41,
        atommasse: 47.867,
        ionisierungsenergie: 6.8281,
        dichte: 4.507,
        schmelzpunkt: 1660,
        siedepunkt: 3287,
        elektronegativität: 1.54,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Vanadium",
        kurzsymbol: "V",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "stahlgrau metallisch, bläulich schimmernd",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Vanadium",
        flammenfarbe: "-/-",
        zweitname: "Wanadium",
        protonen: 23,
        neutronen: 28,
        lost: 2,
        hauptgruppe: 5,
        periode: 4,
        haerte: 7,
        volumen: 0.00000832,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 50.9415,
        ionisierungsenergie: 6.7462,
        dichte: 6.11,
        schmelzpunkt: 1890,
        siedepunkt: 3380,
        elektronegativität: 1.63,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Chrom",
        kurzsymbol: "Cr",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig metallisch",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Chrom",
        flammenfarbe: "-/-",
        zweitname: "Chromium",
        protonen: 24,
        neutronen: 28,
        lost: 1,
        hauptgruppe: 6,
        periode: 4,
        haerte: 8.5,
        volumen: 0.00000723,
        prozentsatzAnDerErdhuelle: 0.02,
        atommasse: 51.9961,
        ionisierungsenergie: 6.7665,
        dichte: 7.14,
        schmelzpunkt: 1857,
        siedepunkt: 2672,
        elektronegativität: 1.66,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Mangan",
        kurzsymbol: "Mn",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig metallisch (Stahlweiß)",
        aggregatszustand: "fest",
        struktur: "4 Verschiedene Modifikationen",
        wikipedia: "https://de.wikipedia.org/wiki/Mangan",
        flammenfarbe: "-/-",
        zweitname: "Manganum",
        protonen: 25,
        neutronen: 30,
        lost: 2,
        hauptgruppe: 7,
        periode: 4,
        haerte: 6,
        volumen: 0.00000735,
        prozentsatzAnDerErdhuelle: 0.085,
        atommasse: 54.938045,
        ionisierungsenergie: 7.434,
        dichte: 7.43,
        schmelzpunkt: 1244,
        siedepunkt: 1962,
        elektronegativität: 1.55,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Eisen",
        kurzsymbol: "Fe",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "metallisch glänzend mit einem gräulichen Farbton",
        aggregatszustand: "fest",
        struktur: "4 Verschiedene Modifikationen",
        wikipedia: "https://de.wikipedia.org/wiki/Eisen",
        flammenfarbe: "-/-",
        zweitname: "Ferrum",
        protonen: 26,
        neutronen: 30,
        lost: 2,
        hauptgruppe: 8,
        periode: 4,
        haerte: 4,
        volumen: 0.00000709,
        prozentsatzAnDerErdhuelle: 4.7,
        atommasse: 55.845,
        ionisierungsenergie: 7.9024,
        dichte: 7.874,
        schmelzpunkt: 1535,
        siedepunkt: 2750,
        elektronegativität: 1.83,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Cobalt",
        kurzsymbol: "Co",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "metallisch mit einem bläulich-gräulichen Farbton",
        aggregatszustand: "fest",
        struktur: "2 Verschiedene Modifikationen",
        wikipedia: "https://de.wikipedia.org/wiki/Cobalt",
        flammenfarbe: "-/-",
        zweitname: "Kobalt",
        protonen: 27,
        neutronen: 32,
        lost: 2,
        hauptgruppe: 9,
        periode: 4,
        haerte: 5,
        volumen: 0.00000667,
        prozentsatzAnDerErdhuelle: 0.004,
        atommasse: 58.933195,
        ionisierungsenergie: 7.881,
        dichte: 8.9,
        schmelzpunkt: 1495,
        siedepunkt: 2870,
        elektronegativität: 1.88,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Nickel",
        kurzsymbol: "Ni",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "glänzend, metallisch, silbrig",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Nickel",
        flammenfarbe: "-/-",
        zweitname: "Niccolum",
        protonen: 28,
        neutronen: 31,
        lost: 2,
        hauptgruppe: 10,
        periode: 4,
        haerte: 4,
        volumen: 0.00000659,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 28.6934,
        ionisierungsenergie: 7.6398,
        dichte: 8.908,
        schmelzpunkt: 1453,
        siedepunkt: 2732,
        elektronegativität: 1.91,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Kupfer",
        kurzsymbol: "Cu",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "lachsrosa, metallisch",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Kupfer",
        flammenfarbe: "-/-",
        zweitname: "Cuprum",
        protonen: 29,
        neutronen: 35,
        lost: 1,
        hauptgruppe: 11,
        periode: 4,
        haerte: 3,
        volumen: 0.00000711,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 63.546,
        ionisierungsenergie: 7.7264,
        dichte: 8.92,
        schmelzpunkt: 1083,
        siedepunkt: 2567,
        elektronegativität: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Zink",
        kurzsymbol: "Zn",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "bläulich blassgrau",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Zink",
        flammenfarbe: "-/-",
        zweitname: "Zinkum",
        protonen: 30,
        neutronen: 35,
        lost: 2,
        hauptgruppe: 12,
        periode: 4,
        haerte: 2.5,
        volumen: 0.00000916,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 65.409,
        ionisierungsenergie: 9.3942,
        dichte: 7.14,
        schmelzpunkt: 419.6,
        siedepunkt: 907,
        elektronegativität: 1.65,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Gallium",
        kurzsymbol: "Ga",
        unterkategorie: "-/-",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Gallium",
        flammenfarbe: "-/-",
        zweitname: "Galium",
        protonen: 31,
        neutronen: 39,
        lost: 3,
        hauptgruppe: 13,
        periode: 4,
        haerte: 1.5,
        volumen: 0.0000118,
        prozentsatzAnDerErdhuelle: 0.003,
        atommasse: 69.723,
        ionisierungsenergie: 5.9993,
        dichte: 5.904,
        schmelzpunkt: 29.78,
        siedepunkt: 2403,
        elektronegativität: 1.81,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Germanium",
        kurzsymbol: "Ge",
        unterkategorie: "-/-",
        oberkategorie: "Halbmetall",
        aussehen: "gräulich weiß",
        aggregatszustand: "fest",
        struktur: "Diamantstruktur",
        wikipedia: "https://de.wikipedia.org/wiki/Germanium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 32,
        neutronen: 41,
        lost: 4,
        hauptgruppe: 14,
        periode: 4,
        haerte: 6,
        volumen: 0.00001363,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 72.631,
        ionisierungsenergie: 7.8994,
        dichte: 5.323,
        schmelzpunkt: 937.4,
        siedepunkt: 2830,
        elektronegativität: 2.01,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Arsen",
        kurzsymbol: "As",
        unterkategorie: "-/-",
        oberkategorie: "Halbmetall",
        aussehen: "metallisch grau, gelb oder schwarz",
        aggregatszustand: "fest",
        struktur: "trigonal (grau)",
        wikipedia: "https://de.wikipedia.org/wiki/Arsen",
        flammenfarbe: "-/-",
        zweitname: "Arsenicum",
        protonen: 33,
        neutronen: 42,
        lost: 5,
        hauptgruppe: 15,
        periode: 4,
        haerte: 3.5,
        volumen: 0.00001295,
        prozentsatzAnDerErdhuelle: 0.00055,
        atommasse: 74.9216,
        ionisierungsenergie: 9.7886,
        dichte: 5.72,
        schmelzpunkt: 616,
        siedepunkt: 616,
        elektronegativität: 2.18,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Selen",
        kurzsymbol: "Se",
        unterkategorie: "-/-",
        oberkategorie: "Halbmetall",
        aussehen: "grau, glänzend",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Selen",
        flammenfarbe: "-/-",
        zweitname: "Selenium",
        protonen: 34,
        neutronen: 45,
        lost: 6,
        hauptgruppe: 16,
        periode: 4,
        haerte: 2,
        volumen: 0.00001642,
        prozentsatzAnDerErdhuelle: 0.00008,
        atommasse: 78.971,
        ionisierungsenergie: 9.7524,
        dichte: 4.819,
        schmelzpunkt: 217,
        siedepunkt: 684.9,
        elektronegativität: 2.55,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Brom",
        kurzsymbol: "Br",
        unterkategorie: "Halogen",
        oberkategorie: "Nichtmetall",
        aussehen: "rotbraun, fest: metallisch glänzend",
        aggregatszustand: "flüssig",
        struktur: "orthorhombisch",
        wikipedia: "https://de.wikipedia.org/wiki/Brom",
        flammenfarbe: "-/-",
        zweitname: "Bromum",
        protonen: 35,
        neutronen: 45,
        lost: 7,
        hauptgruppe: 17,
        periode: 4,
        haerte: 0,
        volumen: 0.00001978,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 79.904,
        ionisierungsenergie: 11.8138,
        dichte: 4.05,
        schmelzpunkt: -7.2,
        siedepunkt: 58.78,
        elektronegativität: 2.96,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Krypton",
        kurzsymbol: "Kr",
        unterkategorie: "Edelgas",
        oberkategorie: "Nichtmetall",
        aussehen: "Farbloses Gas",
        aggregatszustand: "gasförmig",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Krypton",
        flammenfarbe: "-/-",
        zweitname: "Crypton",
        protonen: 36,
        neutronen: 48,
        lost: 8,
        hauptgruppe: 18,
        periode: 4,
        haerte: 0,
        volumen: 0.00002799,
        prozentsatzAnDerErdhuelle: 0.00000002,
        atommasse: 83.798,
        ionisierungsenergie: 13.9996,
        dichte: 2.823,
        schmelzpunkt: -156.6,
        siedepunkt: -152.3,
        elektronegativität: 3,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Rubidium",
        kurzsymbol: "Rb",
        unterkategorie: "Alkalimetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Rubidium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 37,
        neutronen: 48,
        lost: 1,
        hauptgruppe: 1,
        periode: 5,
        haerte: 0.3,
        volumen: 0.00005576,
        prozentsatzAnDerErdhuelle: 0.03,
        atommasse: 84.4678,
        ionisierungsenergie: 4.1771,
        dichte: 1.532,
        schmelzpunkt: 38.89,
        siedepunkt: 688,
        elektronegativität: 0.82,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Strontium",
        kurzsymbol: "Sr",
        unterkategorie: "Erdalkalimetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß metallisch",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Strontium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 38,
        neutronen: 50,
        lost: 2,
        hauptgruppe: 2,
        periode: 5,
        haerte: 1.5,
        volumen: 0.00003394,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 87.621,
        ionisierungsenergie: 5.6949,
        dichte: 2.63,
        schmelzpunkt: 769,
        siedepunkt: 1384,
        elektronegativität: 0.95,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Yttrium",
        kurzsymbol: "Y",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Yttrium",
        flammenfarbe: "-/-",
        zweitname: "Ittrium",
        protonen: 39,
        neutronen: 50,
        lost: 2,
        hauptgruppe: 3,
        periode: 5,
        haerte: 0,
        volumen: 0.00001988,
        prozentsatzAnDerErdhuelle: 0.003,
        atommasse: 88.90585,
        ionisierungsenergie: 6.2173,
        dichte: 4.469,
        schmelzpunkt: 1522,
        siedepunkt: 3338,
        elektronegativität: 1.22,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Zirconium",
        kurzsymbol: "Zr",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal, kubisch > 1140 K",
        wikipedia: "https://de.wikipedia.org/wiki/Zirkonium",
        flammenfarbe: "-/-",
        zweitname: "Zirkonium",
        protonen: 40,
        neutronen: 51,
        lost: 2,
        hauptgruppe: 4,
        periode: 5,
        haerte: 5,
        volumen: 0.00001402,
        prozentsatzAnDerErdhuelle: 0.02,
        atommasse: 91.2242,
        ionisierungsenergie: 6.6339,
        dichte: 6.506,
        schmelzpunkt: 1852,
        siedepunkt: 4377,
        elektronegativität: 1.33,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Niob",
        kurzsymbol: "Nb",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "grau metallisch glänzend",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Niob",
        flammenfarbe: "-/-",
        zweitname: "Niobium",
        protonen: 41,
        neutronen: 52,
        lost: 1,
        hauptgruppe: 5,
        periode: 5,
        haerte: 6,
        volumen: 0.00001083,
        prozentsatzAnDerErdhuelle: 0.002,
        atommasse: 92.90638,
        ionisierungsenergie: 6.7589,
        dichte: 8.57,
        schmelzpunkt: 2468,
        siedepunkt: 4742,
        elektronegativität: 1.6,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Molybdän",
        kurzsymbol: "Mo",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "grau metallisch",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Molybd%C3%A4n",
        flammenfarbe: "-/-",
        zweitname: "Molybdaenum",
        protonen: 42,
        neutronen: 54,
        lost: 1,
        hauptgruppe: 6,
        periode: 5,
        haerte: 5.5,
        volumen: 0.00000938,
        prozentsatzAnDerErdhuelle: 0.001,
        atommasse: 95.951,
        ionisierungsenergie: 7.0924,
        dichte: 10.28,
        schmelzpunkt: 2617,
        siedepunkt: 4612,
        elektronegativität: 2.16,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Technetium",
        kurzsymbol: "Tc",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig grau metallisch",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Technetium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 43,
        neutronen: 56,
        lost: 2,
        hauptgruppe: 7,
        periode: 5,
        haerte: 0,
        volumen: 0.00000863,
        prozentsatzAnDerErdhuelle: 0.0000000000000005,
        atommasse: 98.9063,
        ionisierungsenergie: 7.28,
        dichte: 11.5,
        schmelzpunkt: 2172,
        siedepunkt: 4877,
        elektronegativität: 2.1,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Ruthenium",
        kurzsymbol: "Ru",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß metallisch",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Ruthenium",
        flammenfarbe: "-/-",
        zweitname: "Rutenium",
        protonen: 44,
        neutronen: 57,
        lost: 1,
        hauptgruppe: 8,
        periode: 5,
        haerte: 6.5,
        volumen: 0.00000817,
        prozentsatzAnDerErdhuelle: 0.000002,
        atommasse: 101.072,
        ionisierungsenergie: 7.30605,
        dichte: 12.37,
        schmelzpunkt: 2310,
        siedepunkt: 3900,
        elektronegativität: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Rhodium",
        kurzsymbol: "Rh",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß metallisch",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Rhodium",
        flammenfarbe: "-/-",
        zweitname: "Rodium",
        protonen: 45,
        neutronen: 58,
        lost: 1,
        hauptgruppe: 9,
        periode: 5,
        haerte: 6,
        volumen: 0.00000828,
        prozentsatzAnDerErdhuelle: 0.0000001,
        atommasse: 102.9055,
        ionisierungsenergie: 7.4589,
        dichte: 12.38,
        schmelzpunkt: 1966,
        siedepunkt: 3727,
        elektronegativität: 2.28,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Palladium",
        kurzsymbol: "Pd",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig, weiß, metallisch",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Palladium",
        flammenfarbe: "-/-",
        zweitname: "Paladium",
        protonen: 46,
        neutronen: 60,
        lost: 0,
        hauptgruppe: 10,
        periode: 5,
        haerte: 4.75,
        volumen: 0.00000856,
        prozentsatzAnDerErdhuelle: 0.000001,
        atommasse: 106.421,
        ionisierungsenergie: 8.3369,
        dichte: 11.99,
        schmelzpunkt: 1552,
        siedepunkt: 3140,
        elektronegativität: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Silber",
        kurzsymbol: "Ag",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "weißglänzend, metallisch",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Silber",
        flammenfarbe: "-/-",
        zweitname: "Argentum",
        protonen: 47,
        neutronen: 61,
        lost: 1,
        hauptgruppe: 11,
        periode: 5,
        haerte: 2.7,
        volumen: 0.00001027,
        prozentsatzAnDerErdhuelle: 0.00001,
        atommasse: 107.8682,
        ionisierungsenergie: 7.5762,
        dichte: 10.49,
        schmelzpunkt: 961.9,
        siedepunkt: 2212,
        elektronegativität: 1.93,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Cadmium",
        kurzsymbol: "Cd",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig grau metallisch",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Cadmium",
        flammenfarbe: "-/-",
        zweitname: "Kadmium",
        protonen: 48,
        neutronen: 64,
        lost: 2,
        hauptgruppe: 12,
        periode: 5,
        haerte: 2,
        volumen: 0.000013,
        prozentsatzAnDerErdhuelle: 0.00003,
        atommasse: 112.411,
        ionisierungsenergie: 8.9938,
        dichte: 8.65,
        schmelzpunkt: 320.9,
        siedepunkt: 765,
        elektronegativität: 1.69,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Indium",
        kurzsymbol: "In",
        unterkategorie: "-/-",
        oberkategorie: "Metall",
        aussehen: "silbrig glänzend grau",
        aggregatszustand: "fest",
        struktur: "tetragonal",
        wikipedia: "https://de.wikipedia.org/wiki/Indium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 49,
        neutronen: 66,
        lost: 3,
        hauptgruppe: 13,
        periode: 5,
        haerte: 1.2,
        volumen: 0.00001576,
        prozentsatzAnDerErdhuelle: 0.00001,
        atommasse: 114.818,
        ionisierungsenergie: 5.7864,
        dichte: 7.31,
        schmelzpunkt: 156.2,
        siedepunkt: 2080,
        elektronegativität: 1.78,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Zinn",
        kurzsymbol: "Sn",
        unterkategorie: "-/-",
        oberkategorie: "Metall",
        aussehen: "silbrig glänzend grau",
        aggregatszustand: "fest",
        struktur: "alpha-Zinn -> kubisch(Diamantstruktur), beta-Zinn -> tetragonal",
        wikipedia: "https://de.wikipedia.org/wiki/Zinn",
        flammenfarbe: "-/-",
        zweitname: "Stannum",
        protonen: 50,
        neutronen: 69,
        lost: 4,
        hauptgruppe: 14,
        periode: 5,
        haerte: 1.5,
        volumen: 0.00001629,
        prozentsatzAnDerErdhuelle: 0.003,
        atommasse: 118.7107,
        ionisierungsenergie: 7.3439,
        dichte: 5.75,
        schmelzpunkt: 232,
        siedepunkt: 2270,
        elektronegativität: 1.96,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Antimon",
        kurzsymbol: "Sb",
        unterkategorie: "-/-",
        oberkategorie: "Halbmetall",
        aussehen: "silbrig glänzend grau",
        aggregatszustand: "fest",
        struktur: "trigonal",
        wikipedia: "https://de.wikipedia.org/wiki/Antimon",
        flammenfarbe: "-/-",
        zweitname: "Stibium",
        protonen: 51,
        neutronen: 71,
        lost: 5,
        hauptgruppe: 15,
        periode: 5,
        haerte: 3,
        volumen: 0.00001819,
        prozentsatzAnDerErdhuelle: 0.000065,
        atommasse: 121.7601,
        ionisierungsenergie: 8.6084,
        dichte: 6.697,
        schmelzpunkt: 630.7,
        siedepunkt: 1750,
        elektronegativität: 2.05,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Tellur",
        kurzsymbol: "Te",
        unterkategorie: "-/-",
        oberkategorie: "Halbmetall",
        aussehen: "silberweiß, metallisch glänzend",
        aggregatszustand: "fest",
        struktur: "trigonal",
        wikipedia: "https://de.wikipedia.org/wiki/Tellur",
        flammenfarbe: "-/-",
        zweitname: "Tellurium",
        protonen: 52,
        neutronen: 76,
        lost: 6,
        hauptgruppe: 16,
        periode: 5,
        haerte: 2.25,
        volumen: 0.00002046,
        prozentsatzAnDerErdhuelle: 0.000001,
        atommasse: 127.603,
        ionisierungsenergie: 9.0096,
        dichte: 6.24,
        schmelzpunkt: 449.5,
        siedepunkt: 990,
        elektronegativität: 2.1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Iod",
        kurzsymbol: "I",
        unterkategorie: "Halogen",
        oberkategorie: "Nichtmetall",
        aussehen: "Gas: dunkel-violett, fest: grau glänzend",
        aggregatszustand: "fest",
        struktur: "orthorhombisch",
        wikipedia: "https://de.wikipedia.org/wiki/Iod",
        flammenfarbe: "-/-",
        zweitname: "Iodium",
        protonen: 53,
        neutronen: 74,
        lost: 7,
        hauptgruppe: 17,
        periode: 5,
        haerte: 0,
        volumen: 0.00002572,
        prozentsatzAnDerErdhuelle: 0.000006,
        atommasse: 126.90447,
        ionisierungsenergie: 10.4513,
        dichte: 4.93,
        schmelzpunkt: 113.5,
        siedepunkt: 184.4,
        elektronegativität: 2.66,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Xenon",
        kurzsymbol: "Xe",
        unterkategorie: "Edelgas",
        oberkategorie: "Nichtmetall",
        aussehen: "Farbloses Gas",
        aggregatszustand: "gasförmig",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Xenon",
        flammenfarbe: "-/-",
        zweitname: "Xenon",
        protonen: 54,
        neutronen: 77,
        lost: 8,
        hauptgruppe: 18,
        periode: 5,
        haerte: 0,
        volumen: 0.00003592,
        prozentsatzAnDerErdhuelle: 0.000000002,
        atommasse: 131.293,
        ionisierungsenergie: 12.1298,
        dichte: 3.54,
        schmelzpunkt: -111.9,
        siedepunkt: -107.1,
        elektronegativität: 2.6,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Caesium",
        kurzsymbol: "Cs",
        unterkategorie: "Alkalimetall",
        oberkategorie: "Metall",
        aussehen: "silberweiß glänzend, bei Sauerstoffspuren goldgelb",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Caesium",
        flammenfarbe: "-/-",
        zweitname: "Cäsium",
        protonen: 55,
        neutronen: 78,
        lost: 1,
        hauptgruppe: 1,
        periode: 6,
        haerte: 0.2,
        volumen: 0.00007094,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 132.9054519,
        ionisierungsenergie: 3.8939,
        dichte: 1.93,
        schmelzpunkt: 28.4,
        siedepunkt: 678.4,
        elektronegativität: 0.79,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Barium",
        kurzsymbol: "Ba",
        unterkategorie: "Erdalkalimetall",
        oberkategorie: "Metall",
        aussehen: "weiß-grau metallisch",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Barium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 56,
        neutronen: 81,
        lost: 2,
        hauptgruppe: 2,
        periode: 6,
        haerte: 1.25,
        volumen: 0.00003816,
        prozentsatzAnDerErdhuelle: 0.03,
        atommasse: 137.327,
        ionisierungsenergie: 5.2117,
        dichte: 3.62,
        schmelzpunkt: 725,
        siedepunkt: 1640,
        elektronegativität: 0.89,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Lanthan",
        kurzsymbol: "La",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Lanthan",
        flammenfarbe: "-/-",
        zweitname: "Lanthanum",
        protonen: 57,
        neutronen: 82,
        lost: 2,
        hauptgruppe: 3,
        periode: 6,
        haerte: 3,
        volumen: 0.00002239,
        prozentsatzAnDerErdhuelle: 0.002,
        atommasse: 138.90547,
        ionisierungsenergie: 5.5769,
        dichte: 6.17,
        schmelzpunkt: 921,
        siedepunkt: 3457,
        elektronegativität: 1.1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Cer",
        kurzsymbol: "Ce",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Cer",
        flammenfarbe: "-/-",
        zweitname: "Cerium",
        protonen: 58,
        neutronen: 82,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 2.5,
        volumen: 0.00002069,
        prozentsatzAnDerErdhuelle: 0.004,
        atommasse: 140.116,
        ionisierungsenergie: 5.5387,
        dichte: 8.16,
        schmelzpunkt: 799,
        siedepunkt: 3426,
        elektronegativität: 1.12,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Praesodym",
        kurzsymbol: "Pr",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß, gelblicher Farbton",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Praseodym",
        flammenfarbe: "-/-",
        zweitname: "Praseodymium",
        protonen: 59,
        neutronen: 82,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.0000208,
        prozentsatzAnDerErdhuelle: 0.0005,
        atommasse: 140.90765,
        ionisierungsenergie: 5.473,
        dichte: 6.475,
        schmelzpunkt: 931,
        siedepunkt: 3512,
        elektronegativität: 1.13,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Neodym",
        kurzsymbol: "Nd",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "metallisch",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Neodym",
        flammenfarbe: "-/-",
        zweitname: "Neodymium",
        protonen: 60,
        neutronen: 84,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.00002059,
        prozentsatzAnDerErdhuelle: 0.002,
        atommasse: 144.242,
        ionisierungsenergie: 5.525,
        dichte: 7.003,
        schmelzpunkt: 1021,
        siedepunkt: 3068,
        elektronegativität: 1.14,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Promethium",
        kurzsymbol: "Pm",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "metallisch",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Promethium",
        flammenfarbe: "-/-",
        zweitname: "Prometium",
        protonen: 61,
        neutronen: 86,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.0000201,
        prozentsatzAnDerErdhuelle: 0.0000000000000000001,
        atommasse: 144.912744,
        ionisierungsenergie: 5.582,
        dichte: 7.2,
        schmelzpunkt: 1168,
        siedepunkt: 2460,
        elektronegativität: 1.07,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Samarium",
        kurzsymbol: "Sm",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig",
        aggregatszustand: "fest",
        struktur: "trigonal",
        wikipedia: "https://de.wikipedia.org/wiki/Samarium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 62,
        neutronen: 88,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.00001998,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 150.362,
        ionisierungsenergie: 5.6437,
        dichte: 7.536,
        schmelzpunkt: 1077,
        siedepunkt: 1791,
        elektronegativität: 1.17,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Europium",
        kurzsymbol: "Eu",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Europium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 63,
        neutronen: 89,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.002897,
        prozentsatzAnDerErdhuelle: 0.00001,
        atommasse: 151.964,
        ionisierungsenergie: 5.6704,
        dichte: 5.245,
        schmelzpunkt: 822,
        siedepunkt: 1597,
        elektronegativität: 1.01,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Gadolinium",
        kurzsymbol: "Gd",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Gadolinium",
        flammenfarbe: "-/-",
        zweitname: "Gatolinium",
        protonen: 64,
        neutronen: 93,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 1.5,
        volumen: 0.0000199,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 157.253,
        ionisierungsenergie: 6.1498,
        dichte: 7.886,
        schmelzpunkt: 1313,
        siedepunkt: 3266,
        elektronegativität: 1.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Terbium",
        kurzsymbol: "Tb",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Terbium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 65,
        neutronen: 94,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.0000193,
        prozentsatzAnDerErdhuelle: 0.00009,
        atommasse: 158.92535,
        ionisierungsenergie: 5.8638,
        dichte: 8.253,
        schmelzpunkt: 1356,
        siedepunkt: 3123,
        elektronegativität: 1.1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Dysprosium",
        kurzsymbol: "Dy",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Dysprosium",
        flammenfarbe: "-/-",
        zweitname: "Disprosium",
        protonen: 66,
        neutronen: 97,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.00001901,
        prozentsatzAnDerErdhuelle: 0.00042,
        atommasse: 162.5001,
        ionisierungsenergie: 5.9389,
        dichte: 8.559,
        schmelzpunkt: 1412,
        siedepunkt: 2562,
        elektronegativität: 1.22,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Holmium",
        kurzsymbol: "Ho",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Holmium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 67,
        neutronen: 98,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.00001874,
        prozentsatzAnDerErdhuelle: 0.0001,
        atommasse: 164.93032,
        ionisierungsenergie: 6.0215,
        dichte: 8.78,
        schmelzpunkt: 1474,
        siedepunkt: 2695,
        elektronegativität: 1.23,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Erbium",
        kurzsymbol: "Er",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Erbium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 68,
        neutronen: 99,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.00001846,
        prozentsatzAnDerErdhuelle: 0.0002,
        atommasse: 167.2593,
        ionisierungsenergie: 6.1077,
        dichte: 9.045,
        schmelzpunkt: 1497,
        siedepunkt: 2900,
        elektronegativität: 1.24,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Thulium",
        kurzsymbol: "Tm",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig grau",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Thulium",
        flammenfarbe: "-/-",
        zweitname: "Tulium",
        protonen: 69,
        neutronen: 100,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 1,
        volumen: 0.0000191,
        prozentsatzAnDerErdhuelle: 0.00002,
        atommasse: 168.93421,
        ionisierungsenergie: 6.1843,
        dichte: 9.318,
        schmelzpunkt: 1545,
        siedepunkt: 1974,
        elektronegativität: 1.25,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Ytterbium",
        kurzsymbol: "Yb",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Ytterbium",
        flammenfarbe: "-/-",
        zweitname: "Itterbium",
        protonen: 70,
        neutronen: 103,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.00002484,
        prozentsatzAnDerErdhuelle: 0.0003,
        atommasse: 173.0451,
        ionisierungsenergie: 6.2542,
        dichte: 6.973,
        schmelzpunkt: 819,
        siedepunkt: 1194,
        elektronegativität: 1.06,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Lutetium",
        kurzsymbol: "Lu",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Lutetium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 71,
        neutronen: 104,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 0,
        volumen: 0.00001778,
        prozentsatzAnDerErdhuelle: 0.00007,
        atommasse: 174.967,
        ionisierungsenergie: 5.4259,
        dichte: 9.84,
        schmelzpunkt: 1663,
        siedepunkt: 3395,
        elektronegativität: 1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Hafnium",
        kurzsymbol: "Hf",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "stahlgrau",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Hafnium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 72,
        neutronen: 106,
        lost: 2,
        hauptgruppe: 4,
        periode: 6,
        haerte: 5.5,
        volumen: 0.00001344,
        prozentsatzAnDerErdhuelle: 0.0004,
        atommasse: 178.492,
        ionisierungsenergie: 6.8251,
        dichte: 13.28,
        schmelzpunkt: 2227,
        siedepunkt: 4602,
        elektronegativität: 1.3,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Tantal",
        kurzsymbol: "Ta",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "grau",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Tantal",
        flammenfarbe: "-/-",
        zweitname: "Tantalum",
        protonen: 73,
        neutronen: 108,
        lost: 2,
        hauptgruppe: 5,
        periode: 6,
        haerte: 6.5,
        volumen: 0.00001085,
        prozentsatzAnDerErdhuelle: 0.0008,
        atommasse: 180.94788,
        ionisierungsenergie: 7.5496,
        dichte: 16.65,
        schmelzpunkt: 2996,
        siedepunkt: 5425,
        elektronegativität: 1.5,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Wolfram",
        kurzsymbol: "W",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "gräulich weiß, glänzend",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Wolfram",
        flammenfarbe: "-/-",
        zweitname: "Wolframium",
        protonen: 74,
        neutronen: 110,
        lost: 2,
        hauptgruppe: 6,
        periode: 6,
        haerte: 7.5,
        volumen: 0.00000947,
        prozentsatzAnDerErdhuelle: 0.006,
        atommasse: 183.841,
        ionisierungsenergie: 7.864,
        dichte: 19.3,
        schmelzpunkt: 3410,
        siedepunkt: 5660,
        elektronegativität: 1.7,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Rhenium",
        kurzsymbol: "Re",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "gräulich weiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Rhenium",
        flammenfarbe: "-/-",
        zweitname: "Renium",
        protonen: 75,
        neutronen: 111,
        lost: 2,
        hauptgruppe: 7,
        periode: 6,
        haerte: 7,
        volumen: 0.00000886,
        prozentsatzAnDerErdhuelle: 0.0000001,
        atommasse: 186.2071,
        ionisierungsenergie: 7.8335,
        dichte: 21.02,
        schmelzpunkt: 3180,
        siedepunkt: 5627,
        elektronegativität: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Osmium",
        kurzsymbol: "Os",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "bläulich grau",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Osmium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 76,
        neutronen: 114,
        lost: 2,
        hauptgruppe: 8,
        periode: 6,
        haerte: 7,
        volumen: 0.00000842,
        prozentsatzAnDerErdhuelle: 0.000001,
        atommasse: 190.233,
        ionisierungsenergie: 8.4382,
        dichte: 22.61,
        schmelzpunkt: 3045,
        siedepunkt: 5027,
        elektronegativität: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Iridium",
        kurzsymbol: "Ir",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Iridium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 77,
        neutronen: 115,
        lost: 2,
        hauptgruppe: 9,
        periode: 6,
        haerte: 6.5,
        volumen: 0.00000852,
        prozentsatzAnDerErdhuelle: 0.0000001,
        atommasse: 192.2173,
        ionisierungsenergie: 8.967,
        dichte: 22.67,
        schmelzpunkt: 2410,
        siedepunkt: 4130,
        elektronegativität: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Platin",
        kurzsymbol: "Pt",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "grau-weiß",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Platin",
        flammenfarbe: "-/-",
        zweitname: "Platinum",
        protonen: 78,
        neutronen: 117,
        lost: 1,
        hauptgruppe: 10,
        periode: 6,
        haerte: 3.5,
        volumen: 0.00000909,
        prozentsatzAnDerErdhuelle: 0.0000005,
        atommasse: 195.078,
        ionisierungsenergie: 8.9588,
        dichte: 21.45,
        schmelzpunkt: 1772,
        siedepunkt: 3827,
        elektronegativität: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Gold",
        kurzsymbol: "Au",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "gold, ach echt? Google es doch, wenn du mir nicht glaubst ,D",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Gold",
        flammenfarbe: "-/-",
        zweitname: "Aurum",
        protonen: 79,
        neutronen: 118,
        lost: 1,
        hauptgruppe: 11,
        periode: 6,
        haerte: 2.75,
        volumen: 0.00001021,
        prozentsatzAnDerErdhuelle: 0.0000005,
        atommasse: 196.966569,
        ionisierungsenergie: 9.2255,
        dichte: 19.32,
        schmelzpunkt: 1064,
        siedepunkt: 2807,
        elektronegativität: 2.4,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Quecksilber",
        kurzsymbol: "Hg",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "flüssig",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Quecksilber",
        flammenfarbe: "-/-",
        zweitname: "Hydrargyrum",
        protonen: 80,
        neutronen: 121,
        lost: 2,
        hauptgruppe: 12,
        periode: 6,
        haerte: 0,
        volumen: 0.00001409,
        prozentsatzAnDerErdhuelle: 0.00004,
        atommasse: 200.5923,
        ionisierungsenergie: 10.4375,
        dichte: 14.26,
        schmelzpunkt: -38.84,
        siedepunkt: 356.6,
        elektronegativität: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Thallium",
        kurzsymbol: "Tl",
        unterkategorie: "-/-",
        oberkategorie: "Metall",
        aussehen: "",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Thallium",
        flammenfarbe: "-/-",
        zweitname: "Tallium",
        protonen: 81,
        neutronen: 123,
        lost: 3,
        hauptgruppe: 13,
        periode: 6,
        haerte: 1.2,
        volumen: 0.00001722,
        prozentsatzAnDerErdhuelle: 0.00003,
        atommasse: 204.383,
        ionisierungsenergie: 6.1082,
        dichte: 11.85,
        schmelzpunkt: 303.5,
        siedepunkt: 1457,
        elektronegativität: 1.8,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Blei",
        kurzsymbol: "Pb",
        unterkategorie: "-/-",
        oberkategorie: "Metall",
        aussehen: "bläulich weiß",
        aggregatszustand: "fest",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Blei",
        flammenfarbe: "-/-",
        zweitname: "Plumbum",
        protonen: 82,
        neutronen: 125,
        lost: 4,
        hauptgruppe: 14,
        periode: 6,
        haerte: 1.5,
        volumen: 0.00001826,
        prozentsatzAnDerErdhuelle: 0.002,
        atommasse: 207.21,
        ionisierungsenergie: 7.4167,
        dichte: 11.342,
        schmelzpunkt: 327.5,
        siedepunkt: 1740,
        elektronegativität: 1.8,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Bismut",
        kurzsymbol: "Bi",
        unterkategorie: "-/-",
        oberkategorie: "Metall",
        aussehen: "glänzend silberweiß",
        aggregatszustand: "fest",
        struktur: "trigonal",
        wikipedia: "https://de.wikipedia.org/wiki/Bismut",
        flammenfarbe: "-/-",
        zweitname: "Bismuthum",
        protonen: 83,
        neutronen: 126,
        lost: 5,
        hauptgruppe: 15,
        periode: 6,
        haerte: 2.25,
        volumen: 0.00002131,
        prozentsatzAnDerErdhuelle: 0.00002,
        atommasse: 208.9804,
        ionisierungsenergie: 7.2855,
        dichte: 9.78,
        schmelzpunkt: 271.3,
        siedepunkt: 1560,
        elektronegativität: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Polonium",
        kurzsymbol: "Po",
        unterkategorie: "-/-",
        oberkategorie: "Metall",
        aussehen: "silbrig",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Polonium",
        flammenfarbe: "-/-",
        zweitname: "Polonium",
        protonen: 84,
        neutronen: 126,
        lost: 6,
        hauptgruppe: 16,
        periode: 6,
        haerte: 0,
        volumen: 0.00002297,
        prozentsatzAnDerErdhuelle: 0.00000000000002,
        atommasse: 208.982416,
        ionisierungsenergie: 8.414,
        dichte: 9.196,
        schmelzpunkt: 254,
        siedepunkt: 962,
        elektronegativität: 2,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Astat",
        kurzsymbol: "At",
        unterkategorie: "Halogen",
        oberkategorie: "Nichtmetall",
        aussehen: "metallisch",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Astat",
        flammenfarbe: "-/-",
        zweitname: "Astatium",
        protonen: 85,
        neutronen: 125,
        lost: 7,
        hauptgruppe: 17,
        periode: 6,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0.000000000000000000000003,
        atommasse: 209.987131,
        ionisierungsenergie: 7.5,
        dichte: 0,
        schmelzpunkt: 302,
        siedepunkt: 337,
        elektronegativität: 2.2,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Radon",
        kurzsymbol: "Rn",
        unterkategorie: "Edelgas",
        oberkategorie: "Nichtmetall",
        aussehen: "farblos",
        aggregatszustand: "gasförmig",
        struktur: "kubisch flächenzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Radon",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 86,
        neutronen: 136,
        lost: 8,
        hauptgruppe: 18,
        periode: 6,
        haerte: 0,
        volumen: 0.0000505,
        prozentsatzAnDerErdhuelle: 0.0000000000000006,
        atommasse: 222.0175705,
        ionisierungsenergie: 10.7485,
        dichte: 5.06,
        schmelzpunkt: -71,
        siedepunkt: -61.8,
        elektronegativität: 0,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Francium",
        kurzsymbol: "Fr",
        unterkategorie: "Alkalimetall",
        oberkategorie: "Metall",
        aussehen: "unbekannt",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Francium",
        flammenfarbe: "-/-",
        zweitname: "Frankium",
        protonen: 87,
        neutronen: 136,
        lost: 1,
        hauptgruppe: 1,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0.000000000000000000001,
        atommasse: 223.0197307,
        ionisierungsenergie: 4.0727,
        dichte: 2.5,
        schmelzpunkt: 27,
        siedepunkt: 677,
        elektronegativität: 0.7,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Radium",
        kurzsymbol: "Ra",
        unterkategorie: "Erdalkalimetall",
        oberkategorie: "Metall",
        aussehen: "silbrig-weiß-metallisch",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Radium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 88,
        neutronen: 138,
        lost: 2,
        hauptgruppe: 2,
        periode: 7,
        haerte: 0,
        volumen: 0.00004109,
        prozentsatzAnDerErdhuelle: 0.0000000001,
        atommasse: 226.0254026,
        ionisierungsenergie: 5.2784,
        dichte: 5.5,
        schmelzpunkt: 700,
        siedepunkt: 1140,
        elektronegativität: 0.9,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Actinium",
        kurzsymbol: "Ac",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "silbrig",
        aggregatszustand: "fest",
        struktur: "kubisch raumzentriert",
        wikipedia: "https://de.wikipedia.org/wiki/Actinium",
        flammenfarbe: "-/-",
        zweitname: "Aktinium",
        protonen: 89,
        neutronen: 138,
        lost: 2,
        hauptgruppe: 3,
        periode: 7,
        haerte: 0,
        volumen: 0.00002255,
        prozentsatzAnDerErdhuelle: 0.0000064,
        atommasse: 227.027747,
        ionisierungsenergie: 5.17,
        dichte: 10.07,
        schmelzpunkt: 1050,
        siedepunkt: 3200,
        elektronegativität: 1.1,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Thorium",
        kurzsymbol: "Th",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weiß",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Thorium",
        flammenfarbe: "-/-",
        zweitname: "Torium",
        protonen: 90,
        neutronen: 142,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 3,
        volumen: 0.0000198,
        prozentsatzAnDerErdhuelle: 0.001,
        atommasse: 232.03806,
        ionisierungsenergie: 6.3067,
        dichte: 11.724,
        schmelzpunkt: 1750,
        siedepunkt: 4790,
        elektronegativität: 1.3,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Protactinium",
        kurzsymbol: "Pa",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "hell, silbrig, metallisch glänzend",
        aggregatszustand: "fest",
        struktur: "tetragonal",
        wikipedia: "https://de.wikipedia.org/wiki/Protactinium",
        flammenfarbe: "-/-",
        zweitname: "Protaktinium",
        protonen: 91,
        neutronen: 140,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0.00001518,
        prozentsatzAnDerErdhuelle: 0.00000000009,
        atommasse: 231.03588,
        ionisierungsenergie: 5.89,
        dichte: 15.37,
        schmelzpunkt: 1600,
        siedepunkt: 4027,
        elektronegativität: 1.5,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Uran",
        kurzsymbol: "U",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "silberweiß",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Uran",
        flammenfarbe: "-/-",
        zweitname: "Uranium",
        protonen: 92,
        neutronen: 146,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 2.75,
        volumen: 0.00001249,
        prozentsatzAnDerErdhuelle: 0.0003,
        atommasse: 238.02891,
        ionisierungsenergie: 6.1941,
        dichte: 19.16,
        schmelzpunkt: 1132,
        siedepunkt: 3818,
        elektronegativität: 1.7,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Neptunium",
        kurzsymbol: "Np",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "silbrig",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Neptunium",
        flammenfarbe: "-/-",
        zweitname: "Nebtunium",
        protonen: 93,
        neutronen: 144,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0.00001159,
        prozentsatzAnDerErdhuelle: 0.00000000000000004,
        atommasse: 237.0481673,
        ionisierungsenergie: 6.2657,
        dichte: 20.45,
        schmelzpunkt: 640,
        siedepunkt: 3902,
        elektronegativität: 1.3,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Plutonium",
        kurzsymbol: "Pu",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "silbriges Metall",
        aggregatszustand: "fest",
        struktur: "monoklin",
        wikipedia: "https://de.wikipedia.org/wiki/Plutonium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 94,
        neutronen: 150,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0.00001229,
        prozentsatzAnDerErdhuelle: 0.0000000000000000002,
        atommasse: 244.064198,
        ionisierungsenergie: 6.026,
        dichte: 19.816,
        schmelzpunkt: 641,
        siedepunkt: 3332,
        elektronegativität: 1.3,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Americium",
        kurzsymbol: "Am",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weißes Metall",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Americium",
        flammenfarbe: "-/-",
        zweitname: "Amerikium",
        protonen: 95,
        neutronen: 148,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0.00001778,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 243.0613727,
        ionisierungsenergie: 5.9738,
        dichte: 13.67,
        schmelzpunkt: 994,
        siedepunkt: 2607,
        elektronegativität: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Curium",
        kurzsymbol: "Cm",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "silbrig weißes Metall",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Curium",
        flammenfarbe: "-/-",
        zweitname: "Kurium",
        protonen: 96,
        neutronen: 151,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0.00001805,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 247.070347,
        ionisierungsenergie: 5.9914,
        dichte: 13.52,
        schmelzpunkt: 1340,
        siedepunkt: 3100,
        elektronegativität: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Berkelium",
        kurzsymbol: "Bk",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "silberweiß",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Berkelium",
        flammenfarbe: "-/-",
        zweitname: "Bercelium",
        protonen: 97,
        neutronen: 150,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0.00001684,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 247.070299,
        ionisierungsenergie: 6.1979,
        dichte: 14.78,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Californium",
        kurzsymbol: "Cf",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "silbrig",
        aggregatszustand: "fest",
        struktur: "hexagonal",
        wikipedia: "https://de.wikipedia.org/wiki/Californium",
        flammenfarbe: "-/-",
        zweitname: "Kalifornium",
        protonen: 98,
        neutronen: 153,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0.0000165,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 251.07958,
        ionisierungsenergie: 6.2817,
        dichte: 15.1,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Einsteinium",
        kurzsymbol: "Es",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "kubisch",
        wikipedia: "https://de.wikipedia.org/wiki/Einsteinium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 99,
        neutronen: 153,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0.00000884,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 252.08297,
        ionisierungsenergie: 6.42,
        dichte: 8.84,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Fermium",
        kurzsymbol: "Fm",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Fermium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 100,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 257.095099,
        ionisierungsenergie: 6.5,
        dichte: 0,
        schmelzpunkt: 852,
        siedepunkt: 0,
        elektronegativität: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Mendelevium",
        kurzsymbol: "Md",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Mendelevium",
        flammenfarbe: "-/-",
        zweitname: "Mendelefium",
        protonen: 101,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 258.098425,
        ionisierungsenergie: 6.58,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Nobelium",
        kurzsymbol: "No",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Nobelium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 102,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 259.10102,
        ionisierungsenergie: 6.65,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Lawrencium",
        kurzsymbol: "Lr",
        unterkategorie: "Actinoid",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Lawrencium",
        flammenfarbe: "-/-",
        zweitname: "Lawrenkium",
        protonen: 103,
        neutronen: 163,
        lost: 3,
        hauptgruppe: 21,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 262.10969,
        ionisierungsenergie: 4.9,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Rutherfordium",
        kurzsymbol: "Rf",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Rutherfordium",
        flammenfarbe: "-/-",
        zweitname: "Ruterfordium",
        protonen: 104,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 4,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 261.10875,
        ionisierungsenergie: 6,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Dubnium",
        kurzsymbol: "Db",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Dubnium",
        flammenfarbe: "-/-",
        zweitname: "Dupnium",
        protonen: 105,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 5,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 262.11415,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Seaborgium",
        kurzsymbol: "Sg",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "-/-",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Seaborgium",
        flammenfarbe: "-/-",
        zweitname: "Unnilhexium",
        protonen: 106,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 6,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 266.12193,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Bohrium",
        kurzsymbol: "Bh",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Bohrium",
        flammenfarbe: "-/-",
        zweitname: "Borium",
        protonen: 107,
        neutronen: 155,
        lost: 2,
        hauptgruppe: 7,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 264.12473,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Hassium",
        kurzsymbol: "Hs",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Hassium",
        flammenfarbe: "-/-",
        zweitname: "Unniloctium",
        protonen: 108,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 8,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 269,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Meitnerium",
        kurzsymbol: "Mt",
        unterkategorie: "Wahrscheinlich ein Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "wahrscheinlich silbergrau",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Meitnerium",
        flammenfarbe: "-/-",
        zweitname: "Unnilennium",
        protonen: 109,
        neutronen: 159,
        lost: 2,
        hauptgruppe: 9,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 268,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Darmstadtium",
        kurzsymbol: "Ds",
        unterkategorie: "Wahrscheinlich ein Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Darmstadtium",
        flammenfarbe: "-/-",
        zweitname: "-/-",
        protonen: 110,
        neutronen: 171,
        lost: 1,
        hauptgruppe: 10,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 281,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Roentgenium",
        kurzsymbol: "Rg",
        unterkategorie: "Wahrscheinlich ein Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Roentgenium",
        flammenfarbe: "-/-",
        zweitname: "Röntgenium",
        protonen: 111,
        neutronen: 169,
        lost: 1,
        hauptgruppe: 11,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 280,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Copernicium",
        kurzsymbol: "Cn",
        unterkategorie: "Übergangsmetall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Copernicium",
        flammenfarbe: "-/-",
        zweitname: "Copernikium",
        protonen: 112,
        neutronen: 165,
        lost: 2,
        hauptgruppe: 12,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 277,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Nihonium",
        kurzsymbol: "Uut",
        unterkategorie: "Wahrscheinlich ein Metall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Ununtrium",
        flammenfarbe: "-/-",
        zweitname: "Ununtrium",
        protonen: 113,
        neutronen: 171,
        lost: 3,
        hauptgruppe: 13,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 284,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Flerovium",
        kurzsymbol: "Fl",
        unterkategorie: "Wahrscheinlich ein Metall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Flerovium",
        flammenfarbe: "-/-",
        zweitname: "Flerofium",
        protonen: 114,
        neutronen: 175,
        lost: 4,
        hauptgruppe: 14,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 289,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Moscovium",
        kurzsymbol: "Mc",
        unterkategorie: "Wahrscheinlich ein Metall",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Ununpentium",
        flammenfarbe: "-/-",
        zweitname: "Ununpentium",
        protonen: 115,
        neutronen: 173,
        lost: 5,
        hauptgruppe: 15,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 288,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Livermorium",
        kurzsymbol: "Lv",
        unterkategorie: "Unbekannt",
        oberkategorie: "Metall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Livermorium",
        flammenfarbe: "-/-",
        zweitname: "Lifermorium",
        protonen: 116,
        neutronen: 177,
        lost: 6,
        hauptgruppe: 16,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 293,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Tennessine",
        kurzsymbol: "Ts",
        unterkategorie: "Wahrscheinlich ein Halogen",
        oberkategorie: "Nichtmetall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Ununseptium",
        flammenfarbe: "-/-",
        zweitname: "Ununseptium",
        protonen: 117,
        neutronen: 175,
        lost: 7,
        hauptgruppe: 17,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 292,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Oganesson",
        kurzsymbol: "Og",
        unterkategorie: "Wahrscheinlich ein Edelgas",
        oberkategorie: "Nichtmetall",
        aussehen: "Noch nicht erforscht",
        aggregatszustand: "fest",
        struktur: "-/-",
        wikipedia: "https://de.wikipedia.org/wiki/Ununoctium",
        flammenfarbe: "-/-",
        zweitname: "Ununoctium",
        protonen: 118,
        neutronen: 176,
        lost: 8,
        hauptgruppe: 18,
        periode: 7,
        haerte: 0,
        volumen: 0,
        prozentsatzAnDerErdhuelle: 0,
        atommasse: 294,
        ionisierungsenergie: 0,
        dichte: 0,
        schmelzpunkt: 0,
        siedepunkt: 0,
        elektronegativität: 0,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
]