export interface ElementData {
    name: string,
    kurzsymbol: string,
    protonen: number,
    neutronen: number,
    oberkategorie: string,
    unterkategorie?: string,
    hauptgruppe: number,
    periode: number,
    aussehen?: string,
    aggregatszustand?: string,
    struktur?: string,
    haerte?: number,
    volumen?: number,
    radioaktiv: boolean,
    synthetischHergestellt: boolean,
    prozentsatzAnDerErdhuelle?: number,
    atommasse: number,
    ionisierungsenergie?: number,
    dichte?: number,
    schmelzpunkt?: number,
    siedepunkt?: number,
    elektronegativitaet?: number,
    flammenfarbe?: string,
    wikipedia: string,
    lost: number,
    zweitname?: string,
}