import { ElementData } from "./elementData";

export const elementsEn: ElementData[] = [
    {
        name: "Hydrogen",
        kurzsymbol: "H",
        unterkategorie: undefined,
        oberkategorie: "Nonmetal",
        aussehen: "colorless gas",
        aggregatszustand: "gas",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Hydrogen",
        flammenfarbe: undefined,
        zweitname: "Hydrogenium",
        protonen: 1,
        neutronen: 0,
        lost: 1,
        hauptgruppe: 1,
        periode: 1,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: 0.88,
        atommasse: 1.00794,
        ionisierungsenergie: 13.5984,
        dichte: 0.0736,
        schmelzpunkt: -259.14,
        siedepunkt: -252.87,
        elektronegativitaet: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Helium",
        kurzsymbol: "He",
        unterkategorie: "Noble Gas",
        oberkategorie: "Nonmetal",
        aussehen: "colorless gas",
        aggregatszustand: "gas",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Helium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 2,
        neutronen: 2,
        lost: 2,
        hauptgruppe: 18,
        periode: 1,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: 0.0000004,
        atommasse: 4.002602,
        ionisierungsenergie: 24.5874,
        dichte: 0.176,
        schmelzpunkt: -273,
        siedepunkt: -268.93,
        elektronegativitaet: 5.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Lithium",
        kurzsymbol: "Li",
        unterkategorie: "Alkali Metal",
        oberkategorie: "Metal",
        aussehen: "silvery-white/gray",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Lithium",
        flammenfarbe: undefined,
        zweitname: "Litium",
        protonen: 3,
        neutronen: 4,
        lost: 1,
        hauptgruppe: 1,
        periode: 2,
        haerte: 0.6,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: 0.006,
        atommasse: 6.941,
        ionisierungsenergie: 5.3917,
        dichte: 0.535,
        schmelzpunkt: 180.54,
        siedepunkt: 1347,
        elektronegativitaet: 0.98,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Beryllium",
        kurzsymbol: "Be",
        unterkategorie: "Alkaline earth metal",
        oberkategorie: "Metal",
        aussehen: "white-grey metallic",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Beryllium",
        flammenfarbe: undefined,
        zweitname: "Berillium",
        protonen: 4,
        neutronen: 5,
        lost: 2,
        hauptgruppe: 2,
        periode: 2,
        haerte: 5.5,
        volumen: 0.00000485,
        prozentsatzAnDerErdhuelle: 0.0005,
        atommasse: 9.012182,
        ionisierungsenergie: 9.3227,
        dichte: 1.848,
        schmelzpunkt: 1278,
        siedepunkt: 2970,
        elektronegativitaet: 1.57,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Boron",
        kurzsymbol: "B",
        unterkategorie: undefined,
        oberkategorie: "Metalloid",
        aussehen: "",
        aggregatszustand: "solid",
        struktur: "rhombohedral",
        wikipedia: "https://en.wikipedia.org/wiki/Boron",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 5,
        neutronen: 6,
        lost: 3,
        hauptgruppe: 13,
        periode: 2,
        haerte: 9.3,
        volumen: 0.00000439,
        prozentsatzAnDerErdhuelle: 0.001,
        atommasse: 10.811,
        ionisierungsenergie: 8.298,
        dichte: 2.46,
        schmelzpunkt: 2079,
        siedepunkt: 2550,
        elektronegativitaet: 2.04,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Carbon",
        kurzsymbol: "C",
        unterkategorie: undefined,
        oberkategorie: "Nonmetal",
        aussehen: "black (graphite), colorless (diamond), yellow-brown (Lonsdaleit)",
        aggregatszustand: "solid",
        struktur: "2 different modifications",
        wikipedia: "https://en.wikipedia.org/wiki/Carbon",
        flammenfarbe: undefined,
        zweitname: "Carboneum",
        protonen: 6,
        neutronen: 6,
        lost: 4,
        hauptgruppe: 14,
        periode: 2,
        haerte: 0.5,
        volumen: 0.00000531,
        prozentsatzAnDerErdhuelle: 0.087,
        atommasse: 12.0107,
        ionisierungsenergie: 11.2603,
        dichte: 2.267,
        schmelzpunkt: 3550,
        siedepunkt: 4827,
        elektronegativitaet: 2.55,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Nitrogen",
        kurzsymbol: "N",
        unterkategorie: undefined,
        oberkategorie: "Nonmetal",
        aussehen: "colorless gas",
        aggregatszustand: "gas",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Nitrogen",
        flammenfarbe: undefined,
        zweitname: "Nitrogenium",
        protonen: 7,
        neutronen: 7,
        lost: 5,
        hauptgruppe: 15,
        periode: 2,
        haerte: undefined,
        volumen: 0.00001354,
        prozentsatzAnDerErdhuelle: 0.03,
        atommasse: 14.0067,
        ionisierungsenergie: 14.5341,
        dichte: 1.897,
        schmelzpunkt: -209.86,
        siedepunkt: -195.8,
        elektronegativitaet: 3.04,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Oxygen",
        kurzsymbol: "O",
        unterkategorie: undefined,
        oberkategorie: "Nonmetal",
        aussehen: "colorless gas",
        aggregatszustand: "gas",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Oxygen",
        flammenfarbe: undefined,
        zweitname: "Oxygenium",
        protonen: 8,
        neutronen: 8,
        lost: 6,
        hauptgruppe: 16,
        periode: 2,
        haerte: undefined,
        volumen: 0.00001736,
        prozentsatzAnDerErdhuelle: 49.4,
        atommasse: 15.9994,
        ionisierungsenergie: 13.6181,
        dichte: 1.426,
        schmelzpunkt: -218.4,
        siedepunkt: -182.96,
        elektronegativitaet: 3.44,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Fluorine",
        kurzsymbol: "F",
        unterkategorie: "Halogen",
        oberkategorie: "Nonmetal",
        aussehen: "Pale, yellowish gas",
        aggregatszustand: "gas",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Fluorine",
        flammenfarbe: undefined,
        zweitname: "Fluorum",
        protonen: 9,
        neutronen: 10,
        lost: 7,
        hauptgruppe: 17,
        periode: 2,
        haerte: undefined,
        volumen: 0.0000112,
        prozentsatzAnDerErdhuelle: 0.03,
        atommasse: 18.9984032,
        ionisierungsenergie: 17.4228,
        dichte: 1.5127,
        schmelzpunkt: -219.62,
        siedepunkt: -188.14,
        elektronegativitaet: 3.98,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Neon",
        kurzsymbol: "Ne",
        unterkategorie: "Noble Gas",
        oberkategorie: "Nonmetal",
        aussehen: "colorless gas",
        aggregatszustand: "gas",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Neon",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 10,
        neutronen: 10,
        lost: 8,
        hauptgruppe: 18,
        periode: 2,
        haerte: undefined,
        volumen: 0.00001323,
        prozentsatzAnDerErdhuelle: 0.0000005,
        atommasse: 20.1797,
        ionisierungsenergie: 21.5645,
        dichte: 1.444,
        schmelzpunkt: -248.67,
        siedepunkt: -246.05,
        elektronegativitaet: undefined,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Sodium",
        kurzsymbol: "Na",
        unterkategorie: "Alkali Metal",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Sodium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 11,
        neutronen: 12,
        lost: 1,
        hauptgruppe: 1,
        periode: 3,
        haerte: 0.5,
        volumen: 0.00002378,
        prozentsatzAnDerErdhuelle: 2.64,
        atommasse: 22.98976928,
        ionisierungsenergie: 5.1391,
        dichte: 0.968,
        schmelzpunkt: 97.81,
        siedepunkt: 882.9,
        elektronegativitaet: 0.93,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Magnesium",
        kurzsymbol: "Mg",
        unterkategorie: "Alkaline earth metal",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Magnesium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 12,
        neutronen: 12,
        lost: 2,
        hauptgruppe: 2,
        periode: 3,
        haerte: 2.5,
        volumen: 0.000014,
        prozentsatzAnDerErdhuelle: 1.94,
        atommasse: 24.305,
        ionisierungsenergie: 7.6462,
        dichte: 1.738,
        schmelzpunkt: 648.8,
        siedepunkt: 1090,
        elektronegativitaet: 1.31,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Aluminium",
        kurzsymbol: "Al",
        unterkategorie: undefined,
        oberkategorie: "Metal",
        aussehen: "silvery",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Aluminium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 13,
        neutronen: 14,
        lost: 3,
        hauptgruppe: 13,
        periode: 3,
        haerte: 2.75,
        volumen: 0.00001,
        prozentsatzAnDerErdhuelle: 7.57,
        atommasse: 26.9815386,
        ionisierungsenergie: 5.9858,
        dichte: 2.7,
        schmelzpunkt: 660.37,
        siedepunkt: 2467,
        elektronegativitaet: 1.61,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Silicon",
        kurzsymbol: "Si",
        unterkategorie: undefined,
        oberkategorie: "Metalloid",
        aussehen: "dark gray, bluish hue",
        aggregatszustand: "solid",
        struktur: "Diamond structure",
        wikipedia: "https://en.wikipedia.org/wiki/Silicon",
        flammenfarbe: undefined,
        zweitname: "Silizium",
        protonen: 14,
        neutronen: 14,
        lost: 4,
        hauptgruppe: 14,
        periode: 3,
        haerte: 6.5,
        volumen: 0.00001206,
        prozentsatzAnDerErdhuelle: 25.8,
        atommasse: 28.0855,
        ionisierungsenergie: 8.1517,
        dichte: 2.33,
        schmelzpunkt: 1410,
        siedepunkt: 2355,
        elektronegativitaet: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Phosphorus",
        kurzsymbol: "P",
        unterkategorie: undefined,
        oberkategorie: "Nonmetal",
        aussehen: "white-beige, dark red, black, (with 3 different modifications)",
        aggregatszustand: "solid",
        struktur: "orthorhombic",
        wikipedia: "https://en.wikipedia.org/wiki/Phosphorus",
        flammenfarbe: undefined,
        zweitname: "Phosfor",
        protonen: 15,
        neutronen: 16,
        lost: 5,
        hauptgruppe: 15,
        periode: 3,
        haerte: 1.5,
        volumen: 0.00001702,
        prozentsatzAnDerErdhuelle: 0.09,
        atommasse: 30.973762,
        ionisierungsenergie: 10.4867,
        dichte: 1.82,
        schmelzpunkt: 44.1,
        siedepunkt: 280,
        elektronegativitaet: 2.19,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Sulphur",
        kurzsymbol: "S",
        unterkategorie: undefined,
        oberkategorie: "Nonmetal",
        aussehen: "yellow",
        aggregatszustand: "solid",
        struktur: "orthorhombic",
        wikipedia: "https://en.wikipedia.org/wiki/Sulphur",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 16,
        neutronen: 16,
        lost: 6,
        hauptgruppe: 16,
        periode: 3,
        haerte: 2,
        volumen: 0.00001553,
        prozentsatzAnDerErdhuelle: 0.048,
        atommasse: 32.065,
        ionisierungsenergie: 10.36,
        dichte: 2.06,
        schmelzpunkt: 112.8,
        siedepunkt: 444.67,
        elektronegativitaet: 2.58,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Chlorine",
        kurzsymbol: "Cl",
        unterkategorie: "Halogen",
        oberkategorie: "Nonmetal",
        aussehen: "yellowish-green",
        aggregatszustand: "solid",
        struktur: "orthorhombic",
        wikipedia: "https://en.wikipedia.org/wiki/Chlorine",
        flammenfarbe: undefined,
        zweitname: "Chlorum",
        protonen: 17,
        neutronen: 18,
        lost: 7,
        hauptgruppe: 17,
        periode: 3,
        haerte: undefined,
        volumen: 0.00001739,
        prozentsatzAnDerErdhuelle: 0.19,
        atommasse: 35.453,
        ionisierungsenergie: 12.9676,
        dichte: 2.03,
        schmelzpunkt: -100.98,
        siedepunkt: -34.6,
        elektronegativitaet: 3.16,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Argon",
        kurzsymbol: "Ar",
        unterkategorie: "Noble Gas",
        oberkategorie: "Nonmetal",
        aussehen: "colorless gas",
        aggregatszustand: "gas",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Argon",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 18,
        neutronen: 22,
        lost: 8,
        hauptgruppe: 18,
        periode: 3,
        haerte: undefined,
        volumen: 0.00002256,
        prozentsatzAnDerErdhuelle: 0.0004,
        atommasse: 39.948,
        ionisierungsenergie: 15.7596,
        dichte: 1.656,
        schmelzpunkt: -189.2,
        siedepunkt: -185.7,
        elektronegativitaet: undefined,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Potassium",
        kurzsymbol: "K",
        unterkategorie: "Alkali Metal",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Potassium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 19,
        neutronen: 20,
        lost: 1,
        hauptgruppe: 1,
        periode: 4,
        haerte: 0.4,
        volumen: 0.00004594,
        prozentsatzAnDerErdhuelle: 2.4,
        atommasse: 39.0983,
        ionisierungsenergie: 4.3407,
        dichte: 0.856,
        schmelzpunkt: 63.65,
        siedepunkt: 774,
        elektronegativitaet: 0.82,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Calcium",
        kurzsymbol: "Ca",
        unterkategorie: "Alkaline earth metal",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Calcium",
        flammenfarbe: undefined,
        zweitname: "Kalkium",
        protonen: 20,
        neutronen: 20,
        lost: 2,
        hauptgruppe: 2,
        periode: 4,
        haerte: 1.75,
        volumen: 0.0000262,
        prozentsatzAnDerErdhuelle: 3.39,
        atommasse: 40.078,
        ionisierungsenergie: 6.1132,
        dichte: 1.55,
        schmelzpunkt: 839,
        siedepunkt: 1484,
        elektronegativitaet: 1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Scandium",
        kurzsymbol: "Sc",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Scandium",
        flammenfarbe: undefined,
        zweitname: "Skandium",
        protonen: 21,
        neutronen: 24,
        lost: 2,
        hauptgruppe: 3,
        periode: 4,
        haerte: 2.5,
        volumen: 0.000015,
        prozentsatzAnDerErdhuelle: 0.0005,
        atommasse: 44.955912,
        ionisierungsenergie: 6.5615,
        dichte: 2.985,
        schmelzpunkt: 1541,
        siedepunkt: 2831,
        elektronegativitaet: 1.36,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Titanium",
        kurzsymbol: "Ti",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery metallic",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Titanium",
        flammenfarbe: undefined,
        zweitname: "Titanium",
        protonen: 22,
        neutronen: 26,
        lost: 2,
        hauptgruppe: 4,
        periode: 4,
        haerte: 6,
        volumen: 0.00001064,
        prozentsatzAnDerErdhuelle: 0.41,
        atommasse: 47.867,
        ionisierungsenergie: 6.8281,
        dichte: 4.507,
        schmelzpunkt: 1660,
        siedepunkt: 3287,
        elektronegativitaet: 1.54,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Vanadium",
        kurzsymbol: "V",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "metallic steel gray, bluish shimmer",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Vanadium",
        flammenfarbe: undefined,
        zweitname: "Wanadium",
        protonen: 23,
        neutronen: 28,
        lost: 2,
        hauptgruppe: 5,
        periode: 4,
        haerte: 7,
        volumen: 0.00000832,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 50.9415,
        ionisierungsenergie: 6.7462,
        dichte: 6.11,
        schmelzpunkt: 1890,
        siedepunkt: 3380,
        elektronegativitaet: 1.63,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Chromium",
        kurzsymbol: "Cr",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery metallic",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Chromium",
        flammenfarbe: undefined,
        zweitname: "Chromium",
        protonen: 24,
        neutronen: 28,
        lost: 1,
        hauptgruppe: 6,
        periode: 4,
        haerte: 8.5,
        volumen: 0.00000723,
        prozentsatzAnDerErdhuelle: 0.02,
        atommasse: 51.9961,
        ionisierungsenergie: 6.7665,
        dichte: 7.14,
        schmelzpunkt: 1857,
        siedepunkt: 2672,
        elektronegativitaet: 1.66,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Manganese",
        kurzsymbol: "Mn",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery metallic (Stahlweiß)",
        aggregatszustand: "solid",
        struktur: "4 different modifications",
        wikipedia: "https://en.wikipedia.org/wiki/Manganese",
        flammenfarbe: undefined,
        zweitname: "Manganum",
        protonen: 25,
        neutronen: 30,
        lost: 2,
        hauptgruppe: 7,
        periode: 4,
        haerte: 6,
        volumen: 0.00000735,
        prozentsatzAnDerErdhuelle: 0.085,
        atommasse: 54.938045,
        ionisierungsenergie: 7.434,
        dichte: 7.43,
        schmelzpunkt: 1244,
        siedepunkt: 1962,
        elektronegativitaet: 1.55,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Iron",
        kurzsymbol: "Fe",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "shiny metallic with a grayish hue",
        aggregatszustand: "solid",
        struktur: "4 different modifications",
        wikipedia: "https://en.wikipedia.org/wiki/Iron",
        flammenfarbe: undefined,
        zweitname: "Ferrum",
        protonen: 26,
        neutronen: 30,
        lost: 2,
        hauptgruppe: 8,
        periode: 4,
        haerte: 4,
        volumen: 0.00000709,
        prozentsatzAnDerErdhuelle: 4.7,
        atommasse: 55.845,
        ionisierungsenergie: 7.9024,
        dichte: 7.874,
        schmelzpunkt: 1535,
        siedepunkt: 2750,
        elektronegativitaet: 1.83,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Cobalt",
        kurzsymbol: "Co",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "Metallic with a bluish-greyish hue",
        aggregatszustand: "solid",
        struktur: "2 different modifications",
        wikipedia: "https://en.wikipedia.org/wiki/Cobalt",
        flammenfarbe: undefined,
        zweitname: "Kobalt",
        protonen: 27,
        neutronen: 32,
        lost: 2,
        hauptgruppe: 9,
        periode: 4,
        haerte: 5,
        volumen: 0.00000667,
        prozentsatzAnDerErdhuelle: 0.004,
        atommasse: 58.933195,
        ionisierungsenergie: 7.881,
        dichte: 8.9,
        schmelzpunkt: 1495,
        siedepunkt: 2870,
        elektronegativitaet: 1.88,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Nickel",
        kurzsymbol: "Ni",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "shiny, metallic, silvery",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Nickel",
        flammenfarbe: undefined,
        zweitname: "Niccolum",
        protonen: 28,
        neutronen: 31,
        lost: 2,
        hauptgruppe: 10,
        periode: 4,
        haerte: 4,
        volumen: 0.00000659,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 28.6934,
        ionisierungsenergie: 7.6398,
        dichte: 8.908,
        schmelzpunkt: 1453,
        siedepunkt: 2732,
        elektronegativitaet: 1.91,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Copper",
        kurzsymbol: "Cu",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "lachsrosa, metallic",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Copper",
        flammenfarbe: undefined,
        zweitname: "Cuprum",
        protonen: 29,
        neutronen: 35,
        lost: 1,
        hauptgruppe: 11,
        periode: 4,
        haerte: 3,
        volumen: 0.00000711,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 63.546,
        ionisierungsenergie: 7.7264,
        dichte: 8.92,
        schmelzpunkt: 1083,
        siedepunkt: 2567,
        elektronegativitaet: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Zinc",
        kurzsymbol: "Zn",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "bluish pale gray",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Zinc",
        flammenfarbe: undefined,
        zweitname: "Zinkum",
        protonen: 30,
        neutronen: 35,
        lost: 2,
        hauptgruppe: 12,
        periode: 4,
        haerte: 2.5,
        volumen: 0.00000916,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 65.409,
        ionisierungsenergie: 9.3942,
        dichte: 7.14,
        schmelzpunkt: 419.6,
        siedepunkt: 907,
        elektronegativitaet: 1.65,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Gallium",
        kurzsymbol: "Ga",
        unterkategorie: undefined,
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Gallium",
        flammenfarbe: undefined,
        zweitname: "Galium",
        protonen: 31,
        neutronen: 39,
        lost: 3,
        hauptgruppe: 13,
        periode: 4,
        haerte: 1.5,
        volumen: 0.0000118,
        prozentsatzAnDerErdhuelle: 0.003,
        atommasse: 69.723,
        ionisierungsenergie: 5.9993,
        dichte: 5.904,
        schmelzpunkt: 29.78,
        siedepunkt: 2403,
        elektronegativitaet: 1.81,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Germanium",
        kurzsymbol: "Ge",
        unterkategorie: undefined,
        oberkategorie: "Metalloid",
        aussehen: "grayish white",
        aggregatszustand: "solid",
        struktur: "Diamond structure",
        wikipedia: "https://en.wikipedia.org/wiki/Germanium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 32,
        neutronen: 41,
        lost: 4,
        hauptgruppe: 14,
        periode: 4,
        haerte: 6,
        volumen: 0.00001363,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 72.631,
        ionisierungsenergie: 7.8994,
        dichte: 5.323,
        schmelzpunkt: 937.4,
        siedepunkt: 2830,
        elektronegativitaet: 2.01,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Arsenic",
        kurzsymbol: "As",
        unterkategorie: undefined,
        oberkategorie: "Metalloid",
        aussehen: "metallic gray, yellow oder black",
        aggregatszustand: "solid",
        struktur: "trigonal (gray)",
        wikipedia: "https://en.wikipedia.org/wiki/Arsenic",
        flammenfarbe: undefined,
        zweitname: "Arsenicum",
        protonen: 33,
        neutronen: 42,
        lost: 5,
        hauptgruppe: 15,
        periode: 4,
        haerte: 3.5,
        volumen: 0.00001295,
        prozentsatzAnDerErdhuelle: 0.00055,
        atommasse: 74.9216,
        ionisierungsenergie: 9.7886,
        dichte: 5.72,
        schmelzpunkt: 616,
        siedepunkt: 616,
        elektronegativitaet: 2.18,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Selenium",
        kurzsymbol: "Se",
        unterkategorie: undefined,
        oberkategorie: "Metalloid",
        aussehen: "gray, shiny",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Selenium",
        flammenfarbe: undefined,
        zweitname: "Selenium",
        protonen: 34,
        neutronen: 45,
        lost: 6,
        hauptgruppe: 16,
        periode: 4,
        haerte: 2,
        volumen: 0.00001642,
        prozentsatzAnDerErdhuelle: 0.00008,
        atommasse: 78.971,
        ionisierungsenergie: 9.7524,
        dichte: 4.819,
        schmelzpunkt: 217,
        siedepunkt: 684.9,
        elektronegativitaet: 2.55,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Bromine",
        kurzsymbol: "Br",
        unterkategorie: "Halogen",
        oberkategorie: "Nonmetal",
        aussehen: "red-brown, solid: metallic shiny",
        aggregatszustand: "liquid",
        struktur: "orthorhombic",
        wikipedia: "https://en.wikipedia.org/wiki/Bromine",
        flammenfarbe: undefined,
        zweitname: "Bromum",
        protonen: 35,
        neutronen: 45,
        lost: 7,
        hauptgruppe: 17,
        periode: 4,
        haerte: undefined,
        volumen: 0.00001978,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 79.904,
        ionisierungsenergie: 11.8138,
        dichte: 4.05,
        schmelzpunkt: -7.2,
        siedepunkt: 58.78,
        elektronegativitaet: 2.96,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Krypton",
        kurzsymbol: "Kr",
        unterkategorie: "Noble Gas",
        oberkategorie: "Nonmetal",
        aussehen: "colorless gas",
        aggregatszustand: "gas",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Krypton",
        flammenfarbe: undefined,
        zweitname: "Crypton",
        protonen: 36,
        neutronen: 48,
        lost: 8,
        hauptgruppe: 18,
        periode: 4,
        haerte: undefined,
        volumen: 0.00002799,
        prozentsatzAnDerErdhuelle: 0.00000002,
        atommasse: 83.798,
        ionisierungsenergie: 13.9996,
        dichte: 2.823,
        schmelzpunkt: -156.6,
        siedepunkt: -152.3,
        elektronegativitaet: 3,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Rubidium",
        kurzsymbol: "Rb",
        unterkategorie: "Alkali Metal",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Rubidium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 37,
        neutronen: 48,
        lost: 1,
        hauptgruppe: 1,
        periode: 5,
        haerte: 0.3,
        volumen: 0.00005576,
        prozentsatzAnDerErdhuelle: 0.03,
        atommasse: 84.4678,
        ionisierungsenergie: 4.1771,
        dichte: 1.532,
        schmelzpunkt: 38.89,
        siedepunkt: 688,
        elektronegativitaet: 0.82,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Strontium",
        kurzsymbol: "Sr",
        unterkategorie: "Alkaline earth metal",
        oberkategorie: "Metal",
        aussehen: "silvery white metallic",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Strontium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 38,
        neutronen: 50,
        lost: 2,
        hauptgruppe: 2,
        periode: 5,
        haerte: 1.5,
        volumen: 0.00003394,
        prozentsatzAnDerErdhuelle: 0.01,
        atommasse: 87.621,
        ionisierungsenergie: 5.6949,
        dichte: 2.63,
        schmelzpunkt: 769,
        siedepunkt: 1384,
        elektronegativitaet: 0.95,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Yttrium",
        kurzsymbol: "Y",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Yttrium",
        flammenfarbe: undefined,
        zweitname: "Ittrium",
        protonen: 39,
        neutronen: 50,
        lost: 2,
        hauptgruppe: 3,
        periode: 5,
        haerte: undefined,
        volumen: 0.00001988,
        prozentsatzAnDerErdhuelle: 0.003,
        atommasse: 88.90585,
        ionisierungsenergie: 6.2173,
        dichte: 4.469,
        schmelzpunkt: 1522,
        siedepunkt: 3338,
        elektronegativitaet: 1.22,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Zirconium",
        kurzsymbol: "Zr",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal, cubic > 1140 K",
        wikipedia: "https://en.wikipedia.org/wiki/Zirconium",
        flammenfarbe: undefined,
        zweitname: "Zirkonium",
        protonen: 40,
        neutronen: 51,
        lost: 2,
        hauptgruppe: 4,
        periode: 5,
        haerte: 5,
        volumen: 0.00001402,
        prozentsatzAnDerErdhuelle: 0.02,
        atommasse: 91.2242,
        ionisierungsenergie: 6.6339,
        dichte: 6.506,
        schmelzpunkt: 1852,
        siedepunkt: 4377,
        elektronegativitaet: 1.33,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Niob",
        kurzsymbol: "Nb",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "gray metallic shiny",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Niob",
        flammenfarbe: undefined,
        zweitname: "Niobium",
        protonen: 41,
        neutronen: 52,
        lost: 1,
        hauptgruppe: 5,
        periode: 5,
        haerte: 6,
        volumen: 0.00001083,
        prozentsatzAnDerErdhuelle: 0.002,
        atommasse: 92.90638,
        ionisierungsenergie: 6.7589,
        dichte: 8.57,
        schmelzpunkt: 2468,
        siedepunkt: 4742,
        elektronegativitaet: 1.6,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Molybdenum",
        kurzsymbol: "Mo",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "gray metallic",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Molybdenum",
        flammenfarbe: undefined,
        zweitname: "Molybdaenum",
        protonen: 42,
        neutronen: 54,
        lost: 1,
        hauptgruppe: 6,
        periode: 5,
        haerte: 5.5,
        volumen: 0.00000938,
        prozentsatzAnDerErdhuelle: 0.001,
        atommasse: 95.951,
        ionisierungsenergie: 7.0924,
        dichte: 10.28,
        schmelzpunkt: 2617,
        siedepunkt: 4612,
        elektronegativitaet: 2.16,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Technetium",
        kurzsymbol: "Tc",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery gray metallic",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Technetium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 43,
        neutronen: 56,
        lost: 2,
        hauptgruppe: 7,
        periode: 5,
        haerte: undefined,
        volumen: 0.00000863,
        prozentsatzAnDerErdhuelle: 0.0000000000000005,
        atommasse: 98.9063,
        ionisierungsenergie: 7.28,
        dichte: 11.5,
        schmelzpunkt: 2172,
        siedepunkt: 4877,
        elektronegativitaet: 2.1,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Ruthenium",
        kurzsymbol: "Ru",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery white metallic",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Ruthenium",
        flammenfarbe: undefined,
        zweitname: "Rutenium",
        protonen: 44,
        neutronen: 57,
        lost: 1,
        hauptgruppe: 8,
        periode: 5,
        haerte: 6.5,
        volumen: 0.00000817,
        prozentsatzAnDerErdhuelle: 0.000002,
        atommasse: 101.072,
        ionisierungsenergie: 7.30605,
        dichte: 12.37,
        schmelzpunkt: 2310,
        siedepunkt: 3900,
        elektronegativitaet: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Rhodium",
        kurzsymbol: "Rh",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery white metallic",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Rhodium",
        flammenfarbe: undefined,
        zweitname: "Rodium",
        protonen: 45,
        neutronen: 58,
        lost: 1,
        hauptgruppe: 9,
        periode: 5,
        haerte: 6,
        volumen: 0.00000828,
        prozentsatzAnDerErdhuelle: 0.0000001,
        atommasse: 102.9055,
        ionisierungsenergie: 7.4589,
        dichte: 12.38,
        schmelzpunkt: 1966,
        siedepunkt: 3727,
        elektronegativitaet: 2.28,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Palladium",
        kurzsymbol: "Pd",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery, weiß, metallic",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Palladium",
        flammenfarbe: undefined,
        zweitname: "Paladium",
        protonen: 46,
        neutronen: 60,
        lost: 0,
        hauptgruppe: 10,
        periode: 5,
        haerte: 4.75,
        volumen: 0.00000856,
        prozentsatzAnDerErdhuelle: 0.000001,
        atommasse: 106.421,
        ionisierungsenergie: 8.3369,
        dichte: 11.99,
        schmelzpunkt: 1552,
        siedepunkt: 3140,
        elektronegativitaet: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Silver",
        kurzsymbol: "Ag",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "white-shiny, metallic",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Silver",
        flammenfarbe: undefined,
        zweitname: "Argentum",
        protonen: 47,
        neutronen: 61,
        lost: 1,
        hauptgruppe: 11,
        periode: 5,
        haerte: 2.7,
        volumen: 0.00001027,
        prozentsatzAnDerErdhuelle: 0.00001,
        atommasse: 107.8682,
        ionisierungsenergie: 7.5762,
        dichte: 10.49,
        schmelzpunkt: 961.9,
        siedepunkt: 2212,
        elektronegativitaet: 1.93,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Cadmium",
        kurzsymbol: "Cd",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery gray metallic",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Cadmium",
        flammenfarbe: undefined,
        zweitname: "Kadmium",
        protonen: 48,
        neutronen: 64,
        lost: 2,
        hauptgruppe: 12,
        periode: 5,
        haerte: 2,
        volumen: 0.000013,
        prozentsatzAnDerErdhuelle: 0.00003,
        atommasse: 112.411,
        ionisierungsenergie: 8.9938,
        dichte: 8.65,
        schmelzpunkt: 320.9,
        siedepunkt: 765,
        elektronegativitaet: 1.69,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Indium",
        kurzsymbol: "In",
        unterkategorie: undefined,
        oberkategorie: "Metal",
        aussehen: "silvery shiny gray",
        aggregatszustand: "solid",
        struktur: "tetragonal",
        wikipedia: "https://en.wikipedia.org/wiki/Indium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 49,
        neutronen: 66,
        lost: 3,
        hauptgruppe: 13,
        periode: 5,
        haerte: 1.2,
        volumen: 0.00001576,
        prozentsatzAnDerErdhuelle: 0.00001,
        atommasse: 114.818,
        ionisierungsenergie: 5.7864,
        dichte: 7.31,
        schmelzpunkt: 156.2,
        siedepunkt: 2080,
        elektronegativitaet: 1.78,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Tin",
        kurzsymbol: "Sn",
        unterkategorie: undefined,
        oberkategorie: "Metal",
        aussehen: "silvery shiny gray",
        aggregatszustand: "solid",
        struktur: "alpha-Tin -> cubic(Diamond structure), beta-Tin -> tetragonal",
        wikipedia: "https://en.wikipedia.org/wiki/Tin",
        flammenfarbe: undefined,
        zweitname: "Stannum",
        protonen: 50,
        neutronen: 69,
        lost: 4,
        hauptgruppe: 14,
        periode: 5,
        haerte: 1.5,
        volumen: 0.00001629,
        prozentsatzAnDerErdhuelle: 0.003,
        atommasse: 118.7107,
        ionisierungsenergie: 7.3439,
        dichte: 5.75,
        schmelzpunkt: 232,
        siedepunkt: 2270,
        elektronegativitaet: 1.96,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Antimony",
        kurzsymbol: "Sb",
        unterkategorie: undefined,
        oberkategorie: "Metalloid",
        aussehen: "silvery shiny gray",
        aggregatszustand: "solid",
        struktur: "trigonal",
        wikipedia: "https://en.wikipedia.org/wiki/Antimony",
        flammenfarbe: undefined,
        zweitname: "Stibium",
        protonen: 51,
        neutronen: 71,
        lost: 5,
        hauptgruppe: 15,
        periode: 5,
        haerte: 3,
        volumen: 0.00001819,
        prozentsatzAnDerErdhuelle: 0.000065,
        atommasse: 121.7601,
        ionisierungsenergie: 8.6084,
        dichte: 6.697,
        schmelzpunkt: 630.7,
        siedepunkt: 1750,
        elektronegativitaet: 2.05,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Tellurium",
        kurzsymbol: "Te",
        unterkategorie: undefined,
        oberkategorie: "Metalloid",
        aussehen: "silver white, metallic shiny",
        aggregatszustand: "solid",
        struktur: "trigonal",
        wikipedia: "https://en.wikipedia.org/wiki/Tellurium",
        flammenfarbe: undefined,
        zweitname: "Tellurium",
        protonen: 52,
        neutronen: 76,
        lost: 6,
        hauptgruppe: 16,
        periode: 5,
        haerte: 2.25,
        volumen: 0.00002046,
        prozentsatzAnDerErdhuelle: 0.000001,
        atommasse: 127.603,
        ionisierungsenergie: 9.0096,
        dichte: 6.24,
        schmelzpunkt: 449.5,
        siedepunkt: 990,
        elektronegativitaet: 2.1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Iodine",
        kurzsymbol: "I",
        unterkategorie: "Halogen",
        oberkategorie: "Nonmetal",
        aussehen: "Gas: dark purple, solid: gray shiny",
        aggregatszustand: "solid",
        struktur: "orthorhombic",
        wikipedia: "https://en.wikipedia.org/wiki/Iodine",
        flammenfarbe: undefined,
        zweitname: "Iodium",
        protonen: 53,
        neutronen: 74,
        lost: 7,
        hauptgruppe: 17,
        periode: 5,
        haerte: undefined,
        volumen: 0.00002572,
        prozentsatzAnDerErdhuelle: 0.000006,
        atommasse: 126.90447,
        ionisierungsenergie: 10.4513,
        dichte: 4.93,
        schmelzpunkt: 113.5,
        siedepunkt: 184.4,
        elektronegativitaet: 2.66,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Xenon",
        kurzsymbol: "Xe",
        unterkategorie: "Noble Gas",
        oberkategorie: "Nonmetal",
        aussehen: "colorless gas",
        aggregatszustand: "gas",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Xenon",
        flammenfarbe: undefined,
        zweitname: "Xenon",
        protonen: 54,
        neutronen: 77,
        lost: 8,
        hauptgruppe: 18,
        periode: 5,
        haerte: undefined,
        volumen: 0.00003592,
        prozentsatzAnDerErdhuelle: 0.000000002,
        atommasse: 131.293,
        ionisierungsenergie: 12.1298,
        dichte: 3.54,
        schmelzpunkt: -111.9,
        siedepunkt: -107.1,
        elektronegativitaet: 2.6,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Caesium",
        kurzsymbol: "Cs",
        unterkategorie: "Alkali Metal",
        oberkategorie: "Metal",
        aussehen: "silver white shiny, golden yellow with traces of oxygen",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Caesium",
        flammenfarbe: undefined,
        zweitname: "Cäsium",
        protonen: 55,
        neutronen: 78,
        lost: 1,
        hauptgruppe: 1,
        periode: 6,
        haerte: 0.2,
        volumen: 0.00007094,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 132.9054519,
        ionisierungsenergie: 3.8939,
        dichte: 1.93,
        schmelzpunkt: 28.4,
        siedepunkt: 678.4,
        elektronegativitaet: 0.79,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Barium",
        kurzsymbol: "Ba",
        unterkategorie: "Alkaline earth metal",
        oberkategorie: "Metal",
        aussehen: "weiß-gray metallic",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Barium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 56,
        neutronen: 81,
        lost: 2,
        hauptgruppe: 2,
        periode: 6,
        haerte: 1.25,
        volumen: 0.00003816,
        prozentsatzAnDerErdhuelle: 0.03,
        atommasse: 137.327,
        ionisierungsenergie: 5.2117,
        dichte: 3.62,
        schmelzpunkt: 725,
        siedepunkt: 1640,
        elektronegativitaet: 0.89,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Lanthanum",
        kurzsymbol: "La",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Lanthanum",
        flammenfarbe: undefined,
        zweitname: "Lanthanum",
        protonen: 57,
        neutronen: 82,
        lost: 2,
        hauptgruppe: 3,
        periode: 6,
        haerte: 3,
        volumen: 0.00002239,
        prozentsatzAnDerErdhuelle: 0.002,
        atommasse: 138.90547,
        ionisierungsenergie: 5.5769,
        dichte: 6.17,
        schmelzpunkt: 921,
        siedepunkt: 3457,
        elektronegativitaet: 1.1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Cerium",
        kurzsymbol: "Ce",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Cerium",
        flammenfarbe: undefined,
        zweitname: "Cerium",
        protonen: 58,
        neutronen: 82,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 2.5,
        volumen: 0.00002069,
        prozentsatzAnDerErdhuelle: 0.004,
        atommasse: 140.116,
        ionisierungsenergie: 5.5387,
        dichte: 8.16,
        schmelzpunkt: 799,
        siedepunkt: 3426,
        elektronegativitaet: 1.12,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Praesodymium",
        kurzsymbol: "Pr",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white, yellowish color",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Praseodymium",
        flammenfarbe: undefined,
        zweitname: "Praseodymium",
        protonen: 59,
        neutronen: 82,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.0000208,
        prozentsatzAnDerErdhuelle: 0.0005,
        atommasse: 140.90765,
        ionisierungsenergie: 5.473,
        dichte: 6.475,
        schmelzpunkt: 931,
        siedepunkt: 3512,
        elektronegativitaet: 1.13,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Neodymium",
        kurzsymbol: "Nd",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "metallic",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Neodymium",
        flammenfarbe: undefined,
        zweitname: "Neodymium",
        protonen: 60,
        neutronen: 84,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.00002059,
        prozentsatzAnDerErdhuelle: 0.002,
        atommasse: 144.242,
        ionisierungsenergie: 5.525,
        dichte: 7.003,
        schmelzpunkt: 1021,
        siedepunkt: 3068,
        elektronegativitaet: 1.14,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Promethium",
        kurzsymbol: "Pm",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "metallic",
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Promethium",
        flammenfarbe: undefined,
        zweitname: "Prometium",
        protonen: 61,
        neutronen: 86,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.0000201,
        prozentsatzAnDerErdhuelle: 0.0000000000000000001,
        atommasse: 144.912744,
        ionisierungsenergie: 5.582,
        dichte: 7.2,
        schmelzpunkt: 1168,
        siedepunkt: 2460,
        elektronegativitaet: 1.07,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Samarium",
        kurzsymbol: "Sm",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery",
        aggregatszustand: "solid",
        struktur: "trigonal",
        wikipedia: "https://en.wikipedia.org/wiki/Samarium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 62,
        neutronen: 88,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.00001998,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 150.362,
        ionisierungsenergie: 5.6437,
        dichte: 7.536,
        schmelzpunkt: 1077,
        siedepunkt: 1791,
        elektronegativitaet: 1.17,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Europium",
        kurzsymbol: "Eu",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Europium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 63,
        neutronen: 89,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.002897,
        prozentsatzAnDerErdhuelle: 0.00001,
        atommasse: 151.964,
        ionisierungsenergie: 5.6704,
        dichte: 5.245,
        schmelzpunkt: 822,
        siedepunkt: 1597,
        elektronegativitaet: 1.01,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Gadolinium",
        kurzsymbol: "Gd",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Gadolinium",
        flammenfarbe: undefined,
        zweitname: "Gatolinium",
        protonen: 64,
        neutronen: 93,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 1.5,
        volumen: 0.0000199,
        prozentsatzAnDerErdhuelle: 0.0006,
        atommasse: 157.253,
        ionisierungsenergie: 6.1498,
        dichte: 7.886,
        schmelzpunkt: 1313,
        siedepunkt: 3266,
        elektronegativitaet: 1.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Terbium",
        kurzsymbol: "Tb",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Terbium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 65,
        neutronen: 94,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.0000193,
        prozentsatzAnDerErdhuelle: 0.00009,
        atommasse: 158.92535,
        ionisierungsenergie: 5.8638,
        dichte: 8.253,
        schmelzpunkt: 1356,
        siedepunkt: 3123,
        elektronegativitaet: 1.1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Dysprosium",
        kurzsymbol: "Dy",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Dysprosium",
        flammenfarbe: undefined,
        zweitname: "Disprosium",
        protonen: 66,
        neutronen: 97,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.00001901,
        prozentsatzAnDerErdhuelle: 0.00042,
        atommasse: 162.5001,
        ionisierungsenergie: 5.9389,
        dichte: 8.559,
        schmelzpunkt: 1412,
        siedepunkt: 2562,
        elektronegativitaet: 1.22,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Holmium",
        kurzsymbol: "Ho",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Holmium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 67,
        neutronen: 98,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.00001874,
        prozentsatzAnDerErdhuelle: 0.0001,
        atommasse: 164.93032,
        ionisierungsenergie: 6.0215,
        dichte: 8.78,
        schmelzpunkt: 1474,
        siedepunkt: 2695,
        elektronegativitaet: 1.23,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Erbium",
        kurzsymbol: "Er",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Erbium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 68,
        neutronen: 99,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.00001846,
        prozentsatzAnDerErdhuelle: 0.0002,
        atommasse: 167.2593,
        ionisierungsenergie: 6.1077,
        dichte: 9.045,
        schmelzpunkt: 1497,
        siedepunkt: 2900,
        elektronegativitaet: 1.24,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Thulium",
        kurzsymbol: "Tm",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery gray",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Thulium",
        flammenfarbe: undefined,
        zweitname: "Tulium",
        protonen: 69,
        neutronen: 100,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: 1,
        volumen: 0.0000191,
        prozentsatzAnDerErdhuelle: 0.00002,
        atommasse: 168.93421,
        ionisierungsenergie: 6.1843,
        dichte: 9.318,
        schmelzpunkt: 1545,
        siedepunkt: 1974,
        elektronegativitaet: 1.25,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Ytterbium",
        kurzsymbol: "Yb",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Ytterbium",
        flammenfarbe: undefined,
        zweitname: "Itterbium",
        protonen: 70,
        neutronen: 103,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.00002484,
        prozentsatzAnDerErdhuelle: 0.0003,
        atommasse: 173.0451,
        ionisierungsenergie: 6.2542,
        dichte: 6.973,
        schmelzpunkt: 819,
        siedepunkt: 1194,
        elektronegativitaet: 1.06,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Lutetium",
        kurzsymbol: "Lu",
        unterkategorie: "Lanthanoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Lutetium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 71,
        neutronen: 104,
        lost: 2,
        hauptgruppe: 20,
        periode: 6,
        haerte: undefined,
        volumen: 0.00001778,
        prozentsatzAnDerErdhuelle: 0.00007,
        atommasse: 174.967,
        ionisierungsenergie: 5.4259,
        dichte: 9.84,
        schmelzpunkt: 1663,
        siedepunkt: 3395,
        elektronegativitaet: 1,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Hafnium",
        kurzsymbol: "Hf",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "steelgrey",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Hafnium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 72,
        neutronen: 106,
        lost: 2,
        hauptgruppe: 4,
        periode: 6,
        haerte: 5.5,
        volumen: 0.00001344,
        prozentsatzAnDerErdhuelle: 0.0004,
        atommasse: 178.492,
        ionisierungsenergie: 6.8251,
        dichte: 13.28,
        schmelzpunkt: 2227,
        siedepunkt: 4602,
        elektronegativitaet: 1.3,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Tantalum",
        kurzsymbol: "Ta",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "gray",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Tantalum",
        flammenfarbe: undefined,
        zweitname: "Tantalum",
        protonen: 73,
        neutronen: 108,
        lost: 2,
        hauptgruppe: 5,
        periode: 6,
        haerte: 6.5,
        volumen: 0.00001085,
        prozentsatzAnDerErdhuelle: 0.0008,
        atommasse: 180.94788,
        ionisierungsenergie: 7.5496,
        dichte: 16.65,
        schmelzpunkt: 2996,
        siedepunkt: 5425,
        elektronegativitaet: 1.5,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Tungsten",
        kurzsymbol: "W",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "grayish white, shiny",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Tungsten",
        flammenfarbe: undefined,
        zweitname: "Wolframium",
        protonen: 74,
        neutronen: 110,
        lost: 2,
        hauptgruppe: 6,
        periode: 6,
        haerte: 7.5,
        volumen: 0.00000947,
        prozentsatzAnDerErdhuelle: 0.006,
        atommasse: 183.841,
        ionisierungsenergie: 7.864,
        dichte: 19.3,
        schmelzpunkt: 3410,
        siedepunkt: 5660,
        elektronegativitaet: 1.7,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Rhenium",
        kurzsymbol: "Re",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "grayish white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Rhenium",
        flammenfarbe: undefined,
        zweitname: "Renium",
        protonen: 75,
        neutronen: 111,
        lost: 2,
        hauptgruppe: 7,
        periode: 6,
        haerte: 7,
        volumen: 0.00000886,
        prozentsatzAnDerErdhuelle: 0.0000001,
        atommasse: 186.2071,
        ionisierungsenergie: 7.8335,
        dichte: 21.02,
        schmelzpunkt: 3180,
        siedepunkt: 5627,
        elektronegativitaet: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Osmium",
        kurzsymbol: "Os",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "bluish gray",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Osmium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 76,
        neutronen: 114,
        lost: 2,
        hauptgruppe: 8,
        periode: 6,
        haerte: 7,
        volumen: 0.00000842,
        prozentsatzAnDerErdhuelle: 0.000001,
        atommasse: 190.233,
        ionisierungsenergie: 8.4382,
        dichte: 22.61,
        schmelzpunkt: 3045,
        siedepunkt: 5027,
        elektronegativitaet: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Iridium",
        kurzsymbol: "Ir",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Iridium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 77,
        neutronen: 115,
        lost: 2,
        hauptgruppe: 9,
        periode: 6,
        haerte: 6.5,
        volumen: 0.00000852,
        prozentsatzAnDerErdhuelle: 0.0000001,
        atommasse: 192.2173,
        ionisierungsenergie: 8.967,
        dichte: 22.67,
        schmelzpunkt: 2410,
        siedepunkt: 4130,
        elektronegativitaet: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Platinum",
        kurzsymbol: "Pt",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "gray-white",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Platinum",
        flammenfarbe: undefined,
        zweitname: "Platinum",
        protonen: 78,
        neutronen: 117,
        lost: 1,
        hauptgruppe: 10,
        periode: 6,
        haerte: 3.5,
        volumen: 0.00000909,
        prozentsatzAnDerErdhuelle: 0.0000005,
        atommasse: 195.078,
        ionisierungsenergie: 8.9588,
        dichte: 21.45,
        schmelzpunkt: 1772,
        siedepunkt: 3827,
        elektronegativitaet: 2.2,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Gold",
        kurzsymbol: "Au",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "gold, oh really? Google it if you don't believe me ;-)",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Gold",
        flammenfarbe: undefined,
        zweitname: "Aurum",
        protonen: 79,
        neutronen: 118,
        lost: 1,
        hauptgruppe: 11,
        periode: 6,
        haerte: 2.75,
        volumen: 0.00001021,
        prozentsatzAnDerErdhuelle: 0.0000005,
        atommasse: 196.966569,
        ionisierungsenergie: 9.2255,
        dichte: 19.32,
        schmelzpunkt: 1064,
        siedepunkt: 2807,
        elektronegativitaet: 2.4,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Mercury",
        kurzsymbol: "Hg",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "liquid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Mercury_(element)",
        flammenfarbe: undefined,
        zweitname: "Hydrargyrum",
        protonen: 80,
        neutronen: 121,
        lost: 2,
        hauptgruppe: 12,
        periode: 6,
        haerte: undefined,
        volumen: 0.00001409,
        prozentsatzAnDerErdhuelle: 0.00004,
        atommasse: 200.5923,
        ionisierungsenergie: 10.4375,
        dichte: 14.26,
        schmelzpunkt: -38.84,
        siedepunkt: 356.6,
        elektronegativitaet: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Thallium",
        kurzsymbol: "Tl",
        unterkategorie: undefined,
        oberkategorie: "Metal",
        aussehen: "",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Thallium",
        flammenfarbe: undefined,
        zweitname: "Tallium",
        protonen: 81,
        neutronen: 123,
        lost: 3,
        hauptgruppe: 13,
        periode: 6,
        haerte: 1.2,
        volumen: 0.00001722,
        prozentsatzAnDerErdhuelle: 0.00003,
        atommasse: 204.383,
        ionisierungsenergie: 6.1082,
        dichte: 11.85,
        schmelzpunkt: 303.5,
        siedepunkt: 1457,
        elektronegativitaet: 1.8,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Lead",
        kurzsymbol: "Pb",
        unterkategorie: undefined,
        oberkategorie: "Metal",
        aussehen: "bluish white",
        aggregatszustand: "solid",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Lead",
        flammenfarbe: undefined,
        zweitname: "Plumbum",
        protonen: 82,
        neutronen: 125,
        lost: 4,
        hauptgruppe: 14,
        periode: 6,
        haerte: 1.5,
        volumen: 0.00001826,
        prozentsatzAnDerErdhuelle: 0.002,
        atommasse: 207.21,
        ionisierungsenergie: 7.4167,
        dichte: 11.342,
        schmelzpunkt: 327.5,
        siedepunkt: 1740,
        elektronegativitaet: 1.8,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Bismuth",
        kurzsymbol: "Bi",
        unterkategorie: undefined,
        oberkategorie: "Metal",
        aussehen: "shiny silver white",
        aggregatszustand: "solid",
        struktur: "trigonal",
        wikipedia: "https://en.wikipedia.org/wiki/Bismuth",
        flammenfarbe: undefined,
        zweitname: "Bismuthum",
        protonen: 83,
        neutronen: 126,
        lost: 5,
        hauptgruppe: 15,
        periode: 6,
        haerte: 2.25,
        volumen: 0.00002131,
        prozentsatzAnDerErdhuelle: 0.00002,
        atommasse: 208.9804,
        ionisierungsenergie: 7.2855,
        dichte: 9.78,
        schmelzpunkt: 271.3,
        siedepunkt: 1560,
        elektronegativitaet: 1.9,
        synthetischHergestellt: false,
        radioaktiv: false,
    },
    {
        name: "Polonium",
        kurzsymbol: "Po",
        unterkategorie: undefined,
        oberkategorie: "Metal",
        aussehen: "silvery",
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Polonium",
        flammenfarbe: undefined,
        zweitname: "Polonium",
        protonen: 84,
        neutronen: 126,
        lost: 6,
        hauptgruppe: 16,
        periode: 6,
        haerte: undefined,
        volumen: 0.00002297,
        prozentsatzAnDerErdhuelle: 0.00000000000002,
        atommasse: 208.982416,
        ionisierungsenergie: 8.414,
        dichte: 9.196,
        schmelzpunkt: 254,
        siedepunkt: 962,
        elektronegativitaet: 2,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Astatine",
        kurzsymbol: "At",
        unterkategorie: "Halogen",
        oberkategorie: "Nonmetal",
        aussehen: "metallic",
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Astatine",
        flammenfarbe: undefined,
        zweitname: "Astatium",
        protonen: 85,
        neutronen: 125,
        lost: 7,
        hauptgruppe: 17,
        periode: 6,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: 0.000000000000000000000003,
        atommasse: 209.987131,
        ionisierungsenergie: 7.5,
        dichte: undefined,
        schmelzpunkt: 302,
        siedepunkt: 337,
        elektronegativitaet: 2.2,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Radon",
        kurzsymbol: "Rn",
        unterkategorie: "Noble Gas",
        oberkategorie: "Nonmetal",
        aussehen: "colorless",
        aggregatszustand: "gas",
        struktur: "cubic close packed",
        wikipedia: "https://en.wikipedia.org/wiki/Radon",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 86,
        neutronen: 136,
        lost: 8,
        hauptgruppe: 18,
        periode: 6,
        haerte: undefined,
        volumen: 0.0000505,
        prozentsatzAnDerErdhuelle: 0.0000000000000006,
        atommasse: 222.0175705,
        ionisierungsenergie: 10.7485,
        dichte: 5.06,
        schmelzpunkt: -71,
        siedepunkt: -61.8,
        elektronegativitaet: undefined,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Francium",
        kurzsymbol: "Fr",
        unterkategorie: "Alkali Metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Francium",
        flammenfarbe: undefined,
        zweitname: "Frankium",
        protonen: 87,
        neutronen: 136,
        lost: 1,
        hauptgruppe: 1,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: 0.000000000000000000001,
        atommasse: 223.0197307,
        ionisierungsenergie: 4.0727,
        dichte: 2.5,
        schmelzpunkt: 27,
        siedepunkt: 677,
        elektronegativitaet: 0.7,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Radium",
        kurzsymbol: "Ra",
        unterkategorie: "Alkaline earth metal",
        oberkategorie: "Metal",
        aussehen: "silvery-white-metallic",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Radium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 88,
        neutronen: 138,
        lost: 2,
        hauptgruppe: 2,
        periode: 7,
        haerte: undefined,
        volumen: 0.00004109,
        prozentsatzAnDerErdhuelle: 0.0000000001,
        atommasse: 226.0254026,
        ionisierungsenergie: 5.2784,
        dichte: 5.5,
        schmelzpunkt: 700,
        siedepunkt: 1140,
        elektronegativitaet: 0.9,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Actinium",
        kurzsymbol: "Ac",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: "silvery",
        aggregatszustand: "solid",
        struktur: "cubic space-centered",
        wikipedia: "https://en.wikipedia.org/wiki/Actinium",
        flammenfarbe: undefined,
        zweitname: "Aktinium",
        protonen: 89,
        neutronen: 138,
        lost: 2,
        hauptgruppe: 3,
        periode: 7,
        haerte: undefined,
        volumen: 0.00002255,
        prozentsatzAnDerErdhuelle: 0.0000064,
        atommasse: 227.027747,
        ionisierungsenergie: 5.17,
        dichte: 10.07,
        schmelzpunkt: 1050,
        siedepunkt: 3200,
        elektronegativitaet: 1.1,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Thorium",
        kurzsymbol: "Th",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: "silvery white",
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Thorium",
        flammenfarbe: undefined,
        zweitname: "Torium",
        protonen: 90,
        neutronen: 142,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 3,
        volumen: 0.0000198,
        prozentsatzAnDerErdhuelle: 0.001,
        atommasse: 232.03806,
        ionisierungsenergie: 6.3067,
        dichte: 11.724,
        schmelzpunkt: 1750,
        siedepunkt: 4790,
        elektronegativitaet: 1.3,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Protactinium",
        kurzsymbol: "Pa",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: "hell, silvery, metallic shiny",
        aggregatszustand: "solid",
        struktur: "tetragonal",
        wikipedia: "https://en.wikipedia.org/wiki/Protactinium",
        flammenfarbe: undefined,
        zweitname: "Protaktinium",
        protonen: 91,
        neutronen: 140,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: 0.00001518,
        prozentsatzAnDerErdhuelle: 0.00000000009,
        atommasse: 231.03588,
        ionisierungsenergie: 5.89,
        dichte: 15.37,
        schmelzpunkt: 1600,
        siedepunkt: 4027,
        elektronegativitaet: 1.5,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Uranium",
        kurzsymbol: "U",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: "silver white",
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Uranium",
        flammenfarbe: undefined,
        zweitname: "Uranium",
        protonen: 92,
        neutronen: 146,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: 2.75,
        volumen: 0.00001249,
        prozentsatzAnDerErdhuelle: 0.0003,
        atommasse: 238.02891,
        ionisierungsenergie: 6.1941,
        dichte: 19.16,
        schmelzpunkt: 1132,
        siedepunkt: 3818,
        elektronegativitaet: 1.7,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Neptunium",
        kurzsymbol: "Np",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: "silvery",
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Neptunium",
        flammenfarbe: undefined,
        zweitname: "Nebtunium",
        protonen: 93,
        neutronen: 144,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: 0.00001159,
        prozentsatzAnDerErdhuelle: 0.00000000000000004,
        atommasse: 237.0481673,
        ionisierungsenergie: 6.2657,
        dichte: 20.45,
        schmelzpunkt: 640,
        siedepunkt: 3902,
        elektronegativitaet: 1.3,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Plutonium",
        kurzsymbol: "Pu",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: "silveryes metal",
        aggregatszustand: "solid",
        struktur: "monoclinic",
        wikipedia: "https://en.wikipedia.org/wiki/Plutonium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 94,
        neutronen: 150,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: 0.00001229,
        prozentsatzAnDerErdhuelle: 0.0000000000000000002,
        atommasse: 244.064198,
        ionisierungsenergie: 6.026,
        dichte: 19.816,
        schmelzpunkt: 641,
        siedepunkt: 3332,
        elektronegativitaet: 1.3,
        synthetischHergestellt: false,
        radioaktiv: true,
    },
    {
        name: "Americium",
        kurzsymbol: "Am",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: "silvery white metal",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Americium",
        flammenfarbe: undefined,
        zweitname: "Amerikium",
        protonen: 95,
        neutronen: 148,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: 0.00001778,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 243.0613727,
        ionisierungsenergie: 5.9738,
        dichte: 13.67,
        schmelzpunkt: 994,
        siedepunkt: 2607,
        elektronegativitaet: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Curium",
        kurzsymbol: "Cm",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: "silvery white metal",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Curium",
        flammenfarbe: undefined,
        zweitname: "Kurium",
        protonen: 96,
        neutronen: 151,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: 0.00001805,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 247.070347,
        ionisierungsenergie: 5.9914,
        dichte: 13.52,
        schmelzpunkt: 1340,
        siedepunkt: 3100,
        elektronegativitaet: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Berkelium",
        kurzsymbol: "Bk",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: "silver white",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Berkelium",
        flammenfarbe: undefined,
        zweitname: "Bercelium",
        protonen: 97,
        neutronen: 150,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: 0.00001684,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 247.070299,
        ionisierungsenergie: 6.1979,
        dichte: 14.78,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Californium",
        kurzsymbol: "Cf",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: "silvery",
        aggregatszustand: "solid",
        struktur: "hexagonal",
        wikipedia: "https://en.wikipedia.org/wiki/Californium",
        flammenfarbe: undefined,
        zweitname: "Kalifornium",
        protonen: 98,
        neutronen: 153,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: 0.0000165,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 251.07958,
        ionisierungsenergie: 6.2817,
        dichte: 15.1,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Einsteinium",
        kurzsymbol: "Es",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: "cubic",
        wikipedia: "https://en.wikipedia.org/wiki/Einsteinium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 99,
        neutronen: 153,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: 0.00000884,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 252.08297,
        ionisierungsenergie: 6.42,
        dichte: 8.84,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Fermium",
        kurzsymbol: "Fm",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Fermium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 100,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 257.095099,
        ionisierungsenergie: 6.5,
        dichte: undefined,
        schmelzpunkt: 852,
        siedepunkt: undefined,
        elektronegativitaet: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Mendelevium",
        kurzsymbol: "Md",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Mendelevium",
        flammenfarbe: undefined,
        zweitname: "Mendelefium",
        protonen: 101,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 258.098425,
        ionisierungsenergie: 6.58,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Nobelium",
        kurzsymbol: "No",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Nobelium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 102,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 259.10102,
        ionisierungsenergie: 6.65,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: 1.2,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Lawrencium",
        kurzsymbol: "Lr",
        unterkategorie: "Actinoid",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Lawrencium",
        flammenfarbe: undefined,
        zweitname: "Lawrenkium",
        protonen: 103,
        neutronen: 163,
        lost: 3,
        hauptgruppe: 21,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 262.10969,
        ionisierungsenergie: 4.9,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Rutherfordium",
        kurzsymbol: "Rf",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Rutherfordium",
        flammenfarbe: undefined,
        zweitname: "Ruterfordium",
        protonen: 104,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 4,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 261.10875,
        ionisierungsenergie: 6,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Dubnium",
        kurzsymbol: "Db",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Dubnium",
        flammenfarbe: undefined,
        zweitname: "Dupnium",
        protonen: 105,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 5,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 262.11415,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Seaborgium",
        kurzsymbol: "Sg",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: undefined,
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Seaborgium",
        flammenfarbe: undefined,
        zweitname: "Unnilhexium",
        protonen: 106,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 6,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 266.12193,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Bohrium",
        kurzsymbol: "Bh",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Bohrium",
        flammenfarbe: undefined,
        zweitname: "Borium",
        protonen: 107,
        neutronen: 155,
        lost: 2,
        hauptgruppe: 7,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 264.12473,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Hassium",
        kurzsymbol: "Hs",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Hassium",
        flammenfarbe: undefined,
        zweitname: "Unniloctium",
        protonen: 108,
        neutronen: 157,
        lost: 2,
        hauptgruppe: 8,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 269,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Meitnerium",
        kurzsymbol: "Mt",
        unterkategorie: "Probably a transition metal",
        oberkategorie: "Metal",
        aussehen: "probably silver gray",
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Meitnerium",
        flammenfarbe: undefined,
        zweitname: "Unnilennium",
        protonen: 109,
        neutronen: 159,
        lost: 2,
        hauptgruppe: 9,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 268,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Darmstadtium",
        kurzsymbol: "Ds",
        unterkategorie: "Probably a transition metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Darmstadtium",
        flammenfarbe: undefined,
        zweitname: undefined,
        protonen: 110,
        neutronen: 171,
        lost: 1,
        hauptgruppe: 10,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 281,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Roentgenium",
        kurzsymbol: "Rg",
        unterkategorie: "Probably a transition metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Roentgenium",
        flammenfarbe: undefined,
        zweitname: "Röntgenium",
        protonen: 111,
        neutronen: 169,
        lost: 1,
        hauptgruppe: 11,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 280,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Copernicium",
        kurzsymbol: "Cn",
        unterkategorie: "Transition metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Copernicium",
        flammenfarbe: undefined,
        zweitname: "Copernikium",
        protonen: 112,
        neutronen: 165,
        lost: 2,
        hauptgruppe: 12,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 277,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Nihonium",
        kurzsymbol: "Nh",
        unterkategorie: "Probably a metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Nihonium",
        flammenfarbe: undefined,
        zweitname: "Ununtrium",
        protonen: 113,
        neutronen: 171,
        lost: 3,
        hauptgruppe: 13,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 284,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Flerovium",
        kurzsymbol: "Fl",
        unterkategorie: "Probably a metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Flerovium",
        flammenfarbe: undefined,
        zweitname: "Flerofium",
        protonen: 114,
        neutronen: 175,
        lost: 4,
        hauptgruppe: 14,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 289,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Moscovium",
        kurzsymbol: "Mc",
        unterkategorie: "Probably a metal",
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Moscovium",
        flammenfarbe: undefined,
        zweitname: "Ununpentium",
        protonen: 115,
        neutronen: 173,
        lost: 5,
        hauptgruppe: 15,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 288,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Livermorium",
        kurzsymbol: "Lv",
        unterkategorie: undefined,
        oberkategorie: "Metal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Livermorium",
        flammenfarbe: undefined,
        zweitname: "Lifermorium",
        protonen: 116,
        neutronen: 177,
        lost: 6,
        hauptgruppe: 16,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 293,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Tennessine",
        kurzsymbol: "Ts",
        unterkategorie: "Probably a halogen",
        oberkategorie: "Nonmetal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Tennessine",
        flammenfarbe: undefined,
        zweitname: "Ununseptium",
        protonen: 117,
        neutronen: 175,
        lost: 7,
        hauptgruppe: 17,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 292,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
    {
        name: "Oganesson",
        kurzsymbol: "Og",
        unterkategorie: "Probably a Noble Gas",
        oberkategorie: "Nonmetal",
        aussehen: undefined,
        aggregatszustand: "solid",
        struktur: undefined,
        wikipedia: "https://en.wikipedia.org/wiki/Oganesson",
        flammenfarbe: undefined,
        zweitname: "Ununoctium",
        protonen: 118,
        neutronen: 176,
        lost: 8,
        hauptgruppe: 18,
        periode: 7,
        haerte: undefined,
        volumen: undefined,
        prozentsatzAnDerErdhuelle: undefined,
        atommasse: 294,
        ionisierungsenergie: undefined,
        dichte: undefined,
        schmelzpunkt: undefined,
        siedepunkt: undefined,
        elektronegativitaet: undefined,
        synthetischHergestellt: true,
        radioaktiv: true,
    },
]