package oldStuff;

import javax.swing.JOptionPane;


public class ChemieElementSwitch {

	public static int SwitchEins(String ersteNutzerEingabe) {

		int b = 999;
		switch (ersteNutzerEingabe) {
			
			case "wa" :
			case "was" :
			case "wass" :
			case "wasse" :
			case "wasser" :
			case "wassers" :
			case "wasserst" :
			case "wassersto" :
			case "wasserstof" :
			case "wasserstoff" :
			case "hy" :
			case "hyd" :
			case "hydr" :
			case "hydro" :
			case "hydrog" :
			case "hydroge" :
			case "hydrogen" :
			case "hydrogeni" :
			case "hydrogeniu" :
			case "hydrogenium" :	
			case "h" :
			case "H" :
			case "Wa" :
			case "Was" :
			case "Wass" :
			case "Wasse" :
			case "Wasser" :
			case "Wassers" :
			case "Wasserst" :
			case "Wassersto" :
			case "Wasserstof" :
			case "Wasserstoff" :
			case "Hy" :
			case "Hyd" :
			case "Hydr" :
			case "Hydro" :
			case "Hydrog" :
			case "Hydroge" :
			case "Hydrogen" :
			case "Hydrogeni" :
			case "Hydrogeniu" :
			case "Hydrogenium" :
			case "WA" :
			case "WAS" :
			case "WASS" :
			case "WASSE" :
			case "WASSER" :
			case "WASSERS" :
			case "WASSERST" :
			case "WASSERSTO" :
			case "WASSERSTOF" :
			case "WASSERSTOFF" :
			case "HY" :
			case "HYD" :
			case "HYDR" :
			case "HYDRO" :
			case "HYDROG" :
			case "HYDROGE" :
			case "HYDROGEN" :
			case "HYDROGENI" :
			case "HYDROGENIU" :
			case "HYDROGENIUM" :{b=0;
			break;
			}
			case "hel" :
			case "heli" :
			case "heliu" :
			case "helium" :
			case "Hel" :
			case "Heli" :
			case "Heliu" :
			case "Helium" :
			case "HEL" :
			case "HELI" :
			case "HELIU" :
			case "HELIUM" :
			case "he" :
			case "He" :
			case "HE" : {b=1;	
			break;
			}
			case "lith" :
			case "lithi" :
			case "lithiu" :
			case "lithium" :
			case "lit" :
			case "liti" :
			case "litiu" :
			case "litium" :
			case "Lith" :
			case "Lithi" :
			case "Lithiu" :
			case "Lithium" :
			case "LIT" :
			case "LITH" :
			case "LITHI" :
			case "LITHIU" :
			case "LITHIUM" :
			case "LITI" :
			case "LITIU" :
			case "LITIUM" :
			case "L" :
			case "Lit" :
			case "Liti" :
			case "Litiu" :
			case "Litium" :
			case "li" :
			case "Li" :
			case "LI" :{b=2;
			break;
			}
			case "bery" :
			case "beryl" :
			case "beryll" :
			case "berylli" :
			case "berylliu" :
			case "beryllium" :
			case "ber" :
			case "beri" :
			case "beril" :
			case "berill" :
			case "berilli" :
			case "berilliu" :
			case "berillium" :
			case "Bery" :
			case "Beryl" :
			case "Beryll" :
			case "Berylli" :
			case "Berylliu" :
			case "Beryllium" :
			case "Ber" :
			case "Beri" :
			case "Beril" :
			case "Berill" :
			case "Berilli" :
			case "Berilliu" :
			case "Berillium" :
			case "BER" :
			case "BERY" :
			case "BERYL" :
			case "BERYLL" :
			case "BERYLLI" :
			case "BERYLLIU" :
			case "BERYLLIUM" :
			case "BERI" :
			case "BERIL" :
			case "BERILL" :
			case "BERILLI" :
			case "BERILLIU" :
			case "BERILLIUM" :
			case "be" :
			case "Be" :
			case "BE" : {b=3;
			break;
			}
			case "bo" :
			case "bor" :
			case "boru" :
			case "borum" :
			case "Bo" :
			case "Bor" :
			case "Boru" :
			case "Borum" :
			case "BO" :
			case "BOR" :
			case "BORU" :
			case "BORUM" :
			case "b" :
			case "B" : {b=4;
			break;
			}
			case "ko" :
			case "koh" :
			case "kohl" :
			case "kohle" :
			case "kohlen" :
			case "kohlens" :
			case "kohlenst" :
			case "kohlensto" :
			case "kohlenstof" :
			case "kohlenstoff" :
			case "car" :
			case "carb" :
			case "carbo" :
			case "carbon" :
			case "carbone" :
			case "carboneu" :
			case "carboneum" :
			case "Ko" :
			case "Koh" :
			case "Kohl" :
			case "Kohle" :
			case "Kohlen" :
			case "Kohlens" :
			case "Kohlenst" :
			case "Kohlensto" :
			case "Kohlenstof" :
			case "Kohlenstoff" :
			case "Car" :
			case "Carb" :
			case "Carbo" :
			case "Carbon" :
			case "Carbone" :
			case "Carboneu" :
			case "Carboneum" :
			case "KO" :
			case "KOH" :
			case "KOHL" :
			case "KOHLE" :
			case "KOHLEN" :
			case "KOHLENS" :
			case "KOHLENST" :
			case "KOHLENSTO" :
			case "KOHLENSTOF" :
			case "KOHLENSTOFF" :
			case "CAR" :
			case "CARB" :
			case "CARBO" :
			case "CARBON" :
			case "CARBONE" :
			case "CARBONEU" :
			case "CARBONEUM" :
			case "c" :
			case "C" :{b=5;
			break;
			}
			case "st" :
			case "sti" :
			case "stic" :
			case "stick" :
			case "sticks" :
			case "stickst" :
			case "sticksto" :
			case "stickstof" :
			case "stickstoff" :
			case "nit" :
			case "nitr" :
			case "nitro" :
			case "nitrog" :
			case "nitroge" :
			case "nitrogen" :
			case "nitrogeni" :
			case "nitrogeniu" :
			case "nitrogenium" :
			case "St" :
			case "Sti" :
			case "Stic" :
			case "Stick" :
			case "Sticks" :
			case "Stickst" :
			case "Sticksto" :
			case "Stickstof" :
			case "Stickstoff" :
			case "Nit" :
			case "Nitr" :
			case "Nitro" :
			case "Nitrog" :
			case "Nitroge" :
			case "Nitrogen" :
			case "Nitrogeni" :
			case "Nitrogeniu" :
			case "Nitrogenium" :
			case "ST" :
			case "STI" :
			case "STIC" :
			case "STICK" :
			case "STICKS" :
			case "STICKST" :
			case "STICKSTO" :
			case "STICKSTOF" :
			case "STICKSTOFF" :
			case "NIT" :
			case "NITR" :
			case "NITRO" :
			case "NITROG" :
			case "NITROGE" :
			case "NITROGEN" :
			case "NITROGENI" :
			case "NITROGENIU" :
			case "NITROGENIUM" :
			case "n" :
			case "N" :{b=6;
			break;
			}
			case "sa" :
			case "sau" :
			case "saue" :
			case "sauer" :
			case "sauers" :
			case "sauerst" :
			case "sauersto" :
			case "sauerstof" :
			case "sauerstoff" :
			case "ox" :
			case "oxy" :
			case "oxyg" :
			case "oxyge" :
			case "oxygen" :
			case "oxygeni" :
			case "oxygeniu" :
			case "oxygenium" :
			case "Sa" :
			case "Sau" :
			case "Saue" :
			case "Sauer" :
			case "Sauers" :
			case "Sauerst" :
			case "Sauersto" :
			case "Sauerstof" :
			case "Sauerstoff" :
			case "Ox" :
			case "Oxy" :
			case "Oxyg" :
			case "Oxyge" :
			case "Oxygen" :
			case "Oxygeni" :
			case "Oxygeniu" :
			case "Oxygenium" :
			case "SA" :
			case "SAU" :
			case "SAUE" :
			case "SAUER" :
			case "SAUERS" :
			case "SAUERST" :
			case "SAUERSTO" :
			case "SAUERSTOF" :
			case "SAUERSTOFF" :
			case "OX" :
			case "OXY" :
			case "OXYG" :
			case "OXYGE" :
			case "OXYGEN" :
			case "OXYGENI" :
			case "OXYGENIU" :
			case "OXYGENIUM" :
			case "o" :
			case "O" :{b=7;
			break;
			}
			case "flu" :
			case "fluo" :
			case "fluor" :
			case "fluoru" :
			case "fluorum" :
			case "Flu" :
			case "Fluo" :
			case "Fluor" :
			case "Fluoru" :
			case "Fluorum" :
			case "FLUOR" :
			case "FLU" :
			case "FLUO" :
			case "FLUORU" :
			case "FLUORUM" :
			case "f" :
			case "F" :{b=8;
			break;
			}
			case "neo" :
			case "neon" :
			case "Neo" :
			case "Neon" :
			case "NEO" :
			case "NEON" :
			case "ne" :
			case "Ne" :
			case "NE" :{b=9;
			break;
			}
			case "nat" :
			case "natr" :
			case "natri" :
			case "natriu" :
			case "natrium" :
			case "Nat" :
			case "Natr" :
			case "Natri" :
			case "Natriu" :
			case "Natrium" :
			case "NAT" :
			case "NATR" :
			case "NATRI" :
			case "NATRIU" :
			case "NATRIUM" :
			case "na" :
			case "Na" :
			case "NA" : {b=10;
			break;
			}
			case "ma" :
			case "mag" :
			case "magn" :
			case "magne" :
			case "magnes" :
			case "magnesi" :
			case "magnesiu" :
			case "magnesium" :
			case "Ma" :
			case "Mag" :
			case "Magn" :
			case "Magne" :
			case "Magnes" :
			case "Magnesi" :
			case "Magnesiu" :
			case "Magnesium" :
			case "MA" :
			case "MAG" :
			case "MAGN" :
			case "MAGNE" :
			case "MAGNES" :
			case "MAGNESI" :
			case "MAGNESIU" :
			case "MAGNESIUM" :
			case "mg" :
			case "Mg" :
			case "MG" :{b=11;
			break;
			}
			case "a" :
			case "alu" :
			case "alum" :
			case "alumi" :
			case "alumin" :
			case "alumini" :
			case "aluminiu" :
			case "aluminium" :
			case "Alu" :
			case "Alum" :
			case "Alumi" :
			case "Alumin" :
			case "Alumini" :
			case "Aluminiu" :
			case "Aluminium" :
			case "ALU" :
			case "ALUM" :
			case "ALUMI" :
			case "ALUMIN" :
			case "ALUMINI" :
			case "ALUMINIU" :
			case "ALUMINIUM" :
			case "al" :
			case "Al" :
			case "AL" :{b=12;
			break;
			}
			case "sili" :
			case "silic" :
			case "silici" :
			case "siliciu" :
			case "silicium" :
			case "sil" :
			case "siliz" :
			case "silizi" :
			case "siliziu" :
			case "silizium" :
			case "Sil" :
			case "Sili" :
			case "Siliz" :
			case "Silizi" :
			case "Siliziu" :
			case "Silizium" :
			case "Silic" :
			case "Silici" :
			case "Siliciu" :
			case "Silicium" :
			case "SILIZ" :
			case "SILIZI" :
			case "SILIZIU" :
			case "SILIZIUM" :
			case "SIL" :
			case "SILI" :
			case "SILIC" :
			case "SILICI" :
			case "SILICIU" :
			case "SILICIUM" :
			case "si" :
			case "Si" :
			case "SI" :{b=13;
			break;
			}
			case "ph" :
			case "pho" :
			case "phos" :
			case "phosp" :
			case "phosph" :
			case "phospho" :
			case "phosphor" :
			case "phosf" :
			case "phosfo" :
			case "phosfor" :
			case "Ph" :
			case "Pho" :
			case "Phos" :
			case "Phosp" :
			case "Phosph" :
			case "Phospho" :
			case "Phosphor" :
			case "PH" :
			case "PHO" :
			case "PHOS" :
			case "PHOSP" :
			case "PHOSPH" :
			case "PHOSPHO" :
			case "PHOSPHOR" :
			case "Phosf" :
			case "Phosfo" :
			case "Phosfor" :
			case "PHOSF" :
			case "PHOSFO" :
			case "PHOSFOR" :
			case "p" :
			case "P" :{b=14;
			break;
			}
			case "sch" :
			case "schw" :
			case "schwe" :
			case "schwef" :
			case "schwefe" :
			case "schwefel" :
			case "Sch" :
			case "Schw" :
			case "Schwe" :
			case "Schwef" :
			case "Schwefe" :
			case "Schwefel" :
			case "SCH" :
			case "SCHW" :
			case "SCHWE" :
			case "SCHWEF" :
			case "SCHWEFE" :
			case "SCHWEFEL" :
			case "s" :
			case "S" :{b=15;
			break;
			}
			case "chlor" :
			case "CHLOR" :
			case "chlorum" :
			case "Chlorum" :
			case "CHLORUM" :
			case "ch" :
			case "chl" :
			case "chlo" :
			case "chloru" :
			case "Ch" :
			case "Chl" :
			case "Chlo" :
			case "Chlor" :
			case "Chloru" :
			case "CH" :
			case "CHLO" :
			case "CHL" :
			case "CHLORU" :
			case "cl" :
			case "Cl" :
			case "CL" :{b=16;
			break;
			}
			case "argon" :
			case "Argon" :
			case "ARGON" :
			case "arg" :
			case "argo" :
			case "A" :
			case "Arg" :
			case "Argo" :
			case "ARG" :
			case "ARGO" :
			case "ar" :
			case "Ar" :
			case "AR" :{b=17;
			break;
			}
			case "ka" :
			case "kal" :
			case "kali" :
			case "kaliu" :
			case "kalium" :
			case "Ka" :
			case "Kal" :
			case "Kali" :
			case "Kaliu" :
			case "Kalium" :
			case "KA" :
			case "KAL" :
			case "KALI" :
			case "KALIU" :
			case "KALIUM" :
			case "k" :
			case "K" :{b=18;
			break;
			}
			case "cal" :
			case "calc" :
			case "calci" :
			case "calciu" :
			case "calcium" :
			case "Cal" :
			case "Calc" :
			case "Calci" :
			case "Calciu" :
			case "Calcium" :
			case "CAL" :
			case "CALC" :
			case "CALCI" :
			case "CALCIU" :
			case "CALCIUM" :
			case "ca" :
			case "Ca" :
			case "CA" :{b=19;
			break;
			}
			case "sca" :
			case "scan" :
			case "scand" :
			case "scandi" :
			case "scandiu" :
			case "scandium" :
			case "Sca" :
			case "Scan" :
			case "Scand" :
			case "Scandi" :
			case "Scandiu" :
			case "Scandium" :
			case "SCA" :
			case "SCAN" :
			case "SCAND" :
			case "SCANDI" :
			case "SCANDIU" :
			case "SCANDIUM" :
			case "sc" :
			case "Sc" :
			case "SC" :{b=20;
			break;
			}
			case "titan" :
			case "Titan" :
			case "TITAN" :
			case "titanium" :
			case "TITANIUM" :
			case "t" :
			case "tit" :
			case "tita" :
			case "titani" :
			case "titaniu" :
			case "T" :
			case "Tit" :
			case "Tita" :
			case "Titani" :
			case "Titaniu" :
			case "Titanium" :
			case "TIT" :
			case "TITA" :
			case "TITANI" :
			case "TITANIU" :
			case "ti" :
			case "Ti" :
			case "TI" :{b=21;
			break;
			}
			case "va" :
			case "van" :
			case "vana" :
			case "vanad" :
			case "vanadi" :
			case "vanadiu" :
			case "vanadium" :
			case "Va" :
			case "Van" :
			case "Vana" :
			case "Vanad" :
			case "Vanadi" :
			case "Vanadiu" :
			case "Vanadium" :
			case "VA" :
			case "VAN" :
			case "VANA" :
			case "VANAD" :
			case "VANADI" :
			case "VANADIU" :
			case "VANADIUM" :
			case "v" :
			case "V" :{b=22;
			break;
			}
			case "chr" :
			case "chro" :
			case "chrom" :
			case "chromi" :
			case "chromiu" :
			case "chromium" :
			case "Chr" :
			case "Chro" :
			case "Chrom" :
			case "Chromi" :
			case "Chromiu" :
			case "Chromium" :
			case "CHR" :
			case "CHRO" :
			case "CHROM" :
			case "CHROMI" :
			case "CHROMIU" :
			case "CHROMIUM" :
			case "cr" :
			case "Cr" :
			case "CR" :{b=23;
			break;
			}
			case "m" :
			case "man" :
			case "mang" :
			case "manga" :
			case "mangan" :
			case "manganu" :
			case "manganum" :
			case "M" :
			case "Man" :
			case "Mang" :
			case "Manga" :
			case "Mangan" :
			case "Manganu" :
			case "Manganum" :
			case "MAN" :
			case "MANG" :
			case "MANGA" :
			case "MANGAN" :
			case "MANGANU" :
			case "MANGANUM" :
			case "mn" :
			case "Mn" :
			case "MN" :{b=24;
			break;
			}
			case "e" :
			case "ei" :
			case "eis" :
			case "eise" :
			case "eisen" :
			case "fer" :
			case "ferr" :
			case "ferru" :
			case "ferrum" :
			case "E" :
			case "Ei" :
			case "Eis" :
			case "Eise" :
			case "Eisen" :
			case "Fer" :
			case "Ferr" :
			case "Ferru" :
			case "Ferrum" :
			case "EI" :
			case "EIS" :
			case "EISE" :
			case "EISEN" :
			case "FER" :
			case "FERR" :
			case "FERRU" :
			case "FERRUM" :
			case "fe" :
			case "Fe" :
			case "FE" :{b=25;
			break;
			}
			case "cob" :
			case "coba" :
			case "cobal" :
			case "cobalt" :
			case "cobaltu" :
			case "cobaltum" :
			case "Cob" :
			case "Coba" :
			case "Cobal" :
			case "Cobalt" :
			case "Cobaltu" :
			case "Cobaltum" :
			case "co" :
			case "Co" :
			case "CO" :{b=26;
			break;
			}
			case "nic" :
			case "nick" :
			case "nicke" :
			case "nickel" :
			case "nicc" :
			case "nicco" :
			case "niccol" :
			case "niccolu" :
			case "niccolum" :
			case "Nic" :
			case "Nick" :
			case "Nicke" :
			case "Nickel" :
			case "Nicc" :
			case "Nicco" :
			case "Niccol" :
			case "Niccolu" :
			case "Niccolum" :
			case "NIC" :
			case "NICK" :
			case "NICKE" :
			case "NICKEL" :
			case "NICC" :
			case "NICCO" :
			case "NICCOL" :
			case "NICCOLU" :
			case "NICCOLUM" :
			case "ni" :
			case "Ni" :
			case "NI" :{b=27;
			break;
			}
			case "ku" :
			case "kup" :
			case "kupf" :
			case "kupfe" :
			case "kupfer" :
			case "cup" :
			case "cupr" :
			case "cupru" :
			case "cuprum" :
			case "Ku" :
			case "Kup" :
			case "Kupf" :
			case "Kupfe" :
			case "Kupfer" :
			case "Cup" :
			case "Cupr" :
			case "Cupru" :
			case "Cuprum" :
			case "KU" :
			case "KUP" :
			case "KUPF" :
			case "KUPFE" :
			case "KUPFER" :
			case "CUP" :
			case "CUPR" :
			case "CUPRU" :
			case "CUPRUM" :
			case "cu" :
			case "Cu" :
			case "CU" :{b=28;
			break;
			}
			case "z" :
			case "zi" :
			case "zin" :
			case "zink" :
			case "zinku" :
			case "zinkum" :
			case "zinc" :
			case "zincu" :
			case "zincum" :
			case "Z" :
			case "Zi" :
			case "Zin" :
			case "Zinc" :
			case "Zincu" :
			case "Zincum" :
			case "Zink" :
			case "Zinku" :
			case "Zinkum" :
			case "ZI" :
			case "ZIN" :
			case "ZINK" :
			case "ZINKU" :
			case "ZINKUM" :
			case "ZINC" :
			case "ZINCU" :
			case "ZINCUM" :
			case "zn" :
			case "Zn" :
			case "ZN" :{b=29;
			break;
			}
			case "g" :
			case "gal" :
			case "gall" :
			case "galli" :
			case "galliu" :
			case "gallium" :
			case "G" :
			case "Gal" :
			case "Gall" :
			case "Galli" :
			case "Galliu" :
			case "Gallium" :
			case "GAL" :
			case "GALL" :
			case "GALLI" :
			case "GALLIU" :
			case "GALLIUM" :
			case "ga" :
			case "Ga" :
			case "GA" :{b=30;
			break;
			}
			case "ger" :
			case "germ" :
			case "germa" :
			case "german" :
			case "germani" :
			case "germaniu" :
			case "germanium" :
			case "Ger" :
			case "Germ" :
			case "Germa" :
			case "German" :
			case "Germani" :
			case "Germaniu" :
			case "Germanium" :
			case "GER" :
			case "GERM" :
			case "GERMA" :
			case "GERMAN" :
			case "GERMANI" :
			case "GERMANIU" :
			case "GERMANIUM" :
			case "ge" :
			case "Ge" :
			case "GE" :{b=31;
			break;
			}
			case "ars" :
			case "arse" :
			case "arsen" :
			case "arseni" :
			case "arsenic" :
			case "arsenicu" :
			case "arsenicum" :
			case "Ars" :
			case "Arse" :
			case "Arsen" :
			case "Arseni" :
			case "Arsenic" :
			case "Arsenicu" :
			case "Arsenicum" :
			case "ARS" :
			case "ARSE" :
			case "ARSEN" :
			case "ARSENI" :
			case "ARSENIC" :
			case "ARSENICU" :
			case "ARSENICUM" :
			case "as" :
			case "As" :
			case "AS" :{b=32;
			break;
			}
			case "sel" :
			case "sele" :
			case "selen" :
			case "seleni" :
			case "seleniu" :
			case "selenium" :
			case "Sel" :
			case "Sele" :
			case "Selen" :
			case "Seleni" :
			case "Seleniu" :
			case "Selenium" :
			case "SEL" :
			case "SELE" :
			case "SELEN" :
			case "SELENI" :
			case "SELENIU" :
			case "SELENIUM" :
			case "se" :
			case "Se" :
			case "SE" :{b=33;
			break;
			}
			case "bro" :
			case "brom" :
			case "bromu" :
			case "bromum" :
			case "Bro" :
			case "Brom" :
			case "Bromu" :
			case "Bromum" :
			case "BRO" :
			case "BROM" :
			case "BROMU" :
			case "BROMUM" :
			case "br" :
			case "Br" :
			case "BR" :{b=34;
			break;
			}
			case "kry" :
			case "kryp" :
			case "krypt" :
			case "krypto" :
			case "krypton" :
			case "Kry" :
			case "Kryp" :
			case "Krypt" :
			case "Krypto" :
			case "Krypton" :
			case "KRY" :
			case "KRYP" :
			case "KRYPT" :
			case "KRYPTO" :
			case "KRYPTON" :
			case "kr" :
			case "Kr" :
			case "KR" :{b=35;
			break;
			}
			case "r" :
			case "rub" :
			case "rubi" :
			case "rubid" :
			case "rubidi" :
			case "rubidiu" :
			case "rubidium" :
			case "R" :
			case "Rub" :
			case "Rubi" :
			case "Rubid" :
			case "Rubidi" :
			case "Rubidiu" :
			case "Rubidium" :
			case "RUB" :
			case "RUBI" :
			case "RUBID" :
			case "RUBIDI" :
			case "RUBIDIU" :
			case "RUBIDIUM" :
			case "rb" :
			case "Rb" :
			case "RB" :{b=36;
			break;
			}
			case "str" :
			case "stro" :
			case "stron" :
			case "stront" :
			case "stronti" :
			case "strontiu" :
			case "strontium" :
			case "Str" :
			case "Stro" :
			case "Stron" :
			case "Stront" :
			case "Stronti" :
			case "Strontiu" :
			case "Strontium" :
			case "STR" :
			case "STRO" :
			case "STRON" :
			case "STRONT" :
			case "STRONTI" :
			case "STRONTIU" :
			case "STRONTIUM" :
			case "sr" :
			case "Sr" :
			case "SR" :{b=37;
			break;
			}
			case "yt" :
			case "ytt" :
			case "yttr" :
			case "yttri" :
			case "yttriu" :
			case "yttrium" :
			case "Yt" :
			case "Ytt" :
			case "Yttr" :
			case "Yttri" :
			case "Yttriu" :
			case "Yttrium" :
			case "YT" :
			case "YTT" :
			case "YTTR" :
			case "YTTRI" :
			case "YTTRIU" :
			case "YTTRIUM" :
			case "y" :
			case "Y" :{b=38;
			break;
			}
			case "zir" :
			case "zirk" :
			case "zirko" :
			case "zirkon" :
			case "Zir" :
			case "Zirk" :
			case "Zirko" :
			case "Zirkon" :
			case "ZIR" :
			case "ZIRK" :
			case "ZIRKO" :
			case "ZIRKON" :
			case "zr" :
			case "Zr" :
			case "ZR" :{b=39;
			break;
			}
			case "nio" :
			case "niob" :
			case "niobi" :
			case "niobiu" :
			case "niobium" :
			case "Nio" :
			case "Niob" :
			case "Niobi" :
			case "Niobiu" :
			case "Niobium" :
			case "NIO" :
			case "NIOB" :
			case "NIOBI" :
			case "NIOBIU" :
			case "NIOBIUM" :
			case "nb" :
			case "Nb" :
			case "NB" :{b=40;
			break;
			}
			case "mol" :
			case "moly" :
			case "molyb" :
			case "molybd" :
			case "molybdä" :
			case "molybdän" :
			case "molybdänu" :
			case "molybdänum" :
			case "molybda" :
			case "molybdae" :
			case "molybdaen" :
			case "molybdaenu" :
			case "molybdaenum" :
			case "Mol" :
			case "Moly" :
			case "Molyb" :
			case "Molybd" :
			case "Molybdä" :
			case "Molybdän" :
			case "Molybdänu" :
			case "Molybdänum" :
			case "Molybda" :
			case "Molybdae" :
			case "Molybdaen" :
			case "Molybdaenu" :
			case "Molybdaenum" :
			case "MOL" :
			case "MOLY" :
			case "MOLYB" :
			case "MOLYBD" :
			case "MOLYBDÄ" :
			case "MOLYBDÄN" :
			case "MOLYBDÄNU" :
			case "MOLYBDÄNUM" :
			case "MOLYBDA" :
			case "MOLYBDAE" :
			case "MOLYBDAEN" :
			case "MOLYBDAENU" :
			case "MOLYBDAENUM" :
			case "mo" :
			case "Mo" :
			case "MO" :{b=41;
			break;
			}
			case "tec" :
			case "tech" :
			case "techn" :
			case "techne" :
			case "technet" :
			case "techneti" :
			case "technetiu" :
			case "technetium" :
			case "Tec" :
			case "Tech" :
			case "Techn" :
			case "Techne" :
			case "Technet" :
			case "Techneti" :
			case "Technetiu" :
			case "Technetium" :
			case "TEC" :
			case "TECH" :
			case "TECHN" :
			case "TECHNE" :
			case "TECHNET" :
			case "TECHNETI" :
			case "TECHNETIU" :
			case "TECHNETIUM" :
			case "tc" :
			case "Tc" :
			case "TC" :{b=42;
			break;
			}
			case "rut" :
			case "ruth" :
			case "ruthe" :
			case "ruthen" :
			case "rutheni" :
			case "rutheniu" :
			case "ruthenium" :
			case "Rut" :
			case "Ruth" :
			case "Ruthe" :
			case "Ruthen" :
			case "Rutheni" :
			case "Rutheniu" :
			case "Ruthenium" :
			case "RUT" :
			case "RUTH" :
			case "RUTHE" :
			case "RUTHEN" :
			case "RUTHENI" :
			case "RUTHENIU" :
			case "RUTHENIUM" :
			case "ru" :
			case "Ru" :
			case "RU" :{b=43;
			break;
			}
			case "rho" :
			case "rhod" :
			case "rhodi" :
			case "rhodiu" :
			case "rhodium" :
			case "Rho" :
			case "Rhod" :
			case "Rhodi" :
			case "Rhodiu" :
			case "Rhodium" :
			case "RHO" :
			case "RHOD" :
			case "RHODI" :
			case "RHODIU" :
			case "RHODIUM" :
			case "rh" :
			case "Rh" :
			case "RH" :{b=44;
			break;
			}
			case "pal" :
			case "pall" :
			case "palla" :
			case "pallad" :
			case "palladi" :
			case "palladiu" :
			case "palladium" :
			case "Pal" :
			case "Pall" :
			case "Palla" :
			case "Pallad" :
			case "Palladi" :
			case "Palladiu" :
			case "Palladium" :
			case "PAL" :
			case "PALL" :
			case "PALLA" :
			case "PALLAD" :
			case "PALLADI" :
			case "PALLADIU" :
			case "PALLADIUM" :
			case "pd" :
			case "Pd" :
			case "PD" :{b=45;
			break;
			}
			case "silb" :
			case "silbe" :
			case "silber" :
			case "arge" :
			case "argen" :
			case "argent" :
			case "argentu" :
			case "argentum" :
			case "Silb" :
			case "Silbe" :
			case "Silber" :
			case "Arge" :
			case "Argen" :
			case "Argent" :
			case "Argentu" :
			case "Argentum" :
			case "SILB" :
			case "SILBE" :
			case "SILBER" :
			case "ARGE" :
			case "ARGEN" :
			case "ARGENT" :
			case "ARGENTU" :
			case "ARGENTUM" :
			case "ag" :
			case "Ag" :
			case "AG" :{b=46;
			break;
			}
			case "kad" :
			case "kadm" :
			case "kadmi" :
			case "kadmiu" :
			case "kadmium" :
			case "Kad" :
			case "Kadm" :
			case "Kadmi" :
			case "Kadmiu" :
			case "Kadmium" :
			case "KAD" :
			case "KADM" :
			case "KADMI" :
			case "KADMIU" :
			case "KADMIUM" :
			case "cad" :
			case "cadm" :
			case "cadmi" :
			case "cadmiu" :
			case "cadmium" :
			case "Cad" :
			case "Cadm" :
			case "Cadmi" :
			case "Cadmiu" :
			case "Cadmium" :
			case "CAD" :
			case "CADM" :
			case "CADMI" :
			case "CADMIU" :
			case "CADMIUM" :
			case "cd" :
			case "Cd" :
			case "CD" :{b=47;
			break;
			}
			case "ind" :
			case "indi" :
			case "indiu" :
			case "indium" :
			case "Ind" :
			case "Indi" :
			case "Indiu" :
			case "Indium" :
			case "IND" :
			case "INDI" :
			case "INDIU" :
			case "INDIUM" :
			case "in" :
			case "In" :
			case "IN" :{b=48;
			break;
			}
			case "zinn" :
			case "sta" :
			case "stan" :
			case "stann" :
			case "stannu" :
			case "stannum" :
			case "Zinn" :
			case "Sta" :
			case "Stan" :
			case "Stann" :
			case "Stannu" :
			case "Stannum" :
			case "ZINN" :
			case "STA" :
			case "STAN" :
			case "STANN" :
			case "STANNU" :
			case "STANNUM" :
			case "sn" :
			case "Sn" :
			case "SN" :{b=49;
			break;
			}
			case "an" :
			case "ant" :
			case "anti" :
			case "antim" :
			case "antimo" :
			case "antimon" :
			case "stib" :
			case "stibi" :
			case "stibiu" :
			case "stibium" :
			case "An" :
			case "Ant" :
			case "Anti" :
			case "Antim" :
			case "Antimo" :
			case "Antimon" :
			case "Stib" :
			case "Stibi" :
			case "Stibiu" :
			case "Stibium" :
			case "AN" :
			case "ANT" :
			case "ANTI" :
			case "ANTIM" :
			case "ANTIMO" :
			case "ANTIMON" :
			case "STIB" :
			case "STIBI" :
			case "STIBIU" :
			case "STIBIUM" :
			case "sb" :
			case "Sb" :
			case "SB" :{b=50;
			break;
			}
			case "tel" :
			case "tell" :
			case "tellu" :
			case "tellur" :
			case "telluri" :
			case "telluriu" :
			case "tellurium" :
			case "Tel" :
			case "Tell" :
			case "Tellu" :
			case "Tellur" :
			case "Telluri" :
			case "Telluriu" :
			case "Tellurium" :
			case "TEL" :
			case "TELL" :
			case "TELLU" :
			case "TELLUR" :
			case "TELLURI" :
			case "TELLURIU" :
			case "TELLURIUM" :
			case "te" :
			case "Te" :
			case "TE" :{b=51;
			break;
			}
			case "io" :
			case "iod" :
			case "iodi" :
			case "iodiu" :
			case "iodium" :
			case "Io" :
			case "Iod" :
			case "Iodi" :
			case "Iodiu" :
			case "Iodium" :
			case "IO" :
			case "IOD" :
			case "IODI" :
			case "IODIU" :
			case "IODIUM" :
			case "i" :
			case "I" :{b=52;
			break;
			}
			case "x" :
			case "xen" :
			case "xeno" :
			case "xenon" :
			case "X" :
			case "Xen" :
			case "Xeno" :
			case "Xenon" :
			case "XEN" :
			case "XENO" :
			case "XENON" :
			case "xe" :
			case "Xe" :
			case "XE" :{b=53;
			break;
			}
			case "cä" :
			case "cäs" :
			case "cäsi" :
			case "cäsiu" :
			case "cäsium" :
			case "cae" :
			case "caes" :
			case "caesi" :
			case "caesiu" :
			case "caesium" :
			case "Cä" :
			case "Cäs" :
			case "Cäsi" :
			case "Cäsiu" :
			case "Cäsium" :
			case "Cae" :
			case "Caes" :
			case "Caesi" :
			case "Caesiu" :
			case "Caesium" :
			case "CÄ" :
			case "CÄS" :
			case "CÄSI" :
			case "CÄSIU" :
			case "CÄSIUM" :
			case "CAE" :
			case "CAES" :
			case "CAESI" :
			case "CAESIU" :
			case "CAESIUM" :
			case "cs" :
			case "Cs" :
			case "CS" :{b=54;
			break;
			}
			case "bar" :
			case "bari" :
			case "bariu" :
			case "barium" :
			case "Bar" :
			case "Bari" :
			case "Bariu" :
			case "Barium" :
			case "BAR" :
			case "BARI" :
			case "BARIU" :
			case "BARIUM" :
			case "ba" :
			case "Ba" :
			case "BA" :{b=55;
			break;
			}
			case "l" :
			case "lan" :
			case "lant" :
			case "lanth" :
			case "lantha" :
			case "lanthan" :
			case "lanthanu" :
			case "lanthanum" :
			case "Lan" :
			case "Lant" :
			case "Lanth" :
			case "Lantha" :
			case "Lanthan" :
			case "Lanthanu" :
			case "Lanthanum" :
			case "LAN" :
			case "LANT" :
			case "LANTH" :
			case "LANTHA" :
			case "LANTHAN" :
			case "LANTHANU" :
			case "LANTHANUM" :
			case "la" :
			case "La" :
			case "LA" :{b=56;
			break;
			}
			case "cer" :
			case "ceri" :
			case "ceriu" :
			case "cerium" :
			case "Cer" :
			case "Ceri" :
			case "Ceriu" :
			case "Cerium" :
			case "CER" :
			case "CERI" :
			case "CERIU" :
			case "CERIUM" :
			case "ce" :
			case "Ce" :
			case "CE" :{b=57;
			break;
			}
			case "pra" :
			case "pras" :
			case "prase" :
			case "praseo" :
			case "praseod" :
			case "praseody" :
			case "praseodym" :
			case "praseodymi" :
			case "praseodymiu" :
			case "praseodymium" :
			case "Pra" :
			case "Pras" :
			case "Prase" :
			case "Praseo" :
			case "Praseod" :
			case "Praseody" :
			case "Praseodym" :
			case "Praseodymi" :
			case "Praseodymiu" :
			case "Praseodymium" :
			case "PRA" :
			case "PRAS" :
			case "PRASE" :
			case "PRASEO" :
			case "PRASEOD" :
			case "PRASEODY" :
			case "PRASEODYM" :
			case "PRASEODYMI" :
			case "PRASEODYMIU" :
			case "PRASEODYMIUM" :
			case "pr" :
			case "Pr" :
			case "PR" :{b=58;
			break;
			}
			case "neod" :
			case "neody" :
			case "neodym" :
			case "neodymi" :
			case "neodymiu" :
			case "neodymium" :
			case "Neod" :
			case "Neody" :
			case "Neodym" :
			case "Neodymi" :
			case "Neodymiu" :
			case "Neodymium" :
			case "NEOD" :
			case "NEODY" :
			case "NEODYM" :
			case "NEODYMI" :
			case "NEODYMIU" :
			case "NEODYMIUM" :
			case "nd" :
			case "Nd" :
			case "ND" :{b=59;
			break;
			}
			case "pro" :
			case "prom" :
			case "prome" :
			case "promet" :
			case "prometh" :
			case "promethi" :
			case "promethiu" :
			case "promethium" :
			case "Pro" :
			case "Prom" :
			case "Prome" :
			case "Promet" :
			case "Prometh" :
			case "Promethi" :
			case "Promethiu" :
			case "Promethium" :
			case "PRO" :
			case "PROM" :
			case "PROME" :
			case "PROMET" :
			case "PROMETH" :
			case "PROMETHI" :
			case "PROMETHIU" :
			case "PROMETHIUM" :
			case "pm" :
			case "Pm" :
			case "PM" :{b=60;
			break;
			}
			case "sam" :
			case "sama" :
			case "samar" :
			case "samari" :
			case "samariu" :
			case "samarium" :
			case "Sam" :
			case "Sama" :
			case "Samar" :
			case "Samari" :
			case "Samariu" :
			case "Samarium" :
			case "SAM" :
			case "SAMA" :
			case "SAMAR" :
			case "SAMARI" :
			case "SAMARIU" :
			case "SAMARIUM" :
			case "sm" :
			case "Sm" :
			case "SM" :{b=61;
			break;
			}
			case "eur" :
			case "euro" :
			case "europ" :
			case "europi" :
			case "europiu" :
			case "europium" :
			case "Eur" :
			case "Euro" :
			case "Europ" :
			case "Europi" :
			case "Europiu" :
			case "Europium" :
			case "EUR" :
			case "EURO" :
			case "EUROP" :
			case "EUROPI" :
			case "EUROPIU" :
			case "EUROPIUM" :
			case "eu" :
			case "Eu" :
			case "EU" :{b=62;
			break;
			}
			case "gad" :
			case "gado" :
			case "gadol" :
			case "gadoli" :
			case "gadolin" :
			case "gadolini" :
			case "gadoliniu" :
			case "gadolinium" :
			case "Gad" :
			case "Gado" :
			case "Gadol" :
			case "Gadoli" :
			case "Gadolin" :
			case "Gadolini" :
			case "Gadoliniu" :
			case "Gadolinium" :
			case "GAD" :
			case "GADO" :
			case "GADOL" :
			case "GADOLI" :
			case "GADOLIN" :
			case "GADOLINI" :
			case "GADOLINIU" :
			case "GADOLINIUM" :
			case "gd" :
			case "Gd" :
			case "GD" :{b=63;
			break;
			}
			case "ter" :
			case "terb" :
			case "terbi" :
			case "terbiu" :
			case "terbium" :
			case "Ter" :
			case "Terb" :
			case "Terbi" :
			case "Terbiu" :
			case "Terbium" :
			case "TER" :
			case "TERB" :
			case "TERBI" :
			case "TERBIU" :
			case "TERBIUM" :
			case "tb" :
			case "Tb" :
			case "TB" :{b=64;
			break;
			}
			case "d" :
			case "dys" :
			case "dysp" :
			case "dyspr" :
			case "dyspro" :
			case "dyspros" :
			case "dysprosi" :
			case "dysprosiu" :
			case "dysprosium" :
			case "D" :
			case "Dys" :
			case "Dysp" :
			case "Dyspr" :
			case "Dyspro" :
			case "Dyspros" :
			case "Dysprosi" :
			case "Dysprosiu" :
			case "Dysprosium" :
			case "DYS" :
			case "DYSP" :
			case "DYSPR" :
			case "DYSPRO" :
			case "DYSPROS" :
			case "DYSPROSI" :
			case "DYSPROSIU" :
			case "DYSPROSIUM" :
			case "dy" :
			case "Dy" :
			case "DY" :{b=65;
			break;
			}
			case "hol" :
			case "holm" :
			case "holmi" :
			case "holmiu" :
			case "holmium" :
			case "Hol" :
			case "Holm" :
			case "Holmi" :
			case "Holmiu" :
			case "Holmium" :
			case "HOL" :
			case "HOLM" :
			case "HOLMI" :
			case "HOLMIU" :
			case "HOLMIUM" :
			case "ho" :
			case "Ho" :
			case "HO" :{b=66;
			break;
			}
			case "erb" :
			case "erbi" :
			case "erbiu" :
			case "erbium" :
			case "Erb" :
			case "Erbi" :
			case "Erbiu" :
			case "Erbium" :
			case "ERB" :
			case "ERBI" :
			case "ERBIU" :
			case "ERBIUM" :
			case "er" :
			case "Er" :
			case "ER" :{b=67;
			break;
			}
			case "thu" :
			case "thul" :
			case "thuli" :
			case "thuliu" :
			case "thulium" :
			case "Thu" :
			case "Thul" :
			case "Thuli" :
			case "Thuliu" :
			case "Thulium" :
			case "THU" :
			case "THUL" :
			case "THULI" :
			case "THULIU" :
			case "THULIUM" :
			case "tm" :
			case "Tm" :
			case "TM" :{b=68;
			break;
			}
			case "ytte" :
			case "ytter" :
			case "ytterb" :
			case "ytterbi" :
			case "ytterbiu" :
			case "ytterbium" :
			case "Ytte" :
			case "Ytter" :
			case "Ytterb" :
			case "Ytterbi" :
			case "Ytterbiu" :
			case "Ytterbium" :
			case "YTTE" :
			case "YTTER" :
			case "YTTERB" :
			case "YTTERBI" :
			case "YTTERBIU" :
			case "YTTERBIUM" :
			case "yb" :
			case "Yb" :
			case "YB" :{b=69;
			break;
			}
			case "lut" :
			case "lute" :
			case "lutet" :
			case "luteti" :
			case "lutetiu" :
			case "lutetium" :
			case "Lut" :
			case "Lute" :
			case "Lutet" :
			case "Luteti" :
			case "Lutetiu" :
			case "Lutetium" :
			case "LUT" :
			case "LUTE" :
			case "LUTET" :
			case "LUTETI" :
			case "LUTETIU" :
			case "LUTETIUM" :
			case "lu" :
			case "Lu" :
			case "LU" :{b=70;	
			break;
			}
			case "ha" :
			case "haf" :
			case "hafn" :
			case "hafni" :
			case "hafniu" :
			case "hafnium" :
			case "Ha" :
			case "Haf" :
			case "Hafn" :
			case "Hafni" :
			case "Hafniu" :
			case "Hafnium" :
			case "HA" :
			case "HAF" :
			case "HAFN" :
			case "HAFNI" :
			case "HAFNIU" :
			case "HAFNIUM" :
			case "hf" :
			case "Hf" :
			case "HF" :{b=71;
			break;
			}
			case "tan" :
			case "tant" :
			case "tanta" :
			case "tantal" :
			case "tantalu" :
			case "tantalum" :
			case "Tan" :
			case "Tant" :
			case "Tanta" :
			case "Tantal" :
			case "Tantalu" :
			case "Tantalum" :
			case "TAN" :
			case "TANT" :
			case "TANTA" :
			case "TANTAL" :
			case "TANTALU" :
			case "TANTALUM" :
			case "ta" :
			case "Ta" :
			case "TA" :{b=72;
			break;
			}	
			case "wo" :
			case "wol" :
			case "wolf" :
			case "wolfr" :
			case "wolfra" :
			case "wolfram" :
			case "wolframi" :
			case "wolframiu" :
			case "wolframium" :
			case "Wo" :
			case "Wol" :
			case "Wolf" :
			case "Wolfr" :
			case "Wolfra" :
			case "Wolfram" :
			case "Wolframi" :
			case "Wolframiu" :
			case "Wolframium" :
			case "WO" :
			case "WOL" :
			case "WOLF" :
			case "WOLFR" :
			case "WOLFRA" :
			case "WOLFRAM" :
			case "WOLFRAMI" :
			case "WOLFRAMIU" :
			case "WOLFRAMIUM" :
			case "w" :
			case "W" :{b=73;
			break;
			}	
			case "rhe" :
			case "rhen" :
			case "rheni" :
			case "rheniu" :
			case "rhenium" :
			case "Rhe" :
			case "Rhen" :
			case "Rheni" :
			case "Rheniu" :
			case "Rhenium" :
			case "RHE" :
			case "RHEN" :
			case "RHENI" :
			case "RHENIU" :
			case "RHENIUM" :
			case "re" :
			case "Re" :
			case "RE" :{b=74;
			break;
			}	
			case "osm" :
			case "osmi" :
			case "osmiu" :
			case "osmium" :
			case "Osm" :
			case "Osmi" :
			case "Osmiu" :
			case "Osmium" :
			case "OSM" :
			case "OSMI" :
			case "OSMIU" :
			case "OSMIUM" :
			case "os" :
			case "Os" :
			case "OS" :{b=75;
			break;
			}	
			case "iri" :
			case "irid" :
			case "iridi" :
			case "iridiu" :
			case "iridium" :
			case "Iri" :
			case "Irid" :
			case "Iridi" :
			case "Iridiu" :
			case "Iridium" :
			case "IRI" :
			case "IRID" :
			case "IRIDI" :
			case "IRIDIU" :
			case "IRIDIUM" :
			case "ir" :
			case "Ir" :
			case "IR" :{b=76;
			break;
			}
			case "pl" :
			case "pla" :
			case "plat" :
			case "plati" :
			case "platin" :
			case "platinu" :
			case "platinum" :
			case "Pl" :
			case "Pla" :
			case "Plat" :
			case "Plati" :
			case "Platin" :
			case "Platinu" :
			case "Platinum" :
			case "PL" :
			case "PLA" :
			case "PLAT" :
			case "PLATI" :
			case "PLATIN" :
			case "PLATINU" :
			case "PLATINUM" :
			case "pt" :
			case "Pt" :
			case "PT" :{b=77;
			break;
			}	
			case "go" :
			case "gol" :
			case "gold" :
			case "aur" :
			case "auru" :
			case "aurum" :
			case "Go" :
			case "Gol" :
			case "Gold" :
			case "Aur" :
			case "Auru" :
			case "Aurum" :
			case "GO" :
			case "GOL" :
			case "GOLD" :
			case "AUR" :
			case "AURU" :
			case "AURUM" :
			case "au" :
			case "Au" :
			case "AU" :{b=78;
			break;
			}	
			default: b = 999;
			}
		
		return b;
		}


	public static int SwitchZwei(String ersteNutzerEingabe) {
		
		int b = 999;


		switch (ersteNutzerEingabe) {
		case "q" :
		case "qu" :
		case "que" :
		case "quec" :
		case "queck" :
		case "quecks" :
		case "quecksi" :
		case "quecksil" :
		case "quecksilb" :
		case "quecksilbe" :
		case "quecksilber" :
		case "hydra" :
		case "hydrar" :
		case "hydrarg" :
		case "hydrargy" :
		case "hydrargyr" :
		case "hydrargyru" :
		case "hydrargyrum" :
		case "Q" :
		case "Qu" :
		case "Que" :
		case "Quec" :
		case "Queck" :
		case "Quecks" :
		case "Quecksi" :
		case "Quecksil" :
		case "Quecksilb" :
		case "Quecksilbe" :
		case "Quecksilber" :
		case "Hydra" :
		case "Hydrar" :
		case "Hydrarg" :
		case "Hydrargy" :
		case "Hydrargyr" :
		case "Hydrargyru" :
		case "Hydrargyrum" :
		case "QU" :
		case "QUE" :
		case "QUEC" :
		case "QUECK" :
		case "QUECKS" :
		case "QUECKSI" :
		case "QUECKSIL" :
		case "QUECKSILB" :
		case "QUECKSILBE" :
		case "QUECKSILBER" :
		case "HYDRA" :
		case "HYDRAR" :
		case "HYDRARG" :
		case "HYDRARGY" :
		case "HYDRARGYR" :
		case "HYDRARGYRU" :
		case "HYDRARGYRUM" :
		case "hg" :
		case "Hg" :
		case "HG" :{b=79;
		break;
		}	
		case "tha" :
		case "thal" :
		case "thall" :
		case "thalli" :
		case "thalliu" :
		case "thallium" :
		case "Tha" :
		case "Thal" :
		case "Thall" :
		case "Thalli" :
		case "Thalliu" :
		case "Thallium" :
		case "THA" :
		case "THAL" :
		case "THALL" :
		case "THALLI" :
		case "THALLIU" :
		case "THALLIUM" :
		case "tl" :
		case "Tl" :
		case "TL" :{b=80;
		break;
		}	
		case "bl" :
		case "ble" :
		case "blei" :
		case "plu" :
		case "plum" :
		case "plumb" :
		case "plumbu" :
		case "plumbum" :
		case "Bl" :
		case "Ble" :
		case "Blei" :
		case "Plu" :
		case "Plum" :
		case "Plumb" :
		case "Plumbu" :
		case "Plumbum" :
		case "BL" :
		case "BLE" :
		case "BLEI" :
		case "PLU" :
		case "PLUM" :
		case "PLUMB" :
		case "PLUMBU" :
		case "PLUMBUM" :
		case "pb" :
		case "Pb" :
		case "PB" :{b=81;
		break;
		}
		case "bis" :
		case "bism" :
		case "bismu" :
		case "bismut" :
		case "bismuth" :
		case "bismuthu" :
		case "bismuthum" :
		case "Bis" :
		case "Bism" :
		case "Bismu" :
		case "Bismut" :
		case "Bismuth" :
		case "Bismuthu" :
		case "Bismuthum" :
		case "BIS" :
		case "BISM" :
		case "BISMU" :
		case "BISMUT" :
		case "BISMUTH" :
		case "BISMUTHU" :
		case "BISMUTHUM" :
		case "wi" :
		case "wis" :
		case "wism" :
		case "wismu" :
		case "wismut" :
		case "Wi" :
		case "Wis" :
		case "Wism" :
		case "Wismu" :
		case "Wismut" :
		case "WI" :
		case "WIS" :
		case "WISM" :
		case "WISMU" :
		case "WISMUT" :	
		case "bi" :
		case "Bi" :
		case "BI" :{b=82;
		break;
		}
		case "pol" :
		case "polo" :
		case "polon" :
		case "poloni" :
		case "poloniu" :
		case "polonium" :
		case "Pol" :
		case "Polo" :
		case "Polon" :
		case "Poloni" :
		case "Poloniu" :
		case "Polonium" :
		case "POL" :
		case "POLO" :
		case "POLON" :
		case "POLONI" :
		case "POLONIU" :
		case "POLONIUM" :
		case "po" :
		case "Po" :
		case "PO" :{b=83;
		break;
		}
		case "ast" :
		case "asta" :
		case "astat" :
		case "astati" :
		case "astatiu" :
		case "astatium" :
		case "Ast" :
		case "Asta" :
		case "Astat" :
		case "Astati" :
		case "Astatiu" :
		case "Astatium" :
		case "AST" :
		case "ASTA" :
		case "ASTAT" :
		case "ASTATI" :
		case "ASTATIU" :
		case "ASTATIUM" :
		case "at" :
		case "At" :
		case "AT" :{b=84;
		break;
		}
		case "rad" :
		case "rado" :
		case "radon" :
		case "Rad" :
		case "Rado" :
		case "Radon" :
		case "RAD" :
		case "RADO" :
		case "RADON" :
		case "rn" :
		case "Rn" :
		case "RN" :{b=85;
		break;
		}	
		case "fra" :
		case "fran" :
		case "frank" :
		case "franki" :
		case "frankiu" :
		case "frankium" :
		case "Fra" :
		case "Fran" :
		case "Frank" :
		case "Franki" :
		case "Frankiu" :
		case "Frankium" :
		case "FRA" :
		case "FRAN" :
		case "FRANK" :
		case "FRANKI" :
		case "FRANKIU" :
		case "FRANKIUM" :
		case "fr" :
		case "Fr" :
		case "FR" :{b=86;
		break;
		}
		case "radi" :
		case "radiu" :
		case "radium" :
		case "Radi" :
		case "Radiu" :
		case "Radium" :
		case "RADI" :
		case "RADIU" :
		case "RADIUM" :
		case "ra" :
		case "Ra" :
		case "RA" :{b=87;
		break;
		}
		case "act" :
		case "acti" :
		case "actin" :
		case "actini" :
		case "actiniu" :
		case "actinium" :
		case "ak" :
		case "akt" :
		case "akti" :
		case "aktin" :
		case "aktini" :
		case "aktiniu" :
		case "aktinium" :
		case "Act" :
		case "Acti" :
		case "Actin" :
		case "Actini" :
		case "Actiniu" :
		case "Actinium" :
		case "Ak" :
		case "Akt" :
		case "Akti" :
		case "Aktin" :
		case "Aktini" :
		case "Aktiniu" :
		case "Aktinium" :
		case "ACT" :
		case "ACTI" :
		case "ACTIN" :
		case "ACTINI" :
		case "ACTINIU" :
		case "ACTINIUM" :
		case "AK" :
		case "AKT" :
		case "AKTI" :
		case "AKTIN" :
		case "AKTINI" :
		case "AKTINIU" :
		case "AKTINIUM" :
		case "ac" :
		case "Ac" :
		case "AC" :{b=88;
		break;
		}
		case "tho" :
		case "thor" :
		case "thori" :
		case "thoriu" :
		case "thorium" :
		case "Tho" :
		case "Thor" :
		case "Thori" :
		case "Thoriu" :
		case "Thorium" :
		case "THO" :
		case "THOR" :
		case "THORI" :
		case "THORIU" :
		case "THORIUM" :
		case "th" :
		case "Th" :
		case "TH" :{b=89;
		break;
		}
		case "prot" :
		case "prota" :
		case "protac" :
		case "protact" :
		case "protacti" :
		case "protactin" :
		case "protactini" :
		case "protactiniu" :
		case "protactinium" :
		case "protak" :
		case "protakt" :
		case "protakti" :
		case "protaktin" :
		case "protaktini" :
		case "protaktiniu" :
		case "protaktinium" :
		case "Prot" :
		case "Prota" :
		case "Protak" :
		case "Protakt" :
		case "Protakti" :
		case "Protaktin" :
		case "Protaktini" :
		case "Protaktiniu" :
		case "Protaktinium" :
		case "Protac" :
		case "Protact" :
		case "Protacti" :
		case "Protactin" :
		case "Protactini" :
		case "Protactiniu" :
		case "Protactinium" :
		case "PROT" :
		case "PROTA" :
		case "PROTAC" :
		case "PROTACT" :
		case "PROTACTI" :
		case "PROTACTIN" :
		case "PROTACTINI" :
		case "PROTACTINIU" :
		case "PROTACTINIUM" :
		case "PROTAK" :
		case "PROTAKT" :
		case "PROTAKTI" :
		case "PROTAKTIN" :
		case "PROTAKTINI" :
		case "PROTAKTINIU" :
		case "PROTAKTINIUM" :
		case "pa" :
		case "Pa" :
		case "PA" :{b=90;
		break;
		}
		case "ur" :
		case "ura" :
		case "uran" :
		case "urani" :
		case "uraniu" :
		case "uranium" :
		case "Ur" :
		case "Ura" :
		case "Uran" :
		case "Urani" :
		case "Uraniu" :
		case "Uranium" :
		case "UR" :
		case "URA" :
		case "URAN" :
		case "URANI" :
		case "URANIU" :
		case "URANIUM" :
		case "u" :
		case "U" :{b=91;
		break;
		}
		case "nep" :
		case "nept" :
		case "neptu" :
		case "neptun" :
		case "neptuni" :
		case "neptuniu" :
		case "neptunium" :
		case "Nep" :
		case "Nept" :
		case "Neptu" :
		case "Neptun" :
		case "Neptuni" :
		case "Neptuniu" :
		case "Neptunium" :
		case "NEP" :
		case "NEPT" :
		case "NEPTU" :
		case "NEPTUN" :
		case "NEPTUNI" :
		case "NEPTUNIU" :
		case "NEPTUNIUM" :
		case "np" :
		case "Np" :
		case "NP" :{b=92;
		break;
		}
		case "plut" :
		case "pluto" :
		case "pluton" :
		case "plutoni" :
		case "plutoniu" :
		case "plutonium" :
		case "Plut" :
		case "Pluto" :
		case "Pluton" :
		case "Plutoni" :
		case "Plutoniu" :
		case "Plutonium" :
		case "PLUT" :
		case "PLUTO" :
		case "PLUTON" :
		case "PLUTONI" :
		case "PLUTONIU" :
		case "PLUTONIUM" :
		case "pu" :
		case "Pu" :
		case "PU" :{b=93;
		break;
		}
		case "ame" :
		case "amer" :
		case "ameri" :
		case "americ" :
		case "americi" :
		case "americiu" :
		case "americium" :
		case "amerik" :
		case "ameriki" :
		case "amerikiu" :
		case "amerikium" :
		case "Ame" :
		case "Amer" :
		case "Ameri" :
		case "Americ" :
		case "Americi" :
		case "Americiu" :
		case "Americium" :
		case "Amerik" :
		case "Ameriki" :
		case "Amerikiu" :
		case "Amerikium" :
		case "AME" :
		case "AMER" :
		case "AMERI" :
		case "AMERIC" :
		case "AMERICI" :
		case "AMERICIU" :
		case "AMERICIUM" :
		case "AMERIK" :
		case "AMERIKI" :
		case "AMERIKIU" :
		case "AMERIKIUM" :
		case "am" :
		case "Am" :
		case "AM" :{b=94;
		break;
		}
		case "cur" :
		case "curi" :
		case "curiu" :
		case "curium" :
		case "Cur" :
		case "Curi" :
		case "Curiu" :
		case "Curium" :
		case "CUR" :
		case "CURI" :
		case "CURIU" :
		case "CURIUM" :
		case "cm" :
		case "Cm" :
		case "CM" :{b=95;
		break;
		}
		case "berk" :
		case "berke" :
		case "berkel" :
		case "berkeli" :
		case "berkeliu" :
		case "berkelium" :
		case "Berk" :
		case "Berke" :
		case "Berkel" :
		case "Berkeli" :
		case "Berkeliu" :
		case "Berkelium" :
		case "BERK" :
		case "BERKE" :
		case "BERKEL" :
		case "BERKELI" :
		case "BERKELIU" :
		case "BERKELIUM" :
		case "bk" :
		case "Bk" :
		case "BK" :{b=96;
		break;
		}
		case "cal" :
		case "cali" :
		case "calif" :
		case "califo" :
		case "califor" :
		case "californ" :
		case "californi" :
		case "californiu" :
		case "californium" :
		case "Cal" :
		case "Cali" :
		case "Calif" :
		case "Califo" :
		case "Califor" :
		case "Californ" :
		case "Californi" :
		case "Californiu" :
		case "C" :
		case "CA" :
		case "CAL" :
		case "CALI" :
		case "CALIF" :
		case "CALIFO" :
		case "CALIFOR" :
		case "CALIFORN" :
		case "CALIFORNI" :
		case "CALIFORNIU" :
		case "CALIFORNIUM" :
		case "Californium" :
		case "cf" :
		case "Cf" :
		case "CF" :{b=97;
		break;
		}
		case "e" :
		case "ei" :
		case "ein" :
		case "eins" :
		case "einst" :
		case "einste" :
		case "einstei" :
		case "einstein" :
		case "einsteini" :
		case "einsteiniu" :
		case "einsteinium" :
		case "E" :
		case "Ei" :
		case "Ein" :
		case "Eins" :
		case "Einst" :
		case "Einste" :
		case "Einstei" :
		case "Einstein" :
		case "Einsteini" :
		case "Einsteiniu" :
		case "Einsteinium" :
		case "EI" :
		case "EIN" :
		case "EINS" :
		case "EINST" :
		case "EINSTE" :
		case "EINSTEI" :
		case "EINSTEIN" :
		case "EINSTEINI" :
		case "EINSTEINIU" :
		case "EINSTEINIUM" :
		case "es" :
		case "Es" :
		case "ES" :{b=98;
		break;
		}
		case "fer" :
		case "ferm" :
		case "fermi" :
		case "fermiu" :
		case "fermium" :
		case "Fer" :
		case "Ferm" :
		case "Fermi" :
		case "Fermiu" :
		case "Fermium" :
		case "FER" :
		case "FERM" :
		case "FERMI" :
		case "FERMIU" :
		case "FERMIUM" :
		case "fm" :
		case "Fm" :
		case "FM" :{b=99;
		break;
		}
		case "m" :
		case "me" :
		case "men" :
		case "mend" :
		case "mende" :
		case "mendel" :
		case "mendele" :
		case "mendelev" :
		case "mendelevi" :
		case "mendeleviu" :
		case "mendelevium" :
		case "Me" :
		case "Men" :
		case "Mend" :
		case "Mende" :
		case "Mendel" :
		case "Mendele" :
		case "Mendelev" :
		case "Mendelevi" :
		case "Mendeleviu" :
		case "Mendelevium" :
		case "M" :
		case "ME" :
		case "MEN" :
		case "MEND" :
		case "MENDE" :
		case "MENDEL" :
		case "MENDELE" :
		case "MENDELEV" :
		case "MENDELEVI" :
		case "MENDELEVIU" :
		case "MENDELEVIUM" :
		case "md" :
		case "Md" :
		case "MD" :{b=100;
		break;
		}
		case "n" :
		case "nob" :
		case "nobe" :
		case "nobel" :
		case "nobeli" :
		case "nobeliu" :
		case "nobelium" :
		case "Nob" :
		case "Nobe" :
		case "Nobel" :
		case "Nobeli" :
		case "Nobeliu" :
		case "Nobelium" :
		case "N" :
		case "NOB" :
		case "NOBE" :
		case "NOBEL" :
		case "NOBELI" :
		case "NOBELIU" :
		case "NOBELIUM" :
		case "no" :
		case "No" :
		case "NO" :{b=101;
		break;
		}
		case "l" :
		case "la" :
		case "law" :
		case "lawr" :
		case "lawre" :
		case "lawren" :
		case "lawrenc" :
		case "lawrenci" :
		case "lawrenciu" :
		case "lawrencium" :
		case "La" :
		case "Law" :
		case "Lawr" :
		case "Lawre" :
		case "Lawren" :
		case "Lawrenc" :
		case "Lawrenci" :
		case "Lawrenciu" :
		case "Lawrencium" :
		case "L" :
		case "LA" :
		case "LAW" :
		case "LAWR" :
		case "LAWRE" :
		case "LAWREN" :
		case "LAWRENC" :
		case "LAWRENCI" :
		case "LAWRENCIU" :
		case "LAWRENCIUM" :
		case "lr" :
		case "Lr" :
		case "LR" :{b=102;
		break;
		}
		case "r" :
		case "ru" :
		case "rut" :
		case "ruth" :
		case "ruthe" :
		case "ruther" :
		case "rutherf" :
		case "rutherfo" :
		case "rutherfor" :
		case "rutherford" :
		case "rutherfordi" :
		case "rutherfordiu" :
		case "rutherfordium" :
		case "Ru" :
		case "Rut" :
		case "Ruth" :
		case "Ruthe" :
		case "Ruther" :
		case "Rutherf" :
		case "Rutherfo" :
		case "Rutherfor" :
		case "Rutherford" :
		case "Rutherfordi" :
		case "Rutherfordiu" :
		case "Rutherfordium" :
		case "R" :
		case "RU" :
		case "RUT" :
		case "RUTH" :
		case "RUTHE" :
		case "RUTHER" :
		case "RUTHERF" :
		case "RUTHERFO" :
		case "RUTHERFOR" :
		case "RUTHERFORD" :
		case "RUTHERFORDI" :
		case "RUTHERFORDIU" :
		case "RUTHERFORDIUM" :
		case "rf" :
		case "Rf" :
		case "RF" :{b=103;
		break;
		}
		case "d" :
		case "du" :
		case "dub" :
		case "dubn" :
		case "dubni" :
		case "dubniu" :
		case "dubnium" :
		case "D" :
		case "Du" :
		case "Dub" :
		case "Dubn" :
		case "Dubni" :
		case "Dubniu" :
		case "Dubnium" :
		case "DU" :
		case "DUB" :
		case "DUBN" :
		case "DUBNI" :
		case "DUBNIU" :
		case "DUBNIUM" :
		case "db" :
		case "Db" :
		case "DB" :{b=104;
		break;
		}
		case "s" :
		case "se" :
		case "sea" :
		case "seab" :
		case "seabo" :
		case "seabor" :
		case "seaborg" :
		case "seaborgi" :
		case "seaborgiu" :
		case "seaborgium" :
		case "S" :
		case "Se" :
		case "Sea" :
		case "Seab" :
		case "Seabo" :
		case "Seabor" :
		case "Seaborg" :
		case "Seaborgi" :
		case "Seaborgiu" :
		case "Seaborgium" :
		case "SE" :
		case "SEA" :
		case "SEAB" :
		case "SEABO" :
		case "SEABOR" :
		case "SEABORG" :
		case "SEABORGI" :
		case "SEABORGIU" :
		case "SEABORGIUM" :
		case "un" :
		case "unn" :
		case "unni" :
		case "unnil" :
		case "unnilh" :
		case "unnilhe" :
		case "unnilhex" :
		case "unnilhexi" :
		case "unnilhexiu" :
		case "unnilhexium" :
		case "Un" :
		case "Unn" :
		case "Unni" :
		case "Unnil" :
		case "Unnilh" :
		case "Unnilhe" :
		case "Unnilhex" :
		case "Unnilhexi" :
		case "Unnilhexiu" :
		case "Unnilhexium" :
		case "UN" :
		case "UNN" :
		case "UNNI" :
		case "UNNIL" :
		case "UNNILH" :
		case "UNNILHE" :
		case "UNNILHEX" :
		case "UNNILHEXI" :
		case "UNNILHEXIU" :
		case "UNNILHEXIUM" :
		case "sg" :
		case "Sg" :
		case "SG" :{b=105;
		break;
		}
		case "b" :
		case "bo" :
		case "boh" :
		case "bohr" :
		case "bohri" :
		case "bohriu" :
		case "bohrium" :
		case "B" :
		case "Bo" :
		case "Boh" :
		case "Bohr" :
		case "Bohri" :
		case "Bohriu" :
		case "Bohrium" :
		case "BO" :
		case "BOH" :
		case "BOHR" :
		case "BOHRI" :
		case "BOHRIU" :
		case "BOHRIUM" :
		case "bh" :
		case "Bh" :
		case "BH" :{b=106;
		break;
		}
		case "h" :
		case "ha" :
		case "has" :
		case "hass" :
		case "hassi" :
		case "hassiu" :
		case "hassium" :
		case "H" :
		case "Ha" :
		case "Has" :
		case "Hass" :
		case "Hassi" :
		case "Hassiu" :
		case "Hassium" :
		case "HA" :
		case "HAS" :
		case "HASS" :
		case "HASSI" :
		case "HASSIU" :
		case "HASSIUM" :
		case "unnilo" :
		case "unniloc" :
		case "unniloct" :
		case "unnilocti" :
		case "unniloctiu" :
		case "unniloctium" :
		case "Unnilo" :
		case "Unniloc" :
		case "Unniloct" :
		case "Unnilocti" :
		case "Unniloctiu" :
		case "Unniloctium" :
		case "UNNILO" :
		case "UNNILOC" :
		case "UNNILOCT" :
		case "UNNILOCTI" :
		case "UNNILOCTIU" :
		case "UNNILOCTIUM" :
		case "hs" :
		case "Hs" :
		case "HS" :{b=107;
		break;
		}
		case "mei" :
		case "meit" :
		case "meitn" :
		case "meitne" :
		case "meitner" :
		case "meitneri" :
		case "meitneriu" :
		case "meitnerium" :
		case "Mei" :
		case "Meit" :
		case "Meitn" :
		case "Meitne" :
		case "Meitner" :
		case "Meitneri" :
		case "Meitneriu" :
		case "Meitnerium" :
		case "MEI" :
		case "MEIT" :
		case "MEITN" :
		case "MEITNE" :
		case "MEITNER" :
		case "MEITNERI" :
		case "MEITNERIU" :
		case "MEITNERIUM" :
		case "unnile" :
		case "unnilen" :
		case "unnilenn" :
		case "unnilenni" :
		case "unnilenniu" :
		case "unnilennium" :
		case "Unnile" :
		case "Unnilen" :
		case "Unnilenn" :
		case "Unnilenni" :
		case "Unnilenniu" :
		case "Unnilennium" :
		case "UNNILE" :
		case "UNNILEN" :
		case "UNNILENN" :
		case "UNNILENNI" :
		case "UNNILENNIU" :
		case "UNNILENNIUM" :
		case "mt" :
		case "Mt" :
		case "MT" :{b=108;
		break;
		}
		case "da" :
		case "dar" :
		case "darm" :
		case "darms" :
		case "darmst" :
		case "darmsta" :
		case "darmstad" :
		case "darmstadt" :
		case "darmstadti" :
		case "darmstadtiu" :
		case "darmstadtium" :
		case "Da" :
		case "Dar" :
		case "Darm" :
		case "Darms" :
		case "Darmst" :
		case "Darmsta" :
		case "Darmstad" :
		case "Darmstadt" :
		case "Darmstadti" :
		case "Darmstadtiu" :
		case "Darmstadtium" :
		case "DA" :
		case "DAR" :
		case "DARM" :
		case "DARMS" :
		case "DARMST" :
		case "DARMSTA" :
		case "DARMSTAD" :
		case "DARMSTADT" :
		case "DARMSTADTI" :
		case "DARMSTADTIU" :
		case "DARMSTADTIUM" :
		case "ds" :
		case "Ds" :
		case "DS" :{b=109;
		break;
		}
		case "ro" :
		case "roe" :
		case "roen" :
		case "roent" :
		case "roentg" :
		case "roentge" :
		case "roentgen" :
		case "roentgeni" :
		case "roentgeniu" :
		case "roentgenium" :
		case "Ro" :
		case "Roe" :
		case "Roen" :
		case "Roent" :
		case "Roentg" :
		case "Roentge" :
		case "Roentgen" :
		case "Roentgeni" :
		case "Roentgeniu" :
		case "Roentgenium" :
		case "RO" :
		case "ROE" :
		case "ROEN" :
		case "ROENT" :
		case "ROENTG" :
		case "ROENTGE" :
		case "ROENTGEN" :
		case "ROENTGENI" :
		case "ROENTGENIU" :
		case "ROENTGENIUM" :
		case "rg" :
		case "Rg" :
		case "RG" :{b=110;
		break;
		}
		case "c" :
		case "co" :
		case "cop" :
		case "cope" :
		case "coper" :
		case "copern" :
		case "coperni" :
		case "copernic" :
		case "copernici" :
		case "coperniciu" :
		case "copernicium" :
		case "Co" :
		case "Cop" :
		case "Cope" :
		case "Coper" :
		case "Copern" :
		case "Coperni" :
		case "Copernic" :
		case "Copernici" :
		case "Coperniciu" :
		case "Copernicium" :
		case "CO" :
		case "COP" :
		case "COPE" :
		case "COPER" :
		case "COPERN" :
		case "COPERNI" :
		case "COPERNIC" :
		case "COPERNICI" :
		case "COPERNICIU" :
		case "COPERNICIUM" :
		case "cn" :
		case "Cn" :
		case "CN" :{b=111;
		break;
		}
		case "ni" :
		case "nih" :
		case "niho" :
		case "nihon" :
		case "nihoni" :
		case "nihoniu" :
		case "nihonium" :
		case "Ni" :
		case "Nih" :
		case "Niho" :
		case "Nihon" :
		case "Nihoni" :
		case "Nihoniu" :
		case "Nihonium" :
		case "nh" :
		case "Nh" :
		case "NH" :
		case "NI" :
		case "NIH" :
		case "NIHO" :
		case "NIHON" :
		case "NIHONI" :
		case "NIHONIU" :
		case "NIHONIUM" :
		case "unu" :
		case "unun" :
		case "ununt" :
		case "ununtr" :
		case "ununtri" :
		case "ununtriu" :
		case "ununtrium" :
		case "Unu" :
		case "Unun" :
		case "Ununt" :
		case "Ununtr" :
		case "Ununtri" :
		case "Ununtriu" :
		case "Ununtrium" :
		case "UNU" :
		case "UNUN" :
		case "UNUNT" :
		case "UNUNTR" :
		case "UNUNTRI" :
		case "UNUNTRIU" :
		case "UNUNTRIUM" :
		case "uut" :
		case "Uut" :
		case "UUT" :{b=112;
		break;
		}
		case "fle" :
		case "fler" :
		case "flero" :
		case "flerov" :
		case "flerovi" :
		case "fleroviu" :
		case "flerovium" :
		case "Fle" :
		case "Fler" :
		case "Flero" :
		case "Flerov" :
		case "Flerovi" :
		case "Fleroviu" :
		case "Flerovium" :
		case "FLE" :
		case "FLER" :
		case "FLERO" :
		case "FLEROV" :
		case "FLEROVI" :
		case "FLEROVIU" :
		case "FLEROVIUM" :
		case "fl" :
		case "Fl" :
		case "FL" :{b=113;
		break;
		}
		case "mo" :
		case "mos" :
		case "mosc" :
		case "mosco" :
		case "moscov" :
		case "moscovi" :
		case "moscoviu" :
		case "moscovium" :
		case "Mo" :
		case "Mos" :
		case "Mosc" :
		case "Mosco" :
		case "Moscov" :
		case "Moscovi" :
		case "Moscoviu" :
		case "Moscovium" :
		case "MO" :
		case "MOS" :
		case "MOSC" :
		case "MOSCO" :
		case "MOSCOV" :
		case "MOSCOVI" :
		case "MOSCOVIU" :
		case "MOSCOVIUM" :
		case "ununp" :
		case "ununpe" :
		case "ununpen" :
		case "ununpent" :
		case "ununpenti" :
		case "ununpentiu" :
		case "ununpentium" :
		case "Ununp" :
		case "Ununpe" :
		case "Ununpen" :
		case "Ununpent" :
		case "Ununpenti" :
		case "Ununpentiu" :
		case "Ununpentium" :
		case "UNUNP" :
		case "UNUNPE" :
		case "UNUNPEN" :
		case "UNUNPENT" :
		case "UNUNPENTI" :
		case "UNUNPENTIU" :
		case "UNUNPENTIUM" :
		case "mc" :
		case "Mc" :
		case "MC" :
		case "uup" :
		case "Uup" :
		case "UUP" :{b=114;
		break;
		}
		case "li" :
		case "liv" :
		case "live" :
		case "liver" :
		case "liverm" :
		case "livermo" :
		case "livermor" :
		case "livermori" :
		case "livermoriu" :
		case "livermorium" :
		case "Li" :
		case "Liv" :
		case "Live" :
		case "Liver" :
		case "Liverm" :
		case "Livermo" :
		case "Livermor" :
		case "Livermori" :
		case "Livermoriu" :
		case "Livermorium" :
		case "LI" :
		case "LIV" :
		case "LIVE" :
		case "LIVER" :
		case "LIVERM" :
		case "LIVERMO" :
		case "LIVERMOR" :
		case "LIVERMORI" :
		case "LIVERMORIU" :
		case "LIVERMORIUM" :
		case "lv" :
		case "Lv" :
		case "LV" :{b=115;
		break;
		}
		case "t" :
		case "te" :
		case "ten" :
		case "tenn" :
		case "tenne" :
		case "tennes" :
		case "tenness" :
		case "tennessi" :
		case "tennessin" :
		case "tennessine" :
		case "T" :
		case "Te" :
		case "Ten" :
		case "Tenn" :
		case "Tenne" :
		case "Tennes" :
		case "Tenness" :
		case "Tennessi" :
		case "Tennessin" :
		case "Tennessine" :
		case "TE" :
		case "TEN" :
		case "TENN" :
		case "TENNE" :
		case "TENNES" :
		case "TENNESS" :
		case "TENNESSI" :
		case "TENNESSIN" :
		case "TENNESSINE" :
		case "ununs" :
		case "ununse" :
		case "ununsep" :
		case "ununsept" :
		case "ununsepti" :
		case "ununseptiu" :
		case "ununseptium" :
		case "ts" :
		case "Ts" :
		case "TS" :
		case "Ununs" :
		case "Ununsp" :
		case "Ununspe" :
		case "Ununspet" :
		case "Ununspeti" :
		case "Ununspetiu" :
		case "Ununspetium" :
		case "UNUNS" :
		case "UNUNSE" :
		case "UNUNSEP" :
		case "UNUNSEPT" :
		case "UNUNSEPTI" :
		case "UNUNSEPTIU" :
		case "UNUNSEPTIUM" :
		case "uus" :
		case "Uus" :
		case "UUS" :{b=116;
		break;
		}
		case "o" :
		case "oga" :
		case "ogan" :
		case "ogane" :
		case "oganes" :
		case "oganess" :
		case "oganesso" :
		case "oganesson" :
		case "O" :
		case "Oga" :
		case "Ogan" :
		case "Ogane" :
		case "Oganes" :
		case "Oganess" :
		case "Oganesso" :
		case "Oganesson" :
		case "OGA" :
		case "OGAN" :
		case "OGANE" :
		case "OGANES" :
		case "OGANESS" :
		case "OGANESSO" :
		case "OGANESSON" :
		case "ununo" :
		case "ununoc" :
		case "ununoct" :
		case "ununocti" :
		case "ununoctiu" :
		case "ununoctium" :
		case "Ununo" :
		case "Ununoc" :
		case "Ununoct" :
		case "Ununocti" :
		case "Ununoctiu" :
		case "Ununoctium" :
		case "UNUNO" :
		case "UNUNOC" :
		case "UNUNOCT" :
		case "UNUNOCTI" :
		case "UNUNOCTIU" :
		case "UNUNOCTIUM" :
		case "og" :
		case "Og" :
		case "OG" :
		case "uuo" :
		case "Uuo" :
		case "UUO" :{b=117;
		break;
		}
		//Spaß-Cases :D//
		case "" : {b=119;
		break;
		}
		case "k" :
		case "ko" :
		case "koh" :
		case "kohl" :
		case "kohle" :
		case "kohlee" :
		case "kohleer" :
		case "kohleerz" :
		case "K" :
		case "Ko" :
		case "Koh" :
		case "Kohl" :
		case "Kohle" :
		case "Kohlee" :
		case "Kohleer" :
		case "Kohleerz" :
		case "KO" :
		case "KOH" :
		case "KOHL" :
		case "KOHLE" :
		case "KOHLEE" :
		case "KOHLEER" :
		case "KOHLEERZ" :{b=120;
		break;	
		}
		case "eis" :
		case "eise" :
		case "eisen" :
		case "eisene" :
		case "eisener" :
		case "eisenerz" :
		case "Eis" :
		case "Eise" :
		case "Eisen" :
		case "Eisene" :
		case "Eisener" :
		case "Eisenerz" :
		case "EIS" :
		case "EISE" :
		case "EISEN" :
		case "EISENE" :
		case "EISENER" :
		case "EISENERZ" :{;b=121;
		break;
		}
		case "g" :
		case "go" :
		case "gol" :
		case "gold" :
		case "golde" :
		case "golder" :
		case "golderz" :
		case "G" :
		case "Go" :
		case "Gol" :
		case "Gold" :
		case "Golde" :
		case "Golder" :
		case "Golderz" :
		case "GO" :
		case "GOL" :
		case "GOLD" :
		case "GOLDE" :
		case "GOLDER" :
		case "GOLDERZ" :{b=122;
		break;	
		}
		case "di" :
		case "dia" :
		case "diam" :
		case "diama" :
		case "diaman" :
		case "diamant" :
		case "diamante" :
		case "diamanter" :
		case "diamanterz" :
		case "Di" :
		case "Dia" :
		case "Diam" :
		case "Diama" :
		case "Diaman" :
		case "Diamant" :
		case "Diamante" :
		case "Diamanter" :
		case "Diamanterz" :
		case "DI" :
		case "DIA" :
		case "DIAM" :
		case "DIAMA" :
		case "DIAMAN" :
		case "DIAMANT" :
		case "DIAMANTE" :
		case "DIAMANTER" :
		case "DIAMANTERZ" :{b=123;
		break;	
		}
		case "re" :
		case "red" :
		case "reds" :
		case "redst" :
		case "redsto" :
		case "redston" :
		case "redstone" :
		case "redstonee" :
		case "redstoneer" :
		case "redstoneerz" :
		case "Re" :
		case "Red" :
		case "Reds" :
		case "Redst" :
		case "Redsto" :
		case "Redston" :
		case "Redstone" :
		case "Redstonee" :
		case "Redstoneer" :
		case "Redstoneerz" :
		case "RE" :
		case "RED" :
		case "REDS" :
		case "REDST" :
		case "REDSTO" :
		case "REDSTON" :
		case "REDSTONE" :
		case "REDSTONEE" :
		case "REDSTONEER" :
		case "REDSTONEERZ" :{b=124;
		break;	
		}
		case "sm" :
		case "sma" :
		case "smar" :
		case "smara" :
		case "smarag" :
		case "smaragd" :
		case "smaragde" :
		case "smaragder" :
		case "smaragderz" :
		case "Sm" :
		case "Sma" :
		case "Smar" :
		case "Smara" :
		case "Smarag" :
		case "Smaragd" :
		case "Smaragde" :
		case "Smaragder" :
		case "Smaragderz" :
		case "SM" :
		case "SMA" :
		case "SMAR" :
		case "SMARA" :
		case "SMARAG" :
		case "SMARAGD" :
		case "SMARAGDE" :
		case "SMARAGDER" :
		case "SMARAGDERZ" :{b=125;
		break;	
		}
		case "lap" :
		case "lapi" :
		case "lapis" :
		case "lapisl" :
		case "lapisla" :
		case "lapislaz" :
		case "lapislazu" :
		case "lapislazul" :
		case "lapislazuli" :
		case "lapislazulie" :
		case "lapislazulier" :
		case "lapislazulierz" :
		case "Lap" :
		case "Lapi" :
		case "Lapis" :
		case "Lapisl" :
		case "Lapisla" :
		case "Lapislaz" :
		case "Lapislazu" :
		case "Lapislazul" :
		case "Lapislazuli" :
		case "Lapislazulie" :
		case "Lapislazulier" :
		case "Lapislazulierz" :
		case "LAP" :
		case "LAPI" :
		case "LAPIS" :
		case "LAPISL" :
		case "LAPISLA" :
		case "LAPISLAZ" :
		case "LAPISLAZU" :
		case "LAPISLAZUL" :
		case "LAPISLAZULI" :
		case "LAPISLAZULIE" :
		case "LAPISLAZULIER" :
		case "LAPISLAZULIERZ" :{b=126;
		break;	
		}
		case "ne" :
		case "net" :
		case "neth" :
		case "nethe" :
		case "nether" :
		case "netherq" :
		case "netherqu" :
		case "netherqua" :
		case "netherquar" :
		case "netherquarz" :
		case "netherquarze" :
		case "netherquarzer" :
		case "netherquarzerz" :
		case "Ne" :
		case "Net" :
		case "Neth" :
		case "Nethe" :
		case "Nether" :
		case "Netherq" :
		case "Netherqu" :
		case "Netherqua" :
		case "Netherquar" :
		case "Netherquarz" :
		case "Netherquarze" :
		case "Netherquarzer" :
		case "Netherquarzerz" :
		case "NE" :
		case "NET" :
		case "NETH" :
		case "NETHE" :
		case "NETHER" :
		case "NETHERQ" :
		case "NETHERQU" :
		case "NETHERQUA" :
		case "NETHERQUAR" :
		case "NETHERQUARZ" :
		case "NETHERQUARZE" :
		case "NETHERQUARZER" :
		case "NETHERQUARZERZ" :{b=127;
		break;	
		}
		default: {b = 999;}
		break;
		
		}//Switch-Ende
		
		if (b == 999) {
		JOptionPane.showMessageDialog(null, "Dieses Element gibt es nicht!" + "\n\nFür den Entwickler: " + ersteNutzerEingabe);
		}
		
		return b;
	}

	public static int SwitchALT(String EINGABE) {
		int a = 999;
		
		a = SwitchEins(EINGABE);
		 if(a == 999) {
		a = SwitchZwei(EINGABE);	 
		}
		 return a;
	}
	
	
	
	
	
	
	
	}
	

